### ISSUE TITLE
joint_tests error term

### ISSUE THREAD

**Issue by mattansb** [rvlenth/emmeans#100]
Would it be possible to add to the `data.frame` resulting from `joint_tests()` each `F.ratio`'s `SE`?Similar to how `test()` returns an `SE` for each `t.ratio`?

**Comment by rvlenth** [comment]
I think that is not exactly what you mean: while *t* statistics are ratios of estimates and their standard errors (SEs), there is no SE in the computation of most *F* statistics. Regular ANOVA *F*s are presented as the ratio of a numerator and denominator mean square; and I surmise that you would like to see the denominators (*and* the numerators too, right?). However, that is not possible here, at least not uniquely, due to the way the statistics are computed. They are computed using a quadratic form like this:

    t(L %*% b) %*% solve(L %*% V %*% t(L)) %*% (L %*% b) / r

where `b` is the vector of fixed-effect estimates, `L` is a matrix of coefficients applied to `b`, `V` is the covariance matrix of `b`, and `r` is the rank of `L`. This is equivalent to a ratio of mean squares in certain cases, but in sophisticated mixed models and such, one would be hard put to formulate this as the ratio of two mean squares.

So, no, it really isn't possible to add this information to the results of `joint_tests()`.

**Comment by mattansb** [comment]
Very interesting - thanks for the answer!
I actually was less interested in the numerator, and really would like the SE, as some journals require reporting SEs for each test statistic. Do you have any suggestions or ideas for how I might produce these myself for the F ratios produced by `joint_tests()` (for a standard, simple, bread and butter linear ANOVA model)?

**Comment by rvlenth** [comment]
Sorry -- I guess I just don't understand what you're wanting, as I don't recall seeing an *F* statistic with a SE accompanying it. SEs accompany *estimates* of various things, and *F* ratios are not estimates but just test statistics. If you show me an example of a journal article where you have seen an *F* ratio with a standard error, that might help me see what it is you are looking for.

**Comment by rvlenth** [comment]
Seeing no recent comments, I'm closing this
