### ISSUE TITLE
emmeans for a MCMCglmm object: object 'trait' not found in the case of a multinomial logit model

### ISSUE THREAD

**Issue by atrolle** [rvlenth/emmeans#102]
Hi Russell,

I'm using `emmeans` for plotting marginal effects for a multinomial logit model.
To build that model, I used `MCMCglmm` since I could see it was supported by your package.
Here is the command: 
```
model.mcmc <- MCMCglmm(yvar ~ -1 + trait + trait:(Year + Gender + Module + Year:Module),
                           rcov = ~us(trait):units, family = "categorical", data = data, prior = priors,
                            nitt = 40000, thin = 10, burnin = 20000, pr=FALSE, pl=TRUE)
```
`yvar` is the categorical response (a factor with 9 levels); `Year` is a factor with 3 levels, `Gender` a factor with 2 levels and `Module` a factor with 8 levels.
To write this command, I followed the tutorial at [http://natalialevshina.com/Documents/MCMCglmm_Tutorial.pdf].

But, when creating the interaction plot with:
```
emmip(model.mcmc, yvar ~ Module | (Year + Gender), data = data, type = "response",
            CIs = TRUE, adjust = "tukey", plotit = TRUE)
```
I have the following error:

> Error in eval(predvars, data, env) : object 'trait' not found

I'm not sure to understand this error: when looking at your file `MCMC-support.R`, the function `recover_data.MCMCglmm` seems to handle the case of multivariate responses.

Could you enlighten me on that?

Thank you,
Arnaud.

**Comment by rvlenth** [comment]
Thanks for your message. The short answer is "I don't know." I have very little understanding of these models and I tried to cobble support for them anyway. I should be more honest about that in the `models` vignette.

Technically, part of what goes wrong is that the response variable is a single variable. My (apparently incorrect) understanding had been that the `trait` factor only appears in a model where the response is multivariate. So my code looks for a multivariate response and cobbles together an expanded data matrix using the columns of the multivariate response as the levels of `trait`. In your model, that code is bypassed and `trait` is not generated. 

Here is my attempt to work around this, using the `letting` data and example in your link (I named the model `letting.mod` rather than just `m`). I basically do manually what is described above...
```
letfake = rbind(letting,letting,letting)
letfake$trait = rep(levels(letting$LetVerb), each = nrow(letting))
```
This doesn't work:
```
> rg <- ref_grid(letting.mod, data=letfake)
Error in ref_grid(letting.mod, data = letfake) : 
  Non-conformable elements in reference grid.
 Probably due to rank deficiency not handled as expected.
In addition: Warning message:
In mean.default(y) : argument is not numeric or logical: returning NA
```
However, if I look at the coefficients, I see that there are none for the first level of `trait`, so I tried again using just the part of `letfake` that does not involve the first level:
```
> rg23 <- ref_grid(letting.mod, data=letfake[-(1:nrow(letting)), ])
NOTE: A nesting structure was detected in the fitted model:
    Channel %in% trait, CrSem %in% trait
Warning message:
In mean.default(y) : argument is not numeric or logical: returning NA

> rg23
'emmGrid' object with variables:
    trait = allow, permit
    Channel = Spoken, Written
    CrSem = Anim, Inanim
    MS = 0.0013502
    LetVerb = response variable with mean NA
Nesting structure:  Channel %in% trait, CrSem %in% trait
```
This "works" but I don't think it's right either, because it omits the first trait. Nonetheless, here are its predictions:
```
> summary(rg23)
 trait  Channel CrSem       MS prediction lower.HPD upper.HPD
 allow  Spoken  Anim   0.00135    -1.3577    -2.234    -0.467
 permit Spoken  Anim   0.00135    -7.9465   -10.783    -4.911
 allow  Written Anim   0.00135    -0.0327    -0.389     0.317
 permit Written Anim   0.00135    -3.1711    -4.146    -2.039
 allow  Spoken  Inanim 0.00135     2.0933     1.036     3.184
 permit Spoken  Inanim 0.00135    -3.2966    -6.658    -0.696
 allow  Written Inanim 0.00135     3.4480     2.792     4.133
 permit Written Inanim 0.00135     1.4237     0.283     2.490

HPD interval probability: 0.95
```
BTW, the nesting statement is a result of using a shortcut way to specify the model (where there are no explicit main effects for `Channel` or `CrSem`). IMHO, this is a sloppy way to specify a model if you really don't want to imply that it is nested. Put `nesting = NULL` in the `ref_grid` call to suppress that.

I am especially confused here because `trait` is essentially a synonym for `LetVerb`; thus `LetVerb`, to my mind, appears as both a dependent and independent variable. What am I missing?

I am not sure I can fix this without getting the developer of **MCMCglmm** involved. I have tried to urge package developers to incorporate **emmeans** support for their models in their own packages, to make sure it's done right. So far, I've had very little luck with this. Obviously, `MCMCglmm` can fit all kinds of models, so the fact that some of them don't work in **emmeans** is not really a surprise. But I should make this clearer in the documentation.

**Comment by atrolle** [comment]
Hi Russell,

I'm sorry for my late response.
Actually, I've been working further on that issue for the last days, with your observations as a starting point.
I'm also confused with the `trait` factor. As you mentioned it, for the `letting` data, `trait` has 2 levels, that is, the categories for the dependent variable except the baseline category.
In particular, I've been looking for how to get predicted probabilities for the baseline category, but haven't found any solution. I couldn't see any useful information in the model outputs.
I'm going to test another MCMC package: `brms`.
I've seen that `emmeans` could support simpler models, right?
Anyway, thank you so much for your great work with `emmeans`.

**Comment by rvlenth** [comment]
In R, the factory default for factors is to omit the first level and code the remaining levels of a factor as dummy variables. So my guess is that `baseline` isn't actually excluded, it is just used as the reference level. But that still doesn't tell me what to do to get predictions at all 3 levels of `trait`. I have a guess on what to do, but it is only a guess, and I can't see a way to confirm whether or not it is right.

Meanwhile, with `brms`, the **emmeans** support is again only basic, and I'm not sure it will work for you. I hope it does for your sake. And I'll keep my fingers crossed that if it appears to work, it is also providing the right answers. (If you have a way of checking, it'd be a very good idea!)

**Comment by rvlenth** [comment]
After investigating further, I think that -- inadvertently -- the hack I gave you earlier yields the correct results. The estimates are of log p_j - log p_1, and one way to back-transform them is to just take the estimate of log p_1 to be zero. Then exponentiate and scale so that they sum to 1. I read-in the summary results above into a data frame named `summ` and did this:
```
> (pred = rbind(0, matrix(summ$prediction, nrow = 2)))
        [,1]    [,2]    [,3]   [,4]
[1,]  0.0000  0.0000  0.0000 0.0000
[2,] -1.3577 -0.0327  2.0933 3.4480
[3,] -7.9465 -3.1711 -3.2966 1.4237

> apply(pred, 2, function(x) exp(x) / sum(exp(x)))
             [,1]       [,2]        [,3]       [,4]
[1,] 0.7951618063 0.49756534 0.109305766 0.02732994
[2,] 0.2045567870 0.48155810 0.886648961 0.85918369
[3,] 0.0002814067 0.02087656 0.004045273 0.11348637
```
These are our estimates of the multinomial probabilities for each combination of `Channel` and `CrSem`.

I compared this with results from `nnet::multinom`:
```
> library(nnet)
> let.multi = multinom(LetVerb ~ Channel + CrSem + MS, data = letting)
 ... (chatter omitted) ...
> summary(ref_grid(let.multi))
 Channel CrSem       MS LetVerb   prob     SE df
 Spoken  Anim   0.00135 let     0.7925 0.0569  8
 Written Anim   0.00135 let     0.5105 0.0258  8
 Spoken  Inanim 0.00135 let     0.1590 0.0618  8
 Written Inanim 0.00135 let     0.0428 0.0125  8
 Spoken  Anim   0.00135 allow   0.1911 0.0545  8
 Written Anim   0.00135 allow   0.3452 0.0237  8
 Spoken  Inanim 0.00135 allow   0.7304 0.0920  8
 Written Inanim 0.00135 allow   0.5511 0.0351  8
 Spoken  Anim   0.00135 permit  0.0164 0.0124  8
 Written Anim   0.00135 permit  0.1442 0.0196  8
 Spoken  Inanim 0.00135 permit  0.1106 0.0761  8
 Written Inanim 0.00135 permit  0.4061 0.0356  8
```
I think this is a comparable model, with a frequentist solution. The estimated probabilities are kinda the same as those derived above, though there are pretty big discrepancies (note each set of 4 ests corresponds to a row of the matrix above). But if you look at the MCMC traces, it is clear that the mixing in the MCMCglmm model is very, very slow, so I'm not too surprised.

**Comment by atrolle** [comment]
> 
> 
> In R, the factory default for factors is to omit the first level and code the remaining levels of a factor as dummy variables. So my guess is that `baseline` isn't actually excluded, it is just used as the reference level. But that still doesn't tell me what to do to get predictions at all 3 levels of `trait`. I have a guess on what to do, but it is only a guess, and I can't see a way to confirm whether or not it is right.
> 
> Meanwhile, with `brms`, the **emmeans** support is again only basic, and I'm not sure it will work for you. I hope it does for your sake. And I'll keep my fingers crossed that if it appears to work, it is also providing the right answers. (If you have a way of checking, it'd be a very good idea!)

Hi Russell,

I tested a `brms` model. Computation time was very long. Finally, it came to its end.
But, as you were afraid of, `emmeans` does not work for a multinomial logistic model (`categorical` family of `brms`).
Actually, in the function `recover_data.brmsfit`, in the code `mt = attr(model.frame(bt$dpars$mu$fe, data = object$data), "terms")`, the term `mu` is not valid for such a model; in the ouput, the field `bt$dpars$mu` is replaced with `J-1` fields of the type `bt$dpars$muXXX`, with `J`: number of categories for the dependent variable, and `muXXX`: `mu` paramater for category `XXX`.

**Comment by atrolle** [comment]
> 
> 
> After investigating further, I think that -- inadvertently -- the hack I gave you earlier yields the correct results. The estimates are of log p_j - log p_1, and one way to back-transform them is to just take the estimate of log p_1 to be zero. Then exponentiate and scale so that they sum to 1. I read-in the summary results above into a data frame named `summ` and did this:
> 
> ```
> > (pred = rbind(0, matrix(summ$prediction, nrow = 2)))
>         [,1]    [,2]    [,3]   [,4]
> [1,]  0.0000  0.0000  0.0000 0.0000
> [2,] -1.3577 -0.0327  2.0933 3.4480
> [3,] -7.9465 -3.1711 -3.2966 1.4237
> 
> > apply(pred, 2, function(x) exp(x) / sum(exp(x)))
>              [,1]       [,2]        [,3]       [,4]
> [1,] 0.7951618063 0.49756534 0.109305766 0.02732994
> [2,] 0.2045567870 0.48155810 0.886648961 0.85918369
> [3,] 0.0002814067 0.02087656 0.004045273 0.11348637
> ```
> 
> These are our estimates of the multinomial probabilities for each combination of `Channel` and `CrSem`.
> 
> I compared this with results from `nnet::multinom`:
> 
> ```
> > library(nnet)
> > let.multi = multinom(LetVerb ~ Channel + CrSem + MS, data = letting)
>  ... (chatter omitted) ...
> > summary(ref_grid(let.multi))
>  Channel CrSem       MS LetVerb   prob     SE df
>  Spoken  Anim   0.00135 let     0.7925 0.0569  8
>  Written Anim   0.00135 let     0.5105 0.0258  8
>  Spoken  Inanim 0.00135 let     0.1590 0.0618  8
>  Written Inanim 0.00135 let     0.0428 0.0125  8
>  Spoken  Anim   0.00135 allow   0.1911 0.0545  8
>  Written Anim   0.00135 allow   0.3452 0.0237  8
>  Spoken  Inanim 0.00135 allow   0.7304 0.0920  8
>  Written Inanim 0.00135 allow   0.5511 0.0351  8
>  Spoken  Anim   0.00135 permit  0.0164 0.0124  8
>  Written Anim   0.00135 permit  0.1442 0.0196  8
>  Spoken  Inanim 0.00135 permit  0.1106 0.0761  8
>  Written Inanim 0.00135 permit  0.4061 0.0356  8
> ```
> 
> I think this is a comparable model, with a frequentist solution. The estimated probabilities are kinda the same as those derived above, though there are pretty big discrepancies (note each set of 4 ests corresponds to a row of the matrix above). But if you look at the MCMC traces, it is clear that the mixing in the MCMCglmm model is very, very slow, so I'm not too surprised.

Nice!
Do you think it possible to implement this solution somewhere in the `emmeans` package?

**Comment by rvlenth** [comment]
I was looking at it, but the deeper I look, the more impossible it seems. The reason that my estimates were just in the ballpark instead of closer is that I was missing some scaling factors. See the bottom of p.97 in the developer's "course notes" -- https://cran.r-project.org/web/packages/MCMCglmm/vignettes/CourseNotes.pdf. I need a factor something like `sqrt(1 + k * (16 * sqrt(3) / (15 * pi))^2)`, where `k` depends on the diagonal of a matrix used for setting the prior, and does not appear to be recoverable from the model object.

It is a mystery why this software would create fixed-effect estimates that have such an obscure interpretation, but I'm pretty discouraged in being able to support this in **emmeans**.

**Comment by rvlenth** [comment]
The latest push to github has multinomial support that seems to be right for this particular example, but it depends on an assumption that `diag(IJ) = 2 / k`, which I think is just suggested in examples but may not always be true.

```
> ### `mod` is a model for the `letting` data, but a new MCMC run
> emmeans(mod, ~ LetVerb | Channel * CrSem, data = letting, mode = "prob")
NOTE: A nesting structure was detected in the fitted model:
    Channel %in% trait, CrSem %in% trait
Channel = Spoken, CrSem = Anim:
 LetVerb    prob lower.HPD upper.HPD
 let     0.75689  5.94e-01    0.8929
 allow   0.23899  1.12e-01    0.4073
 permit  0.00239  5.14e-05    0.0136

Channel = Written, CrSem = Anim:
 LetVerb    prob lower.HPD upper.HPD
 let     0.47725  3.91e-01    0.5716
 allow   0.46443  3.82e-01    0.5415
 permit  0.05729  2.91e-02    0.0927

Channel = Spoken, CrSem = Inanim:
 LetVerb    prob lower.HPD upper.HPD
 let     0.10751  2.52e-02    0.2290
 allow   0.86344  7.25e-01    0.9591
 permit  0.02226  4.65e-04    0.1085

Channel = Written, CrSem = Inanim:
 LetVerb    prob lower.HPD upper.HPD
 let     0.03022  8.21e-03    0.0495
 allow   0.74704  6.57e-01    0.8406
 permit  0.22155  1.26e-01    0.3094

HPD interval probability: 0.95

> ### For comparison, the same model fitted with nnet::multinom
> emmeans(let.multi, ~ LetVerb | Channel * CrSem)
Channel = Spoken, CrSem = Anim:
 LetVerb   prob     SE df lower.CL upper.CL
 let     0.7925 0.0569  8   0.6612   0.9237
 allow   0.1911 0.0545  8   0.0654   0.3169
 permit  0.0164 0.0124  8  -0.0121   0.0449

Channel = Written, CrSem = Anim:
 LetVerb   prob     SE df lower.CL upper.CL
 let     0.5105 0.0258  8   0.4511   0.5700
 allow   0.3452 0.0237  8   0.2905   0.3999
 permit  0.1442 0.0196  8   0.0990   0.1895

Channel = Spoken, CrSem = Inanim:
 LetVerb   prob     SE df lower.CL upper.CL
 let     0.1590 0.0618  8   0.0165   0.3015
 allow   0.7304 0.0920  8   0.5182   0.9427
 permit  0.1106 0.0761  8  -0.0648   0.2859

Channel = Written, CrSem = Inanim:
 LetVerb   prob     SE df lower.CL upper.CL
 let     0.0428 0.0125  8   0.0139   0.0717
 allow   0.5511 0.0351  8   0.4702   0.6321
 permit  0.4061 0.0356  8   0.3239   0.4883

Confidence level used: 0.95 
```

**Comment by atrolle** [comment]
I had a look at the "course notes". I guess you were talking about the following code:
```
Delta <- cbind(c(-1, 1, 0), c(-1, 0, 1))
c2 <- (16 * sqrt(3)/(15 * pi))^2
D <- ginv(Delta %*% t(Delta)) %*% Delta
Int <- t(apply(m5c.1$Sol, 1, function(x) {D %*% (x/sqrt(1 + c2 * diag(IJ)))}))
summary(mcmc(exp(Int)/rowSums(exp(Int))))
```
The only variables I can see are `Delta`, the contrast matrix (with `J` rows and `J-1` columns, `J` being the number of categories of the dependent variable) and `IJ`, the prior for the residual covariance matrix, that one may define in a general way:
`IJ <- (1/J) * (diag(J) + matrix(1, J-1, J-1))`
For both variables, the key parameter seems to be `J`, the number of categories of the dependent variable.
Isn't `J` recoverable from the model object? Or have I missed anything?

**Comment by rvlenth** [comment]
Just a note -- Some of this stuff (marginalizing wrt random effects) seems related to issue #99.

**Comment by atrolle** [comment]
Sorry, I'm not sure to see the link between this issue and issue #99.
Actually, in the `letting` data example, there are no random effects to be marginalized, if I'm not wrong.

**Comment by rvlenth** [comment]
My understanding (see the "Course Notes" vignette for **MCMCglmm**, p.35), is that `MCMCglmm()` *always* assumes an additive over-dispersion model, even when there are no random effects; and the fancy adjustments involving factors like `c2 = (16 * sqrt{3} / (15 * pi))^2` (seen in the example on p.97 of those notes, and discussed in Section 2.5, p.47) are related to back-transforming from the logit in the presence of this over-dispersion variance. So that's the connection.

That said, it seems odd to me that the `lessing` model, as well as the ones for `SShorns` in the notes, that this over-dispersion variance is held fixed at its prior value of $2/3$, rather than being estimated. There's a lot (most) of these notes that I haven't read, and I imagine it is justified there somehow. Maybe it's akin to the continuity correction we often use with discrete data.

**Comment by atrolle** [comment]
Thank you for your feedback.
I now see your point. It is necessary to adjust the back-transformation with a factor `c2 = (16 * sqrt(3) / (15 * pi))^2` (for a logit link function).

But I'm still a bit lost.
If I go back to the case of a multinomial logit model, and refer to a previous post
> The only variables I can see are `Delta`, the contrast matrix (with `J` rows and `J-1` columns, `J` being the number of categories of the dependent variable) and `IJ`, the prior for the residual covariance matrix, that one may define in a general way:
> `IJ <- (1/J) * (diag(J) + matrix(1, J-1, J-1))`
> For both variables, the key parameter seems to be `J`, the number of categories of the dependent variable.

it appears to me that, if this is true, all the information necessary for running `emmeans` could be recoverable from the `MCMCglmm` object.
I can work on it, if you permit me.

**Comment by rvlenth** [comment]
Thanks, but I have my own plans for how to deal with this. The needed info is indeed recoverable from the model object, but not in general in the way you describe.

Sent from my iPhone

On May 7, 2019, at 1:33 AM, atrolle <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for your feedback.
I now see your point. It is necessary to adjust the back-transformation with a factor c2 = (16 * sqrt(3) / (15 * pi))^2 (for a logit link function).

But I'm still a bit lost.
If I go back to the case of a multinomial logit model, and refer to a previous post

The only variables I can see are Delta, the contrast matrix (with J rows and J-1 columns, J being the number of categories of the dependent variable) and IJ, the prior for the residual covariance matrix, that one may define in a general way:
IJ <- (1/J) * (diag(J) + matrix(1, J-1, J-1))
For both variables, the key parameter seems to be J, the number of categories of the dependent variable.

it appears to me that, if this is true, all the information necessary for running emmeans could be recoverable from the MCMCglmm object.
I can work on it, if you permit me.

**Comment by atrolle** [comment]
Hi Russell,

Ok. Sorry for that.
I could see you recently modified the file `MCMC-support.R`.
Thank you so much.
I downloaded again `emmeans` and tested it.

When running `ref_grid` for a multinomial model obtained with `MCMCglmm`, an error occurred.
Actually, it is likely to come from line 240 in `MCMC-support.R` (with `recover_data.MCMCglmm`).
With the latest version of the package `MCMCglmm` available from CRAN, `object$family[1]` can equal `"multinomial"`, not `"multinomial1"`.
After correction, there's still a warning message:
> In addition: Warning message:
> In nobs.default(object, use.fallback = TRUE) :
>   no 'nobs' method is available

I really don't know what can cause this warning.
Would you have an idea?
I use R 3.6.0 for Windows.

**Comment by rvlenth** [comment]
I've been quiet on this for awhile. But I have made some changes, including trapping that warning message. `MCMCglmm` is a monster, and I am sure I am a long ways from supporting everything. But the way you'd use it for multinomial logit models has changed -- see the `"models"` vignette. You now specify `trait = <resp.name>` and `mode = "multinomial"`

There are a bunch of other changes in the **emmeans** package, many having to do with prediction and bias adjustment when back-transforming. The latter is kind of inspired by this conversation.  I have prepared version 1.3.5 and sent it to CRAN, but as of noon June 8 they haven't posted it.

**Comment by atrolle** [comment]
Hi Russell,

No worries.
Thank you very much for these updates.

**Comment by rvlenth** [comment]
No recent traffic on this. Some support has been added in recent updates. I think it unlikely that fuller support for MCMCglmm is unlikely unless the developer of that package wants to incorporate and support the **emmeans** functionality within the **MCMCglmm** package.
