### ISSUE TITLE
Question about Tukey comparisons 

### ISSUE THREAD

**Issue by dshelldhillon** [rvlenth/emmeans#109]
Hi great sir,
I would like to first thank you for making such an excellent package. It has made my analysis so much easier.  

I have a question about Tukey pairwise comparisons.  

I am running a two factorial Anova and also including the interaction term for the two factors.  A priori I believed that the interaction term would be important to include and after running the model the interaction term is significant.  

Now I'd like to run Tukey pairwise comparisons. There's two ways I did it.  But I'm not quite sure I uderstand the difference in the two methods.  

## Data Prep
```r
outcome <- rnorm(144,9.477,20) ## Response 
factor1 <- c(1,2,3,4,5,6) ## Factor 1 
factor2 <- c("A","B","C","D","E","F") ## Factor 2
block  <- c(1,2) ## Blocking factor 
test <- cbind(factor1,factor2,block) %>% as_tibble()
df_q <- test %>%
  tidyr :: expand(factor1,factor2,block)
df_emmeans <- df_q %>% ## Since each has two replicates 
  bind_rows(df_q) %>%
  cbind(outcome)
```
`df_emmeans` is final data  

## Linear Model  
```r
m1 <- lm(outcome ~ factor1*factor2 + block, data = df_emmeans)
```

#### Tukey pairwise comparison METHOD 1 
```r
emmeans(m1, pairwise ~ factor1 |factor2, adjust = "tukey")$contrasts
```
*This says tukey method for comparing a family of 6 estimates* 

#### Tukey pairwise compariosn METHOD 2   
```r
pairs(emmeans(m1, ~factor1*factor2, adjust = "tukey")) 
```
*This says tukey method for comparing a family of 36 estimates*

Which of these above two methods would correctly control the Tukey pairwise family error rate? 
For method 1, I'm not making comparisons that aren't meaningful to me, which is what I'd like, but I want to make sure I'm still preserving the family wise error rate in method 1.  

Thank you!!

**Comment by rvlenth** [comment]
First, you should identify which comparisons you are interested in, and which you are not. You should try to avoid testing comparisons that you are not interested in. So if your method 2 has a lot of unwanted comparisons, don't do that. (Also, I'll comment that the `adjust` argument should go in the `pairs` call, outside of the `emmeans` call; but it is unnecessary anyway, as Tukey is the default.)

If your method 1 includes all of the comparisons you want, then that's what you should use. But do you also want pairwise comparisons of `factor2` for each level of `factor1`?

In most cases, I'd recommend something like this:
```r
emm = emmeans(m1, ~ factor1*factor2)
emm   ## view the means
pairs(emm, simple = "each")
```
The last call is the same as two calls to `pairs`, using each factor as a `by` variable.

The last concern is what you want to correct for. The above does a Tukey multiplicity adjustment considering a "family" defined by each set of means for one factor, with each level of the other factor. So in your example, that is 6 families of comparisons for `factor1` and 6 families of comparisons for `factor2`, for a total of 12 separate families and a total of 15*12 = 180 tests. Each of those 12 families is Tukey-adjusted *separately*. You could consider combining these into larger families -- say, two sets of 90 comparisons each:
```r
lapply(pairs(emm, simple = "each"), rbind, adjust = "mvt")
```
The Tukey adjustment is no longer appropriate here, because Tukey is based on *one* set of pairwise comparisons. I recommend using the "mvt" method, which is more-or-less exact based on the correlation structure of the combined sets.

To make this more concrete, consider a smaller example. For the separate families ...
```r
> warp.lm = lm(breaks ~ wool * tension, data = warpbreaks)

> emm = emmeans(warp.lm, ~ wool * tension)
> pairs(emm, simple = "each")
$`simple contrasts for wool`
tension = L:
 contrast estimate   SE df t.ratio p.value
 A - B       16.33 5.16 48  3.167  0.0027 

tension = M:
 contrast estimate   SE df t.ratio p.value
 A - B       -4.78 5.16 48 -0.926  0.3589 

tension = H:
 contrast estimate   SE df t.ratio p.value
 A - B        5.78 5.16 48  1.120  0.2682 


$`simple contrasts for tension`
wool = A:
 contrast estimate   SE df t.ratio p.value
 L - M      20.556 5.16 48  3.986  0.0007 
 L - H      20.000 5.16 48  3.878  0.0009 
 M - H      -0.556 5.16 48 -0.108  0.9936 

wool = B:
 contrast estimate   SE df t.ratio p.value
 L - M      -0.556 5.16 48 -0.108  0.9936 
 L - H       9.444 5.16 48  1.831  0.1704 
 M - H      10.000 5.16 48  1.939  0.1389 

P value adjustment: tukey method for comparing a family of 3 estimates
```
 For the combined families, ...
```r
> lapply(pairs(emm, simple = "each"), rbind, adjust = "mvt")
$`simple contrasts for wool`
 tension contrast estimate   SE df t.ratio p.value
 L       A - B       16.33 5.16 48  3.167  0.0081 
 M       A - B       -4.78 5.16 48 -0.926  0.7318 
 H       A - B        5.78 5.16 48  1.120  0.6028 

P value adjustment: mvt method for 3 tests 

$`simple contrasts for tension`
 wool contrast estimate   SE df t.ratio p.value
 A    L - M      20.556 5.16 48  3.986  0.0013 
 A    L - H      20.000 5.16 48  3.878  0.0018 
 A    M - H      -0.556 5.16 48 -0.108  1.0000 
 B    L - M      -0.556 5.16 48 -0.108  1.0000 
 B    L - H       9.444 5.16 48  1.831  0.3080 
 B    M - H      10.000 5.16 48  1.939  0.2553 

P value adjustment: mvt method for 6 tests
```

**Comment by dshelldhillon** [comment]
Thanks for the informative response!  This was really helpful!
