### ISSUE TITLE
emmip converts co-variates to factors

### ISSUE THREAD

**Issue by ekatko1** [rvlenth/emmeans#122]
Whereas the example provided in the documentation works well for graphing [1], converting continuous variables into factors is not desirable when the correct spacing between values along the x-axis is important. Instead, it would be desirable to have a continuous x-axis.

[1] https://cran.r-project.org/web/packages/emmeans/vignettes/basics.html#plots

**Comment by rvlenth** [comment]
Well, maybe, but if the model specifies it as a factor, how is `emmip()`  supposed to know you want it treated like a numeric variable? I can imagine lots of cases where you would want it treated like a factor. So even if I were to try to detect whether the levels of a factor could possibly be numeric values, I don't think I would want to change the default behavior of `emmip()`.

Note: you can always do something like:
```r
plot_data <- emmip(..., plotit = FALSE)
ggplot(..., data = plot_data)
```
That is, you can save the plotted points in a data.frame, then plot those results in any manner that you please. I provide that capability precisely because graphics production is not the primary goal of the **emmeans** package.

**Comment by rvlenth** [comment]
Seeing no additional comments on this issue, I am closing it. But let me know if there are additional questions.
