### ISSUE TITLE
question about emmeans post-hoc analysis

### ISSUE THREAD

**Issue by Mengxia-Fu** [rvlenth/emmeans#125]
Hi Russ,

I have a question about post-hoc analyses using emmeans function. The model I am using has four independent variables, pre-test scores, group (4 levels), time (4 levels), and the interaction between group and time. The dependent variable is post-test scores. I would like to know the differences between the four groups in terms of their post-test scores at each time point while controlling for the effects of pre-test scores. My model is:

mod<-lmer(posttest scores~pre-test scores+group+time+group*time+(1|Subject),data=GJT)

For the post-hoc analyses, I used emmeans. The R code is:

emmeans(mod, list(pairwise~group|time), adjust="bonferroni")

My question is: Do the pair-wise comparisons carried out through emmeans account for the influence of pre-test scores? Because the omnibus test shows that the effect of pre-test scores is significant, I would like to exclude the influence of pre-test scores on pair-wise comparisons. 

Your suggestions and comments will be highly appreciated. Thanks in advance.

Mengxia

**Comment by rvlenth** [comment]
I saw your question on the R mixed models group too, but am slow in answering due to other things going on.

Yes, there is an adjustment for pre-test scores. The estimates are based on predictions at the average pre-test score, so each EMM contains an added term of the form `beta_j*pretest_avg`. Including pre-test in the model removes the variations due to pre-test from the residual error, thus reducing the SE of the EMMs. In differences of the EMMs, note that each EMM has exactly the same `beta_j*pretest_avg` value, thus those quantities cancel out in the pairwise comparisons.

**Comment by Mengxia-Fu** [comment]
Hi Russell,

Thank you very much for your detailed explanation!

Best regards,

Mengxia

**Comment by Mengxia-Fu** [comment]
Thank you very much for the detailed explanation!

Best regards,

Mengxia
