### ISSUE TITLE
odds ratios for contrast method = "del.eff" ?

### ISSUE THREAD

**Issue by benwhalley** [rvlenth/emmeans#134]
Given a stan_glmer model with binomial link, this produces odds ratios `contrast(emmeans(m, ~itemtype, type="response"), method = "eff")`, but this doesn't: `contrast(emmeans(m, ~itemtype, type="response"), method = "del.eff")`

Is that expected? exp(x) seem like reasonable ORs

**Comment by rvlenth** [comment]
Thanks for your report. It appears that the problem comes from a piece of code that purportedly tests that we have a true contrast (coefs sum to zero):
```r
    true.con = all(zapsmall(apply(cmat, 2, sum)) == 0) # each set of coefs sums to 0
```
However, running debug on a similar example (via `example(as.mcmc.emmGrid)` I get this:
```r
Browse[2]> cmat
    1 effect   2 effect   3 effect   4 effect
1  1.0000000 -0.3333333 -0.3333333 -0.3333333
2 -0.3333333  1.0000000 -0.3333333 -0.3333333
3 -0.3333333 -0.3333333  1.0000000 -0.3333333
4 -0.3333333 -0.3333333 -0.3333333  1.0000000

zapsmall(apply(cmat, 2, sum))
    1 effect     2 effect     3 effect     4 effect 
5.551115e-17 5.551115e-17 5.551115e-17 5.551115e-17
```
Obviously, I am expecting `zapsmall()` to do something other than what it does. I'll change the test to contain a tolerance of some sort. This is a case that should have passed the test, but didn't.

You'll see a notice when I've pushed an update that addresses this.

**Comment by rvlenth** [comment]
Works correctly now. 
```r
> contrast(emmeans(cbpp.rg, ~period), type = "response", method = "del.eff")
 contrast odds.ratio lower.HPD upper.HPD
 1 effect      3.278     1.997     5.243
 2 effect      0.924     0.436     1.617
 3 effect      0.781     0.350     1.399
 4 effect      0.434     0.109     0.867

Results are back-transformed from the log odds ratio scale 
HPD interval probability: 0.95
```
Thanks again. Am closing as this is resolved.
