### ISSUE TITLE
Contrast for binomial: difference in p(success) rather than OR?

### ISSUE THREAD

**Issue by benwhalley** [rvlenth/emmeans#135]
This might be a feature request...

Is it possible to get a contrast expressed as the absolute difference in probabilities between cells, rather than an OR? (I'm trying to express this with a `stan_glmer model`)

**Comment by rvlenth** [comment]
Yes, it is already possible. Read the vignette on transformations, with particular attention to “timing us everything” and the `regrid()` function.

Russ

Sent from my iPhone

On Aug 19, 2019, at 12:30 PM, Ben Whalley <notifications@github.com<mailto:notifications@github.com>> wrote:


This might be a feature request...

Is it possible to get a contrast expressed as the absolute difference in probabilities between cells, rather than an OR? (I'm trying to express this with a stan_glmer model)

**Comment by rvlenth** [comment]
I think this issue is resolved, so am closing it.
