### ISSUE TITLE
parallel foreach and emmeans produce an error

### ISSUE THREAD

**Issue by MatsuuraKentaro** [rvlenth/emmeans#139]
```R
library(emmeans)
library(mvtnorm)
library(foreach)
library(doParallel)

calc_emmeans <- function(d) {
  fit <- nlme:::gls(data = d, y ~ TRT*TIME, 
                    correlation = corSymm(form = ~ 1 | ID), 
                    weights = varIdent(form = ~ 1 | TIME))
  res <- emmeans(object=fit, specs=list(pairwise ~ TRT*TIME), df=N-1, adjust='none', data=d)
  res[['pairwise differences of TRT, TIME']]
}

N <- 200
N0 <- N/2
N1 <- N/2
D <- 3
TRT <- c(rep(1, N0), rep(2, N1))
mu_TIME <- list(c(-5, -8, -9), c(-8, -13, -15))
cov <- matrix(c(20,10,5,10,20,10,5,10,20), D, D)

registerDoParallel(3)

sim_result <- foreach(seed=1:9, .combine=rbind, .packages=c('nlme', 'emmeans', 'mvtnorm')) %dopar% {
  set.seed(seed)
  x <- sapply(1:N, function(i) { rmvnorm(1, mean=-2.1*TRT[i] + mu_TIME[[TRT[i]]], sigma=cov)})
  d <- data.frame(ID=factor(rep(1:N, each=D)), 
                  TRT=factor(rep(TRT, each=D)), 
                  TIME=factor(rep(1:3, len=length(x))), 
                  y=as.vector(x))
  res <- data.frame(seed=seed, calc_emmeans(d))
}

stopImplicitCluster()
```
The above code produces the following error:
```
Error in { : 
  task 1 failed - "Unable to estimate Satterthwaite parameters"
```

However, it works when I execute sequentially instead of in parallel:
```R
...

sim_result <- foreach(seed=1:9, .combine=rbind, .packages=c('nlme', 'emmeans', 'mvtnorm')) %do% {
  set.seed(seed)
  x <- sapply(1:N, function(i) { rmvnorm(1, mean=-2.1*TRT[i] + mu_TIME[[TRT[i]]], sigma=cov)})
  d <- data.frame(ID=factor(rep(1:N, each=D)), 
                  TRT=factor(rep(TRT, each=D)), 
                  TIME=factor(rep(1:3, len=length(x))), 
                  y=as.vector(x))
  res <- data.frame(seed=seed, calc_emmeans(d))
}
```

Other libraries such as DoseFinding, survival and rstan can be parallelized without errors. Could you tell me if you have any hints to solve it?

**Comment by rvlenth** [comment]
I don't think this has anything to do with parallelization. The error comes from the support codem for `gls` objects, which defaults to a Satterthwaite method for obtaining degrees of freedom; and that code errored for some reason. 

This exposes a different problem. Even though you specified `df` in your call, the way it works is that the default d.f. method is implemented, then it is overridden by your supplied value. I need to consider a better approach, since sometimes the d.f. setups involve elaborate calculations -- as is the case for `gls` objects -- and in your case, it caused an error.

The quick way to get this to work in your example is to add an argument to the `emmeans()` call: `mode = "df.error"` -- this will ask for a much simpler df method and avoid the error message (see `vignette("models", "emmeans")`, section K). And I believe it will side-step the error condition that you observed. 

I actually think you should also remove the argument `df = N-1`, because that definitely *over*-estimates the d.f. -- but that's up to you.

I will look at more efficient and reliable ways to handle cases where `df` is supplied, and will reference this issue when I have an update.

**Comment by MatsuuraKentaro** [comment]
`mode = "df.error"` works for me. Thank you very much.

**Comment by rvlenth** [comment]
I think this is resolved, so I'm closing this issue. I will however try to make `gls` support more robust in the future.
