### ISSUE TITLE
passing args to `recover_data` via `emtrends`

### ISSUE THREAD

**Issue by mattansb** [rvlenth/emmeans#145]
Unlike `emmeans` (via `ref_grid`), `emtrends` does not support passing custom arguments (`...`) to `recover_data`:

https://github.com/rvlenth/emmeans/blob/18ac9fcb54380960c8932e1cfc7eb83bac0824cf/R/emtrends.R#L103

https://github.com/rvlenth/emmeans/blob/18ac9fcb54380960c8932e1cfc7eb83bac0824cf/R/emtrends.R#L108

(But does to `emm_basis`)

**Comment by rvlenth** [comment]
This is a very thorny issue, for various reasons:

  * A `mode` argument, if specified, gets mismatched to the `model` argument unless one is very careful
  * In most cases where custom arguments are needed in `recover_data()`, some post-processing is required in the reference grid, and that post-processing basically can't be done the way `emtrends()` is currently coded.

Here's an example where I tried it with the dots arguments passed to `recover_data()`
```r
> library(ordinal)
> wine$botno = as.numeric(wine$bottle)   ## yes, this is really lame but I needed a covariate
> mod = clm(rating ~ temp * botno, data = wine)

> emt = emtrends(mod, ~rating|temp, var="botno", mode="prob")
Error in data[[var]] : subscript out of bounds

> # same call with named 'model' argument
> emt = emtrends(model = mod, ~rating|temp, var="botno", mode="prob")
> emt

temp = cold:
 rating botno.trend SE  df asymp.LCL asymp.UCL
 1           nonEst NA Inf        NA        NA
 2           nonEst NA Inf        NA        NA
 3           nonEst NA Inf        NA        NA
 4           nonEst NA Inf        NA        NA
 5           nonEst NA Inf        NA        NA

temp = warm:
 rating botno.trend SE  df asymp.LCL asymp.UCL
 1           nonEst NA Inf        NA        NA
 2           nonEst NA Inf        NA        NA
 3           nonEst NA Inf        NA        NA
 4           nonEst NA Inf        NA        NA
 5           nonEst NA Inf        NA        NA

Confidence level used: 0.95 
```
What happened here is that the grid was set up for the probabilities for each `rating` , but the difference quotients couldn't be computed correctly because the grid for those was set up with `mode = linear.predictor` (no post-processing was done to get the probabilities). It's amazing actually that we didn't get an error.

I agree that this is not ideal, but simply passing dots to `recover_data()` just makes things worse, not better. I think I need to ponder this and decide what kind of re-engineering of `emtrends()` is needed. Or at least explain its limitations in the documentation...

**Comment by rvlenth** [comment]
I think I have a much more robust implementation now. For the earlier example:

```r
> emtrends(mod, ~ rating | temp, "botno", mode = "prob")
temp = cold:
 rating botno.trend     SE  df asymp.LCL asymp.UCL
 1          -0.0213 0.0100 Inf  -0.04095  -0.00164
 2          -0.1084 0.0477 Inf  -0.20182  -0.01494
 3           0.0437 0.0472 Inf  -0.04874   0.13615
 4           0.0602 0.0504 Inf  -0.03856   0.15903
 5           0.0257 0.0289 Inf  -0.03097   0.08244

temp = warm:
 rating botno.trend     SE  df asymp.LCL asymp.UCL
 1          -0.0237 0.0257 Inf  -0.07402   0.02658
 2          -0.1204 0.0673 Inf  -0.25242   0.01152
 3           0.0489 0.0888 Inf  -0.12518   0.22295
 4           0.0668 0.0209 Inf   0.02581   0.10776
 5           0.0285 0.0122 Inf   0.00465   0.05235

Confidence level used: 0.95 
```

The 1st argument is renamed `object` so it doesn't get tangled up with `mode`

**Comment by rvlenth** [comment]
Yet new improvements to `emmtrends()`. All model-class options are supported now, as well as correct handling of `cov.reduce` when it is a formula. All in all, we have more efficient code because the needed grid is now set up entirely within `ref_grid()`, with appropriate hooks. I think this issue is now resolved when the changes are pushed up. But let me know if you see anything strange.
