### ISSUE TITLE
Negative probabilities with clmm?

### ISSUE THREAD

**Issue by frousseu** [rvlenth/emmeans#154]
Hello

I am getting negative lower bounds of predicted probabilities from emmeans when predicting values from a clmm model.

```r
library(ordinal)
library(emmeans)

m <- clmm(rating ~ temp + contact + (1|judge), data = wine)	

e<-emmeans(m, ~ rating | temp, mode = "prob")

e

temp = cold:
 rating    prob      SE  df asymp.LCL asymp.UCL
 1      0.09761 0.05626 Inf -0.012656    0.2079
 2      0.52233 0.09102 Inf  0.343931    0.7007
 3      0.33106 0.08617 Inf  0.162164    0.4999
 4      0.04088 0.02550 Inf -0.009112    0.0909
 5      0.00814 0.00656 Inf -0.004719    0.0210

temp = warm:
 rating    prob      SE  df asymp.LCL asymp.UCL
 1      0.00530 0.00461 Inf -0.003733    0.0143
 2      0.09866 0.05073 Inf -0.000772    0.1981
 3      0.44653 0.08363 Inf  0.282622    0.6104
 4      0.30982 0.08237 Inf  0.148386    0.4713
 5      0.13969 0.06838 Inf  0.005665    0.2737
```

Is that intended behaviour? 
Thank you

**Comment by rvlenth** [comment]
I would say it is not unintended, in the sense that the estimates and SEs are all on the `prob` scale, and the underlying machinery constructs CIs using normal theory: estimate +/- tcrit * SE. In the estimates exist on the link scale, we would compute the CIs and then back-transform; but that is not the case (see #155)

**Comment by rvlenth** [comment]
One way to obtain in-bounds intervals would be to fit a Bayesian model. Then each MCMC run would yield a set of nonnegative `prob` values, and thus the HPD interval would not go into negative territory.

**Comment by rvlenth** [comment]
# A simple fix
Construct confidence intervals for *log p*, and back-transform those:
```r
> summary(regrid(e, "log"), type = "response")
temp = cold:
 rating response      SE  df asymp.LCL asymp.UCL
 1       0.09761 0.05626 Inf  0.031541    0.3021
 2       0.52233 0.09102 Inf  0.371204    0.7350
 3       0.33106 0.08617 Inf  0.198766    0.5514
 4       0.04088 0.02550 Inf  0.012032    0.1389
 5       0.00814 0.00656 Inf  0.001676    0.0395

temp = warm:
 rating response      SE  df asymp.LCL asymp.UCL
 1       0.00530 0.00461 Inf  0.000964    0.0291
 2       0.09866 0.05073 Inf  0.036012    0.2703
 3       0.44653 0.08363 Inf  0.309338    0.6446
 4       0.30982 0.08237 Inf  0.184001    0.5217
 5       0.13969 0.06838 Inf  0.053515    0.3646

Results are averaged over the levels of: contact 
Confidence level used: 0.95 
Intervals are back-transformed from the log scale
```
So the SEs printed are the same (forward and then reverse from the delta method), but the CIs stay positive -- quite a bit more positive, actually.

## Bias adjustment
An additional thing to consider is that when there is a nonlinear link function, back-transformed estimates become biased when there are random effects. There is a bias adjustment that can be made, but it depends on the SD of the random effects. Note:
```r
> summary(m)
    . . .
Random effects:
 Groups Name        Variance Std.Dev.
 judge  (Intercept) 1.279    1.131   
Number of groups:  judge 9 
    . . .
> e.ba = emmeans(m, ~ rating | temp, mode = "prob", bias.adj = TRUE, sigma = 1.131)
> e.ba
temp = cold:
 rating    prob      SE  df asymp.LCL asymp.UCL
 1      0.13599 0.06662 Inf   0.00542    0.2666
 2      0.46613 0.07962 Inf   0.31008    0.6222
 3      0.32405 0.06567 Inf   0.19535    0.4528
 4      0.06067 0.03433 Inf  -0.00661    0.1280
 5      0.01315 0.01045 Inf  -0.00733    0.0336

temp = warm:
 rating    prob      SE  df asymp.LCL asymp.UCL
 1      0.00861 0.00742 Inf  -0.00593    0.0231
 2      0.13484 0.05759 Inf   0.02197    0.2477
 3      0.39975 0.07005 Inf   0.26245    0.5371
 4      0.27379 0.07127 Inf   0.13410    0.4135
 5      0.18301 0.07206 Inf   0.04177    0.3243

Results are averaged over the levels of: contact 
Confidence level used: 0.95 
```
So with the bias adjustment, the negative excursions are not as bad (but no absent). I think these EMMs are more comparable to what you'd get by fitting a `clm` model without the random effect for `judge` -- but the SEs take into account the variation in judges.

We can do the log trick here, too:
```r
> summary(regrid(e.ba, "log"), type = "response")
temp = cold:
 rating response      SE  df asymp.LCL asymp.UCL
 1       0.13599 0.06662 Inf   0.05206    0.3552
 2       0.46613 0.07962 Inf   0.33351    0.6515
 3       0.32405 0.06567 Inf   0.21783    0.4821
 4       0.06067 0.03433 Inf   0.02002    0.1839
 5       0.01315 0.01045 Inf   0.00277    0.0624

temp = warm:
 rating response      SE  df asymp.LCL asymp.UCL
 1       0.00861 0.00742 Inf   0.00159    0.0466
 2       0.13484 0.05759 Inf   0.05838    0.3114
 3       0.39975 0.07005 Inf   0.28354    0.5636
 4       0.27379 0.07127 Inf   0.16437    0.4560
 5       0.18301 0.07206 Inf   0.08459    0.3960

Results are averaged over the levels of: contact 
Confidence level used: 0.95 
Intervals are back-transformed from the log scale
```

### Notes

  * The bias-adjusted estimates are *not* available from the latest CRAN version. That's because I had to revise the code for ordinal models so that the `bnias.adj` and `sigma` areguments are pushed through. Shortly, I will push a revised version that will have those changes.
  * In this particular example, the `prob` values are obtained in a multi-step process: obtain the linear predictions, back-transform them into cumulative probabilities, then contrast them to obtain `rating` probabilities. The bias-adjustment part comes at the first back-transformation step. It is inappropriate to apply the bias-adjustment idea anywhere later on, such as in the regridding to log and back.

**Comment by rvlenth** [comment]
Yet more additions to the package inspired by this... Previously `regrid()` only supported faking a log transform. Now it can fake any transform in `make.link()`. In this case, the probit transformation is a more appropriate one to fake than the log:
```r
> summary(regrid(e, "probit"), type = "response")
temp = cold:
 rating response      SE  df asymp.LCL asymp.UCL
 1       0.09761 0.05626 Inf   0.02651    0.2560
 2       0.52233 0.09102 Inf   0.34757    0.6928
 3       0.33106 0.08617 Inf   0.18333    0.5115
 4       0.04088 0.02550 Inf   0.01043    0.1209
 5       0.00814 0.00656 Inf   0.00144    0.0340

temp = warm:
 rating response      SE  df asymp.LCL asymp.UCL
 1       0.00530 0.00461 Inf   0.00082    0.0249
 2       0.09866 0.05073 Inf   0.03134    0.2367
 3       0.44653 0.08363 Inf   0.29150    0.6103
 4       0.30982 0.08237 Inf   0.17003    0.4846
 5       0.13969 0.06838 Inf   0.04602    0.3161

Results are averaged over the levels of: contact 
Confidence level used: 0.95 
Intervals are back-transformed from the probit scale
```
Again, we have the same point estimates and SEs as in the original question, but the CIs are closer to the original ones but still bounded above zero.

Second, I realized that when I make the fix for bias adjustment, that allows other arguments to be passed to regrid at the right time, and that includes the one that allows a fake posterior sample to be generated. So this goes along with an earlier response about using a Bayesian model:
```r
> emmeans(m, ~ rating | temp, mode = "prob", N.sim = 1000)
Generating a posterior sample of size 1000
temp = cold:
 rating    prob lower.HPD upper.HPD
 1      0.09949  0.019840    0.2265
 2      0.50762  0.335845    0.6743
 3      0.32049  0.181639    0.4988
 4      0.04094  0.006443    0.1108
 5      0.00824  0.000992    0.0303

temp = warm:
 rating    prob lower.HPD upper.HPD
 1      0.00571  0.000278    0.0229
 2      0.10027  0.024450    0.2142
 3      0.42608  0.267149    0.5838
 4      0.30019  0.144083    0.4627
 5      0.13949  0.033366    0.3018

Point estimate displayed: median 
HPD interval probability: 0.95
```
