### ISSUE TITLE
Degrees of freedom for interactions in factorial designs

### ISSUE THREAD

**Issue by EBlini** [rvlenth/emmeans#159]
Hi!
First of all, thank you very much for your work in creating this super useful package!

I do apologize if the question is very naive, but I was hoping to understand a bit better what it's happening under the hoods in emmeans.

I have a 3x3x2 fully within design, 42 subjects. The three-way interaction is significant (unlike the reproducible example I'm about to post:

`
library("emmeans")
library("afex")

set.seed(1)

DF= expand.grid(A= factor(c("A1", "A2", "A3")),
                B= factor(c("B1", "B2", "B3")),
                C= factor(c("C1", "C2")),
                ID= factor(1:42),
                DV= 0)
DF$DV= rnorm(nrow(DF), mean= 0, sd= 1)

model= aov_ez(id= "ID", dv= "DV", 
              data= DF, 
              within= c("A", "B", "C"))

joint_tests(model, by= "B")

emmeans(model, pairwise ~ A:C | B, 
        interaction= T)
`

My question is about the last line of code, in which I ask emmeans to perform pairwise contrasts by the factor "B" and assess the mutual interactions of factors A and C. 
In my understanding this is a comparison of differences (e.g. deltas, C1 minus C2) from each pairwise combination of the levels of A (e.g. A1 vs A2), and separately for each level of B. 
I'm pretty sure this is what I want, but I can't really understand how degrees of freedom are calculated. I get df= 245 in the previous example, whereas I would expect something around 41...

I'm guessing marginal means are not equal to t.tests on actual data, for example: 

`
DF2= DF[DF$B== "B1",]

A1dC= DF2$DV[DF2$A== "A1" & DF2$C== "C1"] - DF2$DV[DF2$A== "A1" & DF2$C== "C2"] 
A2dC= DF2$DV[DF2$A== "A2" & DF2$C== "C1"] - DF2$DV[DF2$A== "A2" & DF2$C== "C2"] 

t.test(A1dC, A2dC, paired= T)

`

Is it something related to conditioning coefficients to all other parameters in the model?

Any ideas on what I may be missing would be greatly appreciated!

Best regards,
Elvio

(package versions: emmeans_1.4.2   afex_0.25-1)

**Comment by rvlenth** [comment]
As I understand it, the `aov_ez` function actually produces two analyses; and the one used by default in `emmeans` support is the "univariate" analysis produced by the `aov` function in R. In that analysis, error SDs are *pooled* because the error variances are assumed to be homogeneous. That leads to more d.f.

An alternative offered by the `afex_aov` support is to use the multivariate model instead:
```r
> (emm = emmeans(model, ~ A:C | B, model = "multivariate"))
B = B1:
 A  C    emmean    SE df lower.CL upper.CL
 A1 C1 -0.11294 0.146 41 -0.40761   0.1817
 A2 C1  0.26625 0.135 41 -0.00723   0.5397
 A3 C1 -0.21679 0.173 41 -0.56664   0.1331
 A1 C2 -0.05227 0.149 41 -0.35285   0.2483
 A2 C2 -0.05725 0.136 41 -0.33159   0.2171
 A3 C2  0.04222 0.144 41 -0.24876   0.3332

B = B2:
 A  C    emmean    SE df lower.CL upper.CL
 A1 C1  0.01988 0.170 41 -0.32348   0.3632
 A2 C1  0.02289 0.173 41 -0.32654   0.3723
 A3 C1 -0.09674 0.151 41 -0.40154   0.2081
 A1 C2 -0.03983 0.165 41 -0.37297   0.2933
 A2 C2 -0.23112 0.148 41 -0.53043   0.0682
 A3 C2 -0.01764 0.146 41 -0.31329   0.2780

B = B3:
 A  C    emmean    SE df lower.CL upper.CL
 A1 C1  0.09186 0.172 41 -0.25636   0.4401
 A2 C1 -0.03232 0.172 41 -0.37954   0.3149
 A3 C1 -0.05185 0.177 41 -0.40899   0.3053
 A1 C2  0.00460 0.168 41 -0.33551   0.3447
 A2 C2  0.00456 0.166 41 -0.33107   0.3402
 A3 C2  0.03816 0.170 41 -0.30509   0.3814

Confidence level used: 0.95 
> contrast(emm, interaction = "pairwise")
B = B1:
 A_pairwise C_pairwise estimate    SE df t.ratio p.value
 A1 - A2    C1 - C2     -0.3842 0.306 41 -1.255  0.2166 
 A1 - A3    C1 - C2      0.1983 0.310 41  0.640  0.5256 
 A2 - A3    C1 - C2      0.5825 0.291 41  2.005  0.0516 

B = B2:
 A_pairwise C_pairwise estimate    SE df t.ratio p.value
 A1 - A2    C1 - C2     -0.1943 0.267 41 -0.728  0.4708 
 A1 - A3    C1 - C2      0.1388 0.353 41  0.393  0.6962 
 A2 - A3    C1 - C2      0.3331 0.312 41  1.066  0.2925 

B = B3:
 A_pairwise C_pairwise estimate    SE df t.ratio p.value
 A1 - A2    C1 - C2      0.1241 0.315 41  0.394  0.6956 
 A1 - A3    C1 - C2      0.1773 0.338 41  0.525  0.6026 
 A2 - A3    C1 - C2      0.0531 0.321 41  0.165  0.8695 
```
That analysis is closer to the one you did with the t tests; in both the paired t tests on subsets of the data and the multivariate analysis, errors are not pooled, and the d.f. for error is 41.

[For technical reasons, adding `model = "multivariate"` to `emmeans(..., pairwise ~ ...)` does not work, because `model` gets passed to `contrast`, where it gets confused with some other specs. I will consider whether there is a workaround, but in general I highly recommend doing the emmeans and any contrasts thereof in *separate* steps; they are two analyses, and it is cleaner to keep them separate. ]

For more details on the support for these models, see `? "afex_aov-methods"`

I'm closing this issue because I think I answered the question, but feel free to comment if anything is not clear.

**Comment by rvlenth** [comment]
I did make a small change. Now, `emmeans(model, pairwise ~ A:C | B, model = "multivariate")` will work without error.

**Comment by EBlini** [comment]
Yes, this was super clear and useful, thanks!
