### ISSUE TITLE
as.stanfit

### ISSUE THREAD

**Issue by felixthoemmes** [rvlenth/emmeans#16]
Hello,
I noticed that emmeans has retired the as.stanfit command, and is now exclusively using as.mcmc when using emmeans for Bayesian models, like the ones generated from the rstanarm package. 
Just as a personal opinion, I liked the as.stanfit() command, because it allowed me to generate interest contrasts, etc. using emmeans, but getting output that looked very similar to the stan output, and not like the mcmc output. In particular, this meant that the credible intervals appear next to the estimates, and the Gelman-Rubin convergence criteria are printed alongside the estimates. 
It's not a huge deal, and I still appreciate that emmeans is so flexible to utilize all these different fitted methods, but it was nice having as.stanfit().

**Comment by rvlenth** [comment]
Thanks for the comment. From the start, `as.stanfit` was something of a hack; and it started creating problems. And I realized that really, th plot methods for `stanfit` objects were really from **bayesplot**, which supports `mcmc` and `mcmc.list` objects. So that's why I deprecated it. I hear you on the summary you'd have liked. I wonder if you could implore the **stanreg/stanfit** developers to provide an `as.stanfit` method for `mcmc`/`mcmc.list` objects.

**Comment by felixthoemmes** [comment]
Good point - I will go ahead and contact the stanfit team, and see what they have to say. As always, thanks for your work on emmeans, and the quick reply!

**Comment by rvlenth** [comment]
Going ahead and closing now, as I think this is resolved.
