### ISSUE TITLE
pairwise contrasts: estimate vs odds.ratio

### ISSUE THREAD

**Issue by dendrologicus** [rvlenth/emmeans#168]
Hi

I want to post-hoc test differences in plant survival between four soil treatments. First, I do the following:
```
MYEMM <- emmeans(MYMODEL, c("soil"))
pairs(MYEMM) 
contrast estimate      SE  df z.ratio p.value
 F - H      -0.567   0.301 Inf -1.879  0.2369 
 F - L      -7.803 790.432 Inf -0.010  1.0000 
 F - W      -2.615 456.356 Inf -0.006  1.0000 
 H - L      -7.236 790.432 Inf -0.009  1.0000 
 H - W      -2.049 456.356 Inf -0.004  1.0000 
 L - W       5.187 912.712 Inf  0.006  1.0000
```
Second, I try this:
```
pairs(MYEMM, type="response")         # <-  :)
 contrast odds.ratio       SE  df z.ratio p.value
 F / H      5.67e-01 1.70e-01 Inf -1.879  0.2369 
 F / L      4.10e-04 3.20e-01 Inf -0.010  1.0000 
 F / W      7.31e-02 3.34e+01 Inf -0.006  1.0000 
 H / L      7.20e-04 5.70e-01 Inf -0.009  1.0000 
 H / W      1.29e-01 5.88e+01 Inf -0.004  1.0000 
 L / W      1.79e+02 1.63e+05 Inf  0.006  1.0000 
```

I am confused: It seems to me that the first command ```pairs(MYEMM)``` is giving me the odds.ratios of the pairwise comparisons - they also make sense with my original data - however they are called  ```estimate```. With  ```pairs(MYEMM, type="response")``` I get ```odds.ratio```, but the numbers do not make sense to me... What are they?

It is probably me not 100% grasping the concept of odds.ratios, and not really a emmans issue. But maybe you could clarify. Thank you very much for your great work!
Lukas

**Comment by rvlenth** [comment]
No ---  `pairs(MYEMM)` gives the *log* odds ratios, and `pairs(MYEMM, type="response")` gives the odds ratios themselves. For example, for H versus W, the estimated log odds ratio is -2.049 and the odds ratio itself is exp(-2.049) = 0.1289, as is shown in the second output.

Odds are always positive numbers, because they are quantities of the form *p/(1-p)*. For example if *p1=0.75* and *p2=1/3$, then the odds are 0.75/0.25 = 3.0 and (1/3)/(2/3) = 0.5 respectively, and the odds ratio is 3.0/0.5 = 6.0. The log odds are log(3) and log(0.5), and the log odds ratio is log(6) which is equal to log(3/0.5) = log(3) - log(0.5).

**Comment by robertour** [comment]
Does this still work? I get the estimate for both cases: `pairs(the_means, type="response")` and `pairs(the_means)`. The column name is `estimate`, and the values are also the same.

I am using an lmer model (`y ~ a*b*c + 1|s`), and my emmeans looks as follows: `emmeans(y,  ~ a|(b:c), lmer.df = "asymptotic")`. The reason for using asymptotic is because  "kenward-roger" or "satterthwaite" are computationally to expensive.

Is there another way to calculate the odds ratio?

**Comment by rvlenth** [comment]
I'm confused. If you're using `lmer`, you're not fitting a logit model so I don't see how odds ratios even make sense. Moreover, I do not see evidence of a response transformation either, so `type = "response"` will not make any difference.

If you're using `glmer` with a logit link, then odds ratios etc. would make sense in that case.

**Comment by robertour** [comment]
Thanks!, you are absolutely right! neither I am dealing with binomial responses, nor I am transforming anything on my model. Sorry about that, I just got confused, and assumed a similar situation to the question.
