### ISSUE TITLE
Nested models not working

### ISSUE THREAD

**Issue by p-schaefer** [rvlenth/emmeans#169]
This may or may not be related to other issues concerning nesting. I have a particularly complicated nested study design that looks like this:

`tst<-data.frame(val=rnorm(45),
                CI=factor(c(rep("C",15),rep("I",30))),
                Year=factor(rep(rep(1:3,each=5),3)),
                Area=factor(rep(c("A","B","C"),each=15))
)`

`fit<-lm(val ~ CI + Year + CI/Area + CI*Year + CI/(Area*Year), data=tst )`

Unfortunately, in my actual results the CI*Year term is significant, and I want to pull out pariwise contrasts between CI over time. So I use:

`emmeans(fit,~CI|Year)`

which just results in:
`Results are averaged over the levels of: Area `
`Confidence level used: 0.95`

and no additional tables or anything.

I am using emmeans version 1.4.3.1090007

EDIT: I just noticed that 
`data.frame(emmeans(fit,~CI|Year))`
does actually give me a result, but in my actual dataset, I have missing data, such that:

`tst$val[tst$Area=="B" & tst$Year=="2"]<-NA`
`fit2<-lm(val ~ CI + Year + CI/Area + CI*Year + CI/(Area*Year), data=tst )`
and now, emmeans doesnt work:
`emmeans(fit2,~CI|Year)`

`Error in sum(sapply(by.rows, length)) : invalid 'type' (list) of argument`

**Comment by rvlenth** [comment]
But, at least in terms of the model you actually fitted, Year is nested in CI, not the other way around. So you can't condition comparisons of CI on each year.
```
> emmeans(fit,~Year|CI)
NOTE: A nesting structure was detected in the fitted model:
    Area %in% CI, Year %in% CI
NOTE: Results may be misleading due to involvement in interactions
CI = C:
 Year  emmean    SE df lower.CL upper.CL
 1     0.5015 0.417 36   -0.345    1.348
 2    -0.1898 0.417 36   -1.036    0.657
 3     0.0353 0.417 36   -0.811    0.882

CI = I:
 Year  emmean    SE df lower.CL upper.CL
 1     0.1485 0.295 36   -0.450    0.747
 2     0.6247 0.295 36    0.026    1.223
 3     0.0539 0.295 36   -0.545    0.653

Results are averaged over the levels of: Area 
Confidence level used: 0.95 
```

**Comment by rvlenth** [comment]
Looking at how you use `*` in your model, I wonder if you correctly understand R's model notation vis-a-vis SAS's. If the SAS model is
```
RESP = A|B + C*D + S(A)
```
then the corresponding R model is
```
RESP ~ A*B + C:D + A/S
```
or the last term could be written `A %in% S` or `A:S`

**Comment by rvlenth** [comment]
Also, you can manually specify the nesting structure:
```
> emmeans(fit,~CI|Year, nesting="CI %in% (Area*Year)")
Year = 1:
 CI Area  emmean    SE df lower.CL upper.CL
 C  A     0.5015 0.417 36  -0.3451    1.348
 I  B     0.0868 0.417 36  -0.7599    0.933
 I  C     0.2102 0.417 36  -0.6364    1.057

Year = 2:
 CI Area  emmean    SE df lower.CL upper.CL
 C  A    -0.1898 0.417 36  -1.0365    0.657
 I  B     0.4344 0.417 36  -0.4123    1.281
 I  C     0.8151 0.417 36  -0.0316    1.662

Year = 3:
 CI Area  emmean    SE df lower.CL upper.CL
 C  A     0.0353 0.417 36  -0.8114    0.882
 I  B     0.3055 0.417 36  -0.5412    1.152
 I  C    -0.1977 0.417 36  -1.0444    0.649

Confidence level used: 0.95
```

**Comment by rvlenth** [comment]
What I discovered is that the specs in  the model conflict with the structure of the data.
```
> with(tst, table(CI, Area, Year))
, , Year = 1

   Area
CI  A B C
  C 5 0 0
  I 0 5 5

, , Year = 2

   Area
CI  A B C
  C 5 0 0
  I 0 5 5

, , Year = 3

   Area
CI  A B C
  C 5 0 0
  I 0 5 5
```
This clearly shows that Area is nested in CI alone. If we just fit a model with all the interactions and let `emmeans()` figure out the nesting...
```
> fit4 = lm(val~CI*Area*Year, data=tst)

> emmeans(fit4, ~ CI | Year)
NOTE: A nesting structure was detected in the fitted model:
    Area %in% CI
NOTE: Results may be misleading due to involvement in interactions

Year = 1:
 CI  emmean    SE df lower.CL upper.CL
 C   0.5015 0.417 36   -0.345    1.348
 I   0.1485 0.295 36   -0.450    0.747

Year = 2:
 CI  emmean    SE df lower.CL upper.CL
 C  -0.1898 0.417 36   -1.036    0.657
 I   0.6247 0.295 36    0.026    1.223

Year = 3:
 CI  emmean    SE df lower.CL upper.CL
 C   0.0353 0.417 36   -0.811    0.882
 I   0.0539 0.295 36   -0.545    0.653

Results are averaged over the levels of: Area 
Confidence level used: 0.95 
```

**Comment by p-schaefer** [comment]
Yes, you may be correct. The model may have been specified incorrectly. I think this is closer to what I want:

`> fit3<-lm(val ~ CI + Year + CI/Area + CI:Year + (CI/Area):Year, data=tst )`
`> emmeans(fit3, ~ CI | Year)`
`NOTE: A nesting structure was detected in the fitted model:
    Area %in% CI, Year %in% CI
NOTE: Results may be misleading due to involvement in interactions
Error in sum(sapply(by.rows, length)) : invalid 'type' (list) of argument`

But this gives me that emmeans error again. I dont see a Year %in% CI term in this model, but emmeans says there is one.

**Comment by rvlenth** [comment]
There is always the option of overriding the auto-detected nesting, as is documented:
```
> emmeans(fit3, ~ CI | Year, nesting = "Area %in% CI")
NOTE: Results may be misleading due to involvement in interactions
Year = 1:
 CI  emmean    SE df lower.CL upper.CL
 C   0.5015 0.417 36   -0.345    1.348
 I   0.1485 0.295 36   -0.450    0.747

Year = 2:
 CI  emmean    SE df lower.CL upper.CL
 C  -0.1898 0.417 36   -1.036    0.657
 I   0.6247 0.295 36    0.026    1.223

Year = 3:
 CI  emmean    SE df lower.CL upper.CL
 C   0.0353 0.417 36   -0.811    0.882
 I   0.0539 0.295 36   -0.545    0.653

Results are averaged over the levels of: Area 
Confidence level used: 0.95
```
The nesting is auto-detected by looking at two things: the structure of the data and the model. The first part of it is enough in this example; you can just omit all the explicit nesting in the model and use the structure of the data...
```
> fit3a <- lm(val ~ CI + Year + Area + CI:Year + Area:Year, data = tst)
> emmeans(fit3a, ~ CI | Year)
NOTE: A nesting structure was detected in the fitted model:
    Area %in% CI
Year = 1:
 CI  emmean    SE df lower.CL upper.CL
 C   0.5015 0.417 36   -0.345    1.348
 I   0.1485 0.295 36   -0.450    0.747

Year = 2:
 CI  emmean    SE df lower.CL upper.CL
 C  -0.1898 0.417 36   -1.036    0.657
 I   0.6247 0.295 36    0.026    1.223

Year = 3:
 CI  emmean    SE df lower.CL upper.CL
 C   0.0353 0.417 36   -0.811    0.882
 I   0.0539 0.295 36   -0.545    0.653

Results are averaged over the levels of: Area 
Confidence level used: 0.95 
```
The nesting was correctly detected solely based on the structure of the data.

As for the formula, the formula in `fit3` simplifies to:
```
> update(formula(fit3), .~.)
val ~ CI + Year + CI:Area + CI:Year + CI:Year:Area
```
We can see that Area is nested in `CI` because there is a `CI:Area` term but no `Area` term. There is also a `CI:Year:Area` term but no `Year:Area` term, so the algorithm deems that `Year:Area` is nested in `CI`, and hence that both `Year` and `Area` are nested in `CI`. That is the underlying logic, even though I can see that it leads to the wrong result. I will ponder this, I do have a disclaimer of sorts in the help page for `ref_grid`:

> Nested factors. Having a nesting structure affects marginal averaging in emmeans in that it is done separately for each level (or combination thereof) of the grouping factors. `ref_grid` tries to discern which factors are nested in other factors, but it is not always obvious, and if it misses some, the user must specify this structure via nesting; or later using update.emmGrid.

So I agree that there is something wrong in the auto-detection of nesting. At the very least, I could change the phrasing to say it's not only possible to miss something, it is possible to get an artifact. But I need to think harder about whether I can figure out how I should know that `Year` is not nested in `CI`. (Offhand, it looks like there's a missing step where I fail to note that `Year` has a main effect term.)

**Comment by rvlenth** [comment]
I think I've got it now. It even works with your original model:
```
> emmeans(fit, ~ CI|Year)
NOTE: A nesting structure was detected in the fitted model:
    Area %in% CI
NOTE: Results may be misleading due to involvement in interactions
Year = 1:
 CI  emmean    SE df lower.CL upper.CL
 C   0.5015 0.417 36   -0.345    1.348
 I   0.1485 0.295 36   -0.450    0.747

Year = 2:
 CI  emmean    SE df lower.CL upper.CL
 C  -0.1898 0.417 36   -1.036    0.657
 I   0.6247 0.295 36    0.026    1.223

Year = 3:
 CI  emmean    SE df lower.CL upper.CL
 C   0.0353 0.417 36   -0.811    0.882
 I   0.0539 0.295 36   -0.545    0.653

Results are averaged over the levels of: Area 
Confidence level used: 0.95 
```
Than ks for bringing this to my attention. The update will be available here when I next push it up, and later with the next CRAN update

**Comment by p-schaefer** [comment]
That is very helpful thank you so much!

One final question:
With the missing data at Area B in Year 2, shouldn't we still be able to get an emmean for Year=2 CI=I from the other area? 

```
> tst<-data.frame(val=rnorm(45), 
  CI=factor(c(rep("C",15),rep("I",30))), 
  Year=factor(rep(rep(1:3,each=5),3)), 
  Area=factor(rep(c("A","B","C"),each=15))
 )
> tst$val[tst$Area=="B" & tst$Year=="2"]<-NA

> fit3<-lm(val ~ CI + Year + CI/Area + CI:Year + (CI/Area):Year, data=tst )

> emmeans(fit3, ~ CI | Year, nesting = "Area %in% CI")

Year = 1:
 CI  emmean    SE df lower.CL upper.CL
 C  -0.3167 0.408 32   -1.148    0.514
 I   0.2480 0.288 32   -0.340    0.836

Year = 2:
 CI  emmean    SE df lower.CL upper.CL
 C  -0.0906 0.408 32   -0.922    0.740
 I   nonEst    NA NA       NA       NA

Year = 3:
 CI  emmean    SE df lower.CL upper.CL
 C   0.0307 0.408 32   -0.800    0.862
 I  -0.3752 0.288 32   -0.963    0.212

Results are averaged over the levels of: Area 
Confidence level used: 0.95 
```

**Comment by rvlenth** [comment]
No, because it averages over the areas. If you add weights = “flat” it will, but we’re really not getting true marginal means then.

Russ

Sent from my iPhone

On Jan 16, 2020, at 2:16 PM, p-schaefer <notifications@github.com<mailto:notifications@github.com>> wrote:


That is very helpful thank you so much!

One final question:
With the missing data at Area B in Year 2, shouldn't we still be able to get an emmean for Year=2 CI=I from the other area?

> tst<-data.frame(val=rnorm(45),
  CI=factor(c(rep("C",15),rep("I",30))),
  Year=factor(rep(rep(1:3,each=5),3)),
  Area=factor(rep(c("A","B","C"),each=15))
 )
> tst$val[tst$Area=="B" & tst$Year=="2"]<-NA

> fit3<-lm(val ~ CI + Year + CI/Area + CI:Year + (CI/Area):Year, data=tst )

> emmeans(fit3, ~ CI | Year, nesting = "Area %in% CI")

Year = 1:
 CI  emmean    SE df lower.CL upper.CL
 C  -0.3167 0.408 32   -1.148    0.514
 I   0.2480 0.288 32   -0.340    0.836

Year = 2:
 CI  emmean    SE df lower.CL upper.CL
 C  -0.0906 0.408 32   -0.922    0.740
 I   nonEst    NA NA       NA       NA

Year = 3:
 CI  emmean    SE df lower.CL upper.CL
 C   0.0307 0.408 32   -0.800    0.862
 I  -0.3752 0.288 32   -0.963    0.212

Results are averaged over the levels of: Area
Confidence level used: 0.95

**Comment by p-schaefer** [comment]
Okay thanks
