### ISSUE TITLE
cov.reduce maximum and minimum of overlapping range

### ISSUE THREAD

**Issue by p-schaefer** [rvlenth/emmeans#182]
Is there an easy way to use `cov.reduce` to calculate contrasts at the maximum and minimum of _overlapping_ values between groups? `cov.reduce = range` will give the full range of the covariate in the dataset, but I cant seem to figure out a function or even how to feed it specific values to test at. Thanks.

**Comment by rvlenth** [comment]
If I correctly understand what you mean by "overlapping", it's possible, but not easy, because you need to piece it together. Here's an example:

```r
> fiber.lm <- lm(strength ~ diameter * machine, data = fiber)

> rng = with(fiber, tapply(diameter, machine, range))
> rg1 = ref_grid(fiber.lm, at = list(machine = "A", diameter = rng[[1]]))
> rg2 = ref_grid(fiber.lm, at = list(machine = "B", diameter = rng[[2]]))
> rg3 = ref_grid(fiber.lm, at = list(machine = "C", diameter = rng[[3]]))
> rg = rg1 + rg2 + rg3

> summary(rg)
 diameter machine prediction   SE df
 20       A             35.7 1.26  9
 32       A             48.9 1.52  9
 22       B             39.8 1.17  9
 30       B             46.6 1.17  9
 15       C             30.6 1.49  9
 26       C             40.1 1.25  9
```
As you can see, we do get a different range of diameters for each machine. But this can create problems later:
```r
> emmeans(rg, "machine")
Error in emmeans(rg, "machine") : 
  Irregular reference grid: Marginal means cannot be determined
```
This particular issue can be fixed -- noting that we really have a nesting structure now:
```r
> rg = update(rg, nesting = "diameter %in% machine")
> emmeans(rg, "machine")
NOTE: Results may be misleading due to involvement in interactions
 machine emmean    SE df lower.CL upper.CL
 A         42.3 0.765  9     40.6     44.0
 B         43.2 0.749  9     41.5     44.9
 C         35.4 0.763  9     33.7     37.1

Results are averaged over the levels of: diameter 
Confidence level used: 0.95 
```

Oh -- I suppose that by "overlapping" you mean the largest minimum to the smallest maximum, this is doable with a side calculation:
```
> ovlp = c(max(sapply(rng, min)), min(sapply(rng, max)))
> rg2 = ref_grid(fiber.lm, at = list(diameter = ovlp))
> summary(rg2)
 diameter machine prediction    SE df
       22 A             37.9 0.972  9
       26 A             42.3 0.765  9
       22 B             39.8 1.167  9
       26 B             43.2 0.749  9
       22 C             36.7 0.767  9
       26 C             40.1 1.248  9
```
This will be a nicely behaved `emmGrid` object.

**Comment by rvlenth** [comment]
PS -- It really isn't possible to provide for this via a `cov.reduce` function, because such a function  is a function of the covariate alone, no other variables. You could write a custom function that has built-in the indexes of each group level, but the technique above of doing it on the side and then using `at` is less tedious and less error-prone.

**Comment by p-schaefer** [comment]
Perfect. The `at` solution is exactly what I was looking for. Thanks!
