### ISSUE TITLE
Which effect size measure does eff-size compute?

### ISSUE THREAD

**Issue by abrowman** [rvlenth/emmeans#190]
I was wondering which effect size measure the eff-size function computes (e.g., Cohen's d, Hedges' g, partial eta-squared, etc.). Or does it vary based on the type of test used with emmeans()? For example, what effect size measure would eff-size compute for aov()?

**Comment by rvlenth** [comment]
Pairwise differences, divided by the value of sigma you supply. I think for some models, that could be Cohen's d if you give it the right sigma. I tried very hard to avoid putting in any defaults, because I want the user to be completely responsible for its inputs.

Russ

Sent from my iPhone

On May 1, 2020, at 4:22 PM, Alex Browman <notifications@github.com<mailto:notifications@github.com>> wrote:


I was wondering which effect size measure the eff-size function computes (e.g., Cohen's d, Hedges' g, partial eta-squared, etc.). Or does it vary based on the type of test used with emmeans()? For example, what effect size measure would eff-size compute for aov()?

**Comment by abrowman** [comment]
Understood, thank you!
