### ISSUE TITLE
Error in recover_data when using trms arguments and NAs

### ISSUE THREAD

**Issue by singmann** [rvlenth/emmeans#191]
It seems that at least with the current version, `recover_data` fails when using the `trms` argument and there are `NA`s in the data:

```r
library("emmeans")
warpbreaks[1, "breaks"] <- NA
warp.lm <- lm(breaks ~ wool * tension, data = warpbreaks)
recover_data(warp.lm, trms = terms(warp.lm))
## Error in tbl[, vars, drop = FALSE] : incorrect number of dimensions
```

Works without `trms` though:
```r
> recover_data(warp.lm)
   wool tension
2     A       L
3     A       L
4     A       L
```

For reference: 
```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] emmeans_1.4.6

loaded via a namespace (and not attached):
 [1] lattice_0.20-41  codetools_0.2-16 mvtnorm_1.1-0    zoo_1.8-7        MASS_7.3-51.6   
 [6] grid_4.0.0       xtable_1.8-4     coda_0.19-3      estimability_1.3 multcomp_1.4-13 
[11] Matrix_1.2-18    sandwich_2.5-1   splines_4.0.0    TH.data_1.0-10   tools_4.0.0     
[16] survival_3.1-12  compiler_4.0.0  
```

**Comment by rvlenth** [comment]
Well, the short answer is that `trms` isn't meant to be a user-supplied argument. Notice:
```r
> emmeans:::recover_data.lm
function(object, ...) {
    fcall = object$call
    recover_data(fcall, delete.response(terms(object)), object$na.action, ...)
}
<bytecode: 0x0000012d16b86b20>
<environment: namespace:emmeans>
```
versus:
```r
> args(emmeans:::recover_data.call)
function (object, trms, na.action, data = NULL, params = "pi", ...) 
```
So if you run `recover_data.lm()` and supply a `trms` argument, then `trms` is part of `...` that gets passed to `recover_data.call()`; so `trms` is matched with the `trms` you supplied, but the other arguments of `recover_data.call()` are positionally matched to the wrong things. For example, `data` gets matched to `object$na.action` which in this case is `c(1)`. It goes downhill from there.

Perhaps it would have been better to have written `recover_data.lm()` so that it calls `recover_data.call()` with named arguments, but in this example that would have caused a different error: having two `trms` arguments in the call to `recover_data.call()`.

Generally, the design of these methods is that the only arguments the user should provide are `data` and model-specific ones. In particular with `trms`, it really is something that the model-specific method should provide.

Henrik, may I ask what it is you are trying to accomplish by providing `trms`? If it is to implement a `recover_data()` method for some model class, I suggest routing to `recover_data.call()` instead of a model-based method.

**Comment by singmann** [comment]
As you rightly assume, I do not actually use this in a `lm` call, but could boil it down to that. I encountered the issue actually when using `recover_data` to recover the full data set used for fitting. I do this in the `afex_plot.merMod()` method here (so the same problem holds for the `recover_data.merMod` method): 
https://github.com/singmann/afex/blob/master/R/afex_plot.R#L563

To me using the `trms` argument seemed to be the easiest method to get all the data of a fitted model, including the response variable. I could probably use a different approach, but it has worked so far.

Also, I do not seem to be able to directly call any specific `recover_data` method. Only the generic is exported, but none of the specific methods. And even then, I seem to be unable to pass `merMod` objects directly to `recover_data.call()` (`object of type 'S4' is not subsettable`).

**Comment by rvlenth** [comment]
"... including the response variable. ... It has worked so far"? I don't think so. Almost all `recover_data()` methods call `delete.response()` on the `trms` argument, including the `lm` method shown above. So it won't work for recovering the response variable, unless you add the response to the right-hand size of the model formula.

Note that there is also a `.recover_data()` function (with a leading `.` in its name) that is exported. I believe I provided that at your request sometime in the past. Because it runs in **emmeans**'s namespace, it gives access to all the `recover_data()` methods, including the one for `call`. See `? recover_data`.
```r
> .recover_data(warp.lm$call, trms = terms(warp.lm), na.action = warp.lm$na.action)
   breaks wool tension
2      30    A       L
3      54    A       L
4      25    A       L
5      70    A       L
...
```

Hope that helps.

**Comment by rvlenth** [comment]
PS -- I knew I had seen a relatively new function that may prove useful: `get_all_vars` -- check its help page (combined with `model.frame()`). It "returns a data.frame containing the variables used in formula plus those specified in ... which are recycled to the number of data frame rows. Unlike model.frame.default, it returns the input variables and not those resulting from function calls in formula."

**Comment by rvlenth** [comment]
Henrik,

Looking at this again, I see no purpose in that `.recover_data()` function, as the other one works just fine. Here's a parallel example showing what works for a `merMod` object:
```r
> Oats = nlme::Oats
> Oats$yield[1] = NA
> Oats.lmer = lmer(yield ~ Variety + factor(nitro) + (1|Block/Variety), data = Oats)
> recover_data(Oats.lmer@call, terms(Oats.lmer), na.action = attr(Oats.lmer@frame, ".na.action"))
   yield     Variety nitro
2    130     Victory   0.2
3    157     Victory   0.4
4    174     Victory   0.6
5    117 Golden Rain   0.0
...
```
For S4 objects, slots are extracted using `@` rather than `$`.

**Comment by singmann** [comment]
Thanks, the last code really solved it for `merMod` objects. I had not realized I could pass the `@call` slot to access the `recover_data.call()` method.

And this discussion reminded me that `model.frame` actually recovers the data for many models as well, which I can fall back on.
