### ISSUE TITLE
Unable to run emmeans for ordinal model 

### ISSUE THREAD

**Issue by rpmady** [rvlenth/emmeans#192]
Hello,

I've run a model using the clm() function from the ordinal package successfully. 
My response variable is food_availability with levels None, Inconstant,Constant.
The main predictor of interest is SurveyGroup, coded as a factor with levels 1,2.

Here is the model: 
```
mod<- clm(food_availability~ SurveyGroup + education + gender + PropLifeFeeding + centrality_mean + temp_seasonal,
                       data = subset(econmix2, econmix2$season=="winter"), 
                       nominal = ~ Age + observation, Hess = TRUE)
```
When I run the emmeans function I get an error message.
```
emmeans(mod, ~ SurveyGroup, mode="linear.predictor") 
# Error in if (!all(chk == tbl)) stop("Data appear to be randomized -- ",  : 
#                                       missing value where TRUE/FALSE needed
#                                     Error in ref_grid(object, ...) : 
#                                       Perhaps a 'data' or 'params' argument is needed
```
I can't figure out why and wonder if there is something that is wrong due to the nominal = in the clm() specification.

**Comment by rvlenth** [comment]
This should work:
```r
emmeans(mod, ~ SurveyGroup, mode="linear.predictor",
    data = subset(econmix2, econmix2$season=="winter"))
```
but if it doesn't work, that suggests a problem with the data. I'm not sure why you have that missing-value error.

The error message happens because `emmeans()` tries to reconstruct the dataset from the `clm()` call. When there is a function call somewhere in there (in this case to `subset()`), it runs a check on a few rows of the data to see if we get the same thing twice. I put in that check because I had a surprising number of questions from people using randomization methods and getting bad results because the data were not reproducible.

In future work, I suggest it may be more reliable, in terms of `emmeans()` use, to fit the model using the `subset` argument, rather than a call to the `subset()` function: 
```r
mod = clm(..., data = econmix2, subset = (season == "winter"), ...)
```
Then it won't try to test the data for reproducibility.

**Comment by rpmady** [comment]
Thank you! I should have suspected the subset call was making things funky. I really appreciate, the problem was solved right away.
