### ISSUE TITLE
potential to make emmeans work for vglm package?

### ISSUE THREAD

**Issue by rpmady** [rvlenth/emmeans#193]
I've created models successful in the ordinal package, but have realized that when I need to realize the proportional odds assumption (use the nominal = argument) then p-values are not calculated and I can't get emmeans for those predictors. 

So I've thought of using the vglm package to do that but realized that it is not compatible with emmeans. Is there any way to make emmean work with vglm?

**Comment by rvlenth** [comment]
Can you give me a reproducible example of what doesn't work with the ordinal support? I'm getting more and more reluctant to add support for more packages. It just leads to continuing issues when developers of those packages change something.

Russ

Sent from my iPad

On May 7, 2020, at 1:58 PM, Rachael <notifications@github.com> wrote:

﻿

I've created models successful in the ordinal package, but have realized that when I need to realize the proportional odds assumption (use the nominal = argument) then p-values are not calculated and I can't get emmeans for those predictors.

So I've thought of using the vglm package to do that but realized that it is not compatible with emmeans. Is there any way to make emmean work with vglm?

**Comment by rpmady** [comment]
Of course! The dataset is large, so here is a link to it:
https://drive.google.com/file/d/1xQvcZ3iCeH4J4Z3lj-Tz2mxGL-Z9zN-F/view?usp=sharing

The package is _VGAM_ and the reason I'm using it is because when I relax the proportional odds assumption in the _clm()_ function from the _ordinal_ package for predictor variables, I no longer get p-values and I can no longer calculate emmeans for them. I'm also using it instead of the _polr_ package because that package does not allow me to relax the proportional odds assumption.


the vlg() model: 
```
fit <- vglm(perc_avail_cat2 ~ SurveyGroup + education + gender + Age + PropLifeFeeding + observation + centrality_mean + temp_seasonal,
            family=cumulative(parallel=FALSE~Age + observation), data)
```
When I try to use emmeans,
```
emmeans(fit, pairwise ~ perc_avail_cat2 | SurveyGroup, mode="prob" )
Error in ref_grid(object, ...) : Can't handle an object of class  “vglm” 
 Use help("models", package = "emmeans") for information on supported models.

**Comment by rvlenth** [comment]
I need to know what you mean by not being able to get P values with the clm model. What emmeans call did you use and what error messages resulted? If no errors, note that by default you don't get P values unless you perform comparisons or contrasts.

Sent from my iPhone

On May 8, 2020, at 7:23 AM, Rachael <notifications@github.com<mailto:notifications@github.com>> wrote:


Of course! The dataset is large, so here is a link to it:
https://drive.google.com/file/d/1xQvcZ3iCeH4J4Z3lj-Tz2mxGL-Z9zN-F/view?usp=sharing

The package is VGAM and the reason I'm using it is because when I relax the proportional odds assumption in the clm() function from the ordinal package for predictor variables, I no longer get p-values and I can no longer calculate emmeans for them. I'm also using it instead of the polr package because that package does not allow me to relax the proportional odds assumption.

the vlg() model:

fit <- vglm(perc_avail_cat2 ~ SurveyGroup + education + gender + Age + PropLifeFeeding + observation + centrality_mean + temp_seasonal,
            family=cumulative(parallel=FALSE~Age + observation), data)


When I try to use emmeans,

emmeans(fit, pairwise ~ perc_avail_cat2 | SurveyGroup, mode="prob" )
Error in ref_grid(object, ...) : Can't handle an object of class  “vglm”
 Use help("models", package = "emmeans") for information on supported models.

**Comment by rpmady** [comment]
When I run the model using clm() from ordinal, I meant there are no p-values to assess statistical significance in the model output: 
```
Coefficients:
                 Estimate Std. Error z value Pr(>|z|)   
SurveyGroup1     0.276945   0.087216   3.175   0.0015 **
education.L      0.285282   0.223908   1.274   0.2026   
education.Q     -0.096231   0.190566  -0.505   0.6136   
education.C     -0.045151   0.152354  -0.296   0.7670   
education^4     -0.072175   0.149527  -0.483   0.6293   
gender1          0.064005   0.079159   0.809   0.4188   
PropLifeFeeding -0.753351   0.323221  -2.331   0.0198 * 
centrality_mean -0.057066   0.053616  -1.064   0.2872   
temp_seasonal    0.007901   0.005573   1.418   0.1562   
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Threshold coefficients:
                                 Estimate Std. Error z value
None|Constant.(Intercept)        1.113051   0.490808   2.268
Constant|Inconstant.(Intercept)  0.200886   0.364704   0.551
None|Constant.Age               -0.054179   0.008969  -6.041
Constant|Inconstant.Age          0.005185   0.004665   1.112
None|Constant.observation       -0.220968   0.053133  -4.159
Constant|Inconstant.observation  0.036904   0.012788   2.886
```

But something must have changed in R or maybe I had a type because emmeans will now work for Age and observation. 
Still, I wish I could assess statistical significance of the variables in the model itself. 
Think I'll still shift to the multinomial package potentially.

**Comment by rvlenth** [comment]
Hmmmm. Well, there *are* P values in the first table above (regression coefficients), but not in the second. It's possible to compute P values in the second too, using the Z scores: `2*pnorm(-abs(z))`. However, I believe the reason they are not there is because the scale for the thresholds has an arbitrary zero reference point, so it doesn't make sense to test them against a specific value.

I'm just not clear what you are finding inadequate in the **ordinal** package, but obviously you can make your own choices based on your preferences.

**Comment by rpmady** [comment]
@rvlenth, that makes sense.  Thanks for your help! The problem I have is that I need to be able to assess the statistical significance of the relationship between variables that I relax the proportional odds assumption for and the response variable.
