### ISSUE TITLE
Support for rstanarm::stan_gamm4

### ISSUE THREAD

**Issue by DominiqueMakowski** [rvlenth/emmeans#202]
Hi Russell, so sorry to bother you again with GAMs 😁 

I noticed that `stan_gamm4` models appear as not being supported by `emmeans`:

``` r
model <- rstanarm::stan_gamm4(Sepal.Length ~ s(Petal.Length), data=iris, chains=2, iter=200, refresh=0)
emmeans::ref_grid(model)
#> Error in validObject(.Object): invalid class "emmGrid" object: invalid object for slot "V" in class "emmGrid": got class "numeric", should be or extend class "matrix"
```

<sup>Created on 2020-05-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'm not sure to what extent this is related to brms' GAMs (https://github.com/paul-buerkner/brms/issues/907) or not at all. Thanks again for your help!

**Comment by rvlenth** [comment]
It turns out that this is due to the simplicity of your model. If you try a different model, it works fine:
```r
> model2 <- rstanarm::stan_gamm4(Sepal.Length ~ Species + s(Petal.Length), 
+     data=iris, chains=2, iter=200, refresh=0)

> ref_grid(model2)
'emmGrid' object with variables:
    Species = setosa, versicolor, virginica
    Petal.Length = 3.758
```
However, the smoother aspect doesn't work:
```r
> emmip(model2, Species ~ Petal.Length, at = list(Petal.Length =seq(0.5,6,by=.25)))
```
![image](https://user-images.githubusercontent.com/26777519/83059404-77a5b400-a01f-11ea-84b5-86d7856858a9.png)

I can fix the easy problem, where I failed to put `drop = FALSE` in subsetting the vcov matrix, so if it's 1x1, it resulted in a numeric value rather than a matrix; that's what caused the error. Getting the smoothing part in there, I dunno. If it's like `mgcv::gam`, I have a chance, but otherwise, I'm not inclined to dig deep in a pretty complicated package to figure it out.

**Comment by rvlenth** [comment]
OK; It wasn't hard to do. I added an option `use_pp` that requests it to use the `rstanarm::posterior_predict()` function. It defaults to `FALSE` except for objects fitted with `stan_gamm4()`. So now the above `emmip()` command yields

![image](https://user-images.githubusercontent.com/26777519/83065637-6d88b300-a029-11ea-8506-f74f0554d287.png)

I also fixed that other bug.

On "ordinary" results, here's a comparison:
```r
> emmeans(model2, "Species")
 Species    emmean lower.HPD upper.HPD
 setosa       6.28      4.94      7.13
 versicolor   5.52      4.83      6.24
 virginica    4.96      4.39      5.89

Point estimate displayed: median 
HPD interval probability: 0.95 
> 
> emmeans(model2, "Species", use_pp = FALSE)
 Species    emmean lower.HPD upper.HPD
 setosa       6.49      5.88      7.05
 versicolor   5.77      5.48      6.11
 virginica    5.26      4.97      5.64

Point estimate displayed: median 
HPD interval probability: 0.95 
```
The widths of the intervals with `use_pp = FALSE` are much smaller, presumably because we are not taking the smoother part into account.

**Comment by DominiqueMakowski** [comment]
Wow thanks a lot @rvlenth for fixing the error! Sad news for the smooth part, but it's unfortunately outside by range to be able to be of any help 😞 

As a note, stan_gamm4 *seems* to rely on [`mgcv::jagam`](https://github.com/stan-dev/rstanarm/blob/master/R/stan_gamm4.R#L182). I'm not sure if that's of any help...

I'll close this issue as it has been resolved, thanks again ☺️

**Comment by rvlenth** [comment]
I think the pandemic is making my brain fuzzy. That `use_pp` option is stupid and I will roll it back. The reason is that this produces *predictions*, not *estimates*. I'll see if I can get actual estimates that accommodate any smoothers; but what I had doesn't cut the mustard.

Moreover, given good estimates, **emmeans**'s provisions for predictive distributions appear to be better and more flexible than what's provided in `posterior_predict()`. I'll keep you posted.

**Comment by rvlenth** [comment]
OK. I looked at the code inside `posterior_predict()` and it gave me a good idea how to proceed. So now I seem to be able to support smooths. 
```r
plot(emmeans(model,  ~ Petal.Length, at = list(Petal.Length =seq(0.5,6,by=.25))), 
    horiz = FALSE)
```
![image](https://user-images.githubusercontent.com/26777519/83193561-e147c000-a0fc-11ea-9692-9e0bb9669f44.png)

The changing widths of the intervals clearly suggests that full info about the smoother is coming through.
I'm a little less sure if I now have the right code to support some other **rstanarm** models; but this seems to be a good start at least.

**Comment by DominiqueMakowski** [comment]
@rvlenth you're the best 🙏 🙌 thanks a lot

**Comment by rvlenth** [comment]
I think this is all resolved
