### ISSUE TITLE
p-value in equivalence test result

### ISSUE THREAD

**Issue by TheDom42** [rvlenth/emmeans#205]
First of all: thanks for such a great package! Very flexible and great for such a wide range of analyses!

**EDIT**
I noticed a misunderstanding of the `"holm"` correction on my side, which makes my question unnecessary. Nevertheless, my suggestion reported below is still up:

I would like to suggest a change to the way, equivalence test results obtained via `contrast(..., delta)` or `test(..., delta)` are reported : many people in the psychology community that want to use equivalence tests in their research, follow the TOST approach described by [Lakens](https://doi.org/10.1177%2F1948550617697177) and your package already came up in a [conversation on twitter](https://twitter.com/peder_isager/status/1198981160786890753) as well.
The TOST approach specifically reports the [two tests performed](https://cran.rstudio.com/web/packages/TOSTER/vignettes/IntroductionToTOSTER.html).
I'm not sure, if this is an option to you, but I think in order to make it easier for people previously using the `TOSTER` package switching over to `emmeans` for certain analyses, finding the same output (even just reachable via a method argument) might be a big plus.

Thanks again and looking forward to your thoughts!

**Comment by rvlenth** [comment]
The two-sided equivalence test that **emmeans** does *is* in fact the TOST procedure. Yes, I know that TOST involves two tests, but the summary format used by **emmeans** has space for only one t statistic and one P value. But since *both* tests must be significant for the result to be significant, we report the *less* significant *t* ratio and the *larger* P value.

Here are more details: If Q is the estimated quantity, SE is the SE of Q, and delta is the threshold, the two t statistics are:

  * (Test that Q is significantly less than delta): `t1 = (Q - delta) / SE` -- crit value is in negative tail
  * (Test that Q is significantly greater than -delta): `t2 = (Q - (-delta)) / SE`  -- crit val in pos tail

The way I made this into one t ratio is to reverse the sign of t2 so it is also a left-tailed test: `-t2 = (-Q - delta)/SE`. Now the TOST is significant only if 

    t1 < -tcrit   AND   -t2 < -tcrit

where -tcrit is a critical value in the left tail of the t distribution; and this is equivalent to saying that 

    max(t1, -t2) < -tcrit

So define

    tmax = max(t1, -t2) = max[(Q - delta), (-Q - delta)] / SE 
        = [max(Q, -Q) - delta] / SE
        = (|Q| - delta) / SE

So this is what is reported as the t statistic, and we test it against the left tail of the t distribution, so the P value is the tail area to the left of the observed t. It will not be significant unless t is a reasonably large negative value.

Besides all the notation, this makes intuitive sense. Suppose we observed Q = -0.47 and our threshold is delta = 1. We need to show that Q is statistically less than 1 *and* statistically greater than -1. In this example, the comparison with -1 will be the tougher hurdle because Q is negative and hence closer to that threshold. So if we look ahead, we see that we only really have to do one of those two t tests in the TOST procedure -- in this case, the nonsuperiority part. That t statistic is tmax = (-0.47 - (-1))/SE = 0.53/SE, for which the P value is P(T > 0.53/SE). But that is eual to P(T < -0.53/SE) by symmetry of the t distribution.

I hope that helps. Perhaps I should add a clarifying statement ot the man page for `summary.emmGrid`.

**Comment by rvlenth** [comment]
PS -- I do not have a Twitter account, so perhaps you could post on that Twitter thread a pointer to this issue if you think it would help clarify things.

**Comment by TheDom42** [comment]
Thank you very much for this extensive explanation! Yes, it does indeed help.

I was pretty sure, that the equivalence test is indeed probably the TOST approach but I was just a little bit unsure about the results presented, which is why I asked. So, yeah, it makes sense now! Thank you!

Concerning Twitter: unfortunately I also don't have Twitter - I just stumbled upon the thread when searching for equivalence tests for LMMs. Sorry. 😕
