### ISSUE TITLE
Vignette "transformations": default link for Poisson GLM is "log", not "square-root"

### ISSUE THREAD

**Issue by dwoll** [rvlenth/emmeans#210]
The vignette "transformations" currently states:

https://github.com/rvlenth/emmeans/blob/9b36f67b44d5878fb2904ae311e35e00bac0742c/vignettes/transformations.Rmd#L488

However, the default link for the Poisson family is "log".

Many thanks for developing emmeans, an immensely useful package!

**Comment by rvlenth** [comment]
Yikes. I guess my mindset was on variance-stabilizing transformations rather than link functions. Thanks for reporting this. I'll fix it.

Russ

Sent from my iPad

On Jun 24, 2020, at 6:32 AM, Daniel Wollschlaeger <notifications@github.com> wrote:

﻿

The vignette "transformations" currently states:

https://github.com/rvlenth/emmeans/blob/9b36f67b44d5878fb2904ae311e35e00bac0742c/vignettes/transformations.Rmd#L488

However, the default link for the Poisson family is "log".

Many thanks for developing emmeans, an immensely useful package!

**Comment by rvlenth** [comment]
OK, I fixed it in my local copy. Thanks again for reporting this! There will be a CRAN update pretty soon, i.e., in maybe a week.
