### ISSUE TITLE
Raw string does not work with R < 4.0.0

### ISSUE THREAD

**Issue by banfai** [rvlenth/emmeans#215]
https://github.com/rvlenth/emmeans/blob/01865c0aaccd50e9cd5466b974f339ee235317cd/R/emmGrid-methods.R#L564

The change introduced in fecb90a is only working on R >= 4.0.0. The raw string is failing during install on R < 4.0.0 (tested on 3.6.1).

**Comment by rvlenth** [comment]
You're right. That was dumb. I thought that was such a neat addition when I heard about it in Luke's talk in the RUser's conference, I had to try it. Since I'm not ready to require R >= 4.0.0, I have reverted to the old version and will try to contain myself... The change will be in my next commit -- which may not be very soon.

**Comment by banfai** [comment]
Thanks, I made a temporary fix in my fork, so it's all good, I can use that together with the fix for issue 214.
I can sympathize with the excitement, it is indeed a neat addition 😃 It's working perfectly with 4.0.x, so I'm looking forward to seeing it again in the future.
