### ISSUE TITLE
brms method in emmeans and brms

### ISSUE THREAD

**Issue by singmann** [rvlenth/emmeans#220]
Hi Russ,

Sorry for the flurry of issues, but I have one more thing to report. 

There now exists two `emmeans` method for `brms` obkjects. one in [`emmeans`](https://github.com/rvlenth/emmeans/blob/master/R/brms-support.R) and one in [`brms`](https://github.com/paul-buerkner/brms/blob/master/R/emmeans.R). Depending on whether or not `emmeans` is attached different methods are used. The problem with this is that the method in `brms` uses a bit more up-to-date code. The version in `emmeans` throws `deprecated` warnings as it uses some deprecated calls. See the following example:

```r
library("brms")
fit <- brm(time | cens(censored) ~ age * sex + disease + (1|patient),
            data = kidney, family = lognormal())

## without attaching uses emmeans method and produces warning:
emmeans::emmeans(fit, "disease")
#  disease emmean lower.HPD upper.HPD
#  other     4.13      3.49      4.87
#  GN        3.67      3.05      4.39
#  AN        3.59      2.96      4.24
#  PKD       4.69      3.62      5.79
# 
# Point estimate displayed: median 
# HPD interval probability: 0.95 
# Warning messages:
# 1: Method 'parse_bf' is deprecated. Please use 'brmsterms' instead. 
# 2: Method 'parse_bf' is deprecated. Please use 'brmsterms' instead. 
# 3: Argument 'exact_match' is deprecated. Please use 'fixed' instead. 

## after attaching uses brms method and warning goes away:
library("emmeans")
emmeans::emmeans(fit, "disease")
#  disease emmean lower.HPD upper.HPD
#  other     4.13      3.49      4.87
#  GN        3.67      3.05      4.39
#  AN        3.59      2.96      4.24
#  PKD       4.69      3.62      5.79
# 
# Point estimate displayed: median 
# HPD interval probability: 0.95 
```

I am not sure what would be the best course of action, but given that the method now exists in `brms` one could maybe remove the one in `emmeans`.

Cheers,
Henrik

**Comment by rvlenth** [comment]
Henrik,

Thanks for reporting this. I had thought that I had coded things so that external methods, if they exist, will always override internal ones. So I wasn't in any hurry to remove the old brms support.  But I didn't test this with emmeans not attached (very seldom the case for me...)  I'll take a look at this.

Sent from my iPad

On Aug 25, 2020, at 7:11 AM, Henrik Singmann <notifications@github.com> wrote:

﻿

Hi Russ,

Sorry for the flurry of issues, but I have one more thing to report.

There now exists two emmeans method for brms obkjects. one in emmeans<https://github.com/rvlenth/emmeans/blob/master/R/brms-support.R> and one in brms<https://github.com/paul-buerkner/brms/blob/master/R/emmeans.R>. Depending on whether or not emmeans is attached different methods are used. The problem with this is that the method in brms uses a bit more up-to-date code. The version in emmeans throws deprecated warnings as it uses some deprecated calls. See the following example:

library("brms")
fit <- brm(time | cens(censored) ~ age * sex + disease + (1|patient),
            data = kidney, family = lognormal())

## without attaching uses emmeans method and produces warning:
emmeans::emmeans(fit, "disease")
#  disease emmean lower.HPD upper.HPD
#  other     4.13      3.49      4.87
#  GN        3.67      3.05      4.39
#  AN        3.59      2.96      4.24
#  PKD       4.69      3.62      5.79
#
# Point estimate displayed: median
# HPD interval probability: 0.95
# Warning messages:
# 1: Method 'parse_bf' is deprecated. Please use 'brmsterms' instead.
# 2: Method 'parse_bf' is deprecated. Please use 'brmsterms' instead.
# 3: Argument 'exact_match' is deprecated. Please use 'fixed' instead.

## after attaching uses brms method and warning goes away:
library("emmeans")
emmeans::emmeans(fit, "disease")
#  disease emmean lower.HPD upper.HPD
#  other     4.13      3.49      4.87
#  GN        3.67      3.05      4.39
#  AN        3.59      2.96      4.24
#  PKD       4.69      3.62      5.79
#
# Point estimate displayed: median
# HPD interval probability: 0.95

I am not sure what would be the best course of action, but given that the method now exists in brms one could maybe remove the one in emmeans.

Cheers,
Henrik

**Comment by rvlenth** [comment]
I thought I understood why this happens... But my understanding led me to believe this would fail:

``` r
library(afex) 
#> Loading required package: lme4
#> Loading required package: Matrix
#> Registered S3 methods overwritten by 'car':
#>   method                          from
#>   influence.merMod                lme4
#>   cooks.distance.influence.merMod lme4
#>   dfbeta.influence.merMod         lme4
#>   dfbetas.influence.merMod        lme4
#> ************
#> Welcome to afex. For support visit: http://afex.singmann.science/
#> - Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
#> - Methods for calculating p-values with mixed(): 'KR', 'S', 'LRT', and 'PB'
#> - 'afex_aov' and 'mixed' objects can be passed to emmeans() for follow-up tests
#> - NEWS: library('emmeans') now needs to be called explicitly!
#> - Get and set global package options with: afex_options()
#> - Set orthogonal sum-to-zero contrasts globally: set_sum_contrasts()
#> - For example analyses see: browseVignettes("afex")
#> ************
#> 
#> Attaching package: 'afex'
#> The following object is masked from 'package:lme4':
#> 
#>     lmer

## (NOTE: emmeans not loaded yet)

a1 <- aov_ez("id", "value", obk.long, between = c("treatment", "gender"), 
             within = c("phase", "hour"), observed = "gender")
#> Contrasts set to contr.sum for the following variables: treatment, gender

emmeans::emmeans(a1, "treatment")
#> NOTE: Results may be misleading due to involvement in interactions
#>  treatment emmean    SE df lower.CL upper.CL
#>  control     4.22 0.550 10     3.00     5.45
#>  A           6.25 0.569 10     4.98     7.52
#>  B           6.03 0.521 10     4.87     7.19
#> 
#> Results are averaged over the levels of: gender, phase, hour 
#> Warning: EMMs are biased unless design is perfectly balanced 
#> Confidence level used: 0.95

methods("emm_basis")
#> Error in .S3methods(generic.function, class, envir): no function 'emm_basis' is visible

methods(class = "afex_aov")
#> [1] afex_plot anova     nice      print     summary  
#> see '?methods' for accessing help and source code
```
<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


I had speculated that when **emmeans** is not attached, the emmeans support methods  `afex_aov` objects would not be registered. That seems to be the case -- see the end of the output. See also, BTW, your news item: "NEWS: library('emmeans') now needs to be called explicitly!" -- which seems to match what I was thinking.

But then why does `emmeans()` work anyway in this example? There are NO internal methods for afex_aov objects.

Guess I'll have to probe further.

**Comment by singmann** [comment]
I agree. The way method dispatch works here is a bit mysterious 

The only thing I can add that if one wants to use `emmeans` in another package, it is unlikely that `emmeans` gets attached (as this would require it to be in `DEPENDS`). In this case, there would only be a call to `emmeans::emmeans()`. And it would be good that the most up-to-date method is called then.

**Comment by rvlenth** [comment]
Well, I learned something. S3 method dispatch uses the `getAnywhere()` function, which means it can find things that are not registered. That's why my test example succeeded when I expected it to fail.

My old code uses an internal dispatching algorithm that looks for outside methods; if found, it uses them, otherwise it reverts to standard S3 dispatching via `UseMethod()`. It used `getS3method()`, which does not find external methods unless they are registered; and they are not registered unless **emmeans** is attached. So your example works correctly when **emmeans** is attached, and otherwise, the external method is not found, but the internal ones are found by `UseMethod()`. 

I changed my custom-dispatch code so it uses `getAnywhere()`. That makes all the difference:
```r
> ### emmeans is not attached...
> search()
 [1] ".GlobalEnv"        "package:brms"      "package:Rcpp"      "tools:rstudio"    
 [5] "package:stats"     "package:graphics"  "package:grDevices" "package:utils"    
 [9] "package:datasets"  "package:methods"   "Autoloads"         "package:base"     

> ### but it does have methods for brmsfit objects...
> args(emmeans:::emm_basis.brmsfit)
function (object, trms, xlev, grid, vcov., ...) 
NULL

> ### Now, it uses brms's stuff anyway...
> emmeans::emmeans(fit, "disease")
 disease emmean lower.HPD upper.HPD
 other     4.11      3.41      4.81
 GN        3.68      3.03      4.39
 AN        3.58      2.95      4.27
 PKD       4.68      3.60      5.73

Point estimate displayed: median 
HPD interval probability: 0.95 
```

**Comment by rvlenth** [comment]
BTW, there can be more than one outside method. My code uses the first outside method it finds. So here is a test:
```r
> ### Create a method in the workspace
> emm_basis.brmsfit = function(x,y,z)
+   "This is just a dummy function"

> ### emmeans is NOT attached...
> meth = getAnywhere("emm_basis.brmsfit")
> meth[[3]]
[1] ".GlobalEnv"        "namespace:emmeans" "namespace:brms"   
> # So we will use the one in the workspace; otherwise, we skip over the one in emmeans and use the one in namespace:brms

> ### Now attach emmeans
> library(emmeans)
> meth = getAnywhere("emm_basis.brmsfit")
> meth[[3]]
[1] ".GlobalEnv"                         "registered S3 method for emm_basis"
[3] "namespace:emmeans"                  "namespace:brms"     
> # Still use one in workspace. Otherwise, use the registered S3 method (which is a dupe of the one in namespace:brms)
```
So I think this promises to work the way we would expect; at least usually

**Comment by singmann** [comment]
Thanks so much as usual!
