### ISSUE TITLE
[Question] Paired vs. unpaired comparisons - does emmeans care of in complex cases?

### ISSUE THREAD

**Issue by Generalized** [rvlenth/emmeans#221]
Dear Author!
It's not an issue, rather a question, to double make sure.

Let's assume we have a longitudinal trial with 2 treatments like below:
![obraz](https://user-images.githubusercontent.com/60151643/91295951-20d58500-e79c-11ea-88f5-fa297ae225ee.png)

One is interested to compare the effect of the treatment and also of the time.
Let's assume the model is like this:   gls(post_value ~ pre_value + Time * Treatment)

And let's say, one wants to compare only selected means:
1) treatments at the baseline
2) treatments at T1
3) gain (change) from baseline to T2  in treatment A
4) equality of gains between baseline and T2 for both treatments.

The first 2 comparisons are unpaired.
The 3rd one is paired (dependent)
The 4th - well, it's mixed, but we could compare the gains and use unpaired test.

When I provide those contrasts to emmeans, will it somehow guess, at least in simplest cases, that I may want paired (same treatment, different time) or unpaired (different treatments) comparisons and use appropriate parts of the model covariance?

Or is it assumed to run only unpaired tests (independent samples)?

If so, is there a way to tell emmeans what kind of comparison I want (and use conveniently mvt for adjusting for multiple comparisons), or do I have to reformulate the problem in case of paired data? I mean, use just single-sample t-test on differences (gain scores) between times at a fixed treatment instead?

**Comment by rvlenth** [comment]
Let's back up, and consider a simple paired experiment -- each subject receives two treatments, A and B, in random order, and observe a response y. If I fit the model `m1 = lm(y ~treatment)`, then `emmeans(m1, pairwise ~ treatment)` will estimate and compare the treatments as independent samples. If I fit the model `m2 = lme(y ~ treatment, random = ~1|subject)`, then `emmeans(m2, pairwise ~ treatment)` will compare the treatments as pairs, because the subject effect is accounted for. The points to note are

  * `m1` does not account for subject effects, so if you give `emmeans` that model, it can't possibly do a paired comparison 
  * `emmeans` uses the model you give it. `emmeans` does not do any modeling by itself.
  * The way to "tell" `emmeans` what kind of comparison to do is by handing it a model befitting that structure.

Now, with your example, I am guessing you have subjects involved, and the pairing is on subjects; but the model you have stated does not account for subject effects. So I surmise that all contrasts you have specified will be computed as independent-samples comparisons. If you want to account for pairing, the subjects need to be accounted for in your model. If you have different subjects under A and B (i.e., subjects are nested in treatment), then comparisons between A and B with such a model will still be between-subjects comparisons, and that will show in the covariance structure of the regression coefficients.

Here's a simple example to illustrate. The dataset `nlme::Oats` is a split-plot experiment. The plots are characterized as `Block:Variety` combinations. Varieties are randomized by whole plots, and fertilizer (`nitro`) is randomized to split plots, i.e., each plot is tested with all levels of `nitro`
```r
> library(lme4)
> Oats.lmer = lmer(yield ~ Variety + factor(nitro) + (1|Block:Variety), data = nlme::Oats)
```
Here are the EMMs for Variety, and the covariance among them:
```r
> v.emm = emmeans(Oats.lmer, "Variety")
> zapsmall(vcov(v.emm))  ## zapsmall makes near-zero values actually 0
         [,1]     [,2]     [,3]
[1,] 60.80163  0.00000  0.00000
[2,]  0.00000 60.80163  0.00000
[3,]  0.00000  0.00000 60.80163
```
This shows the EMMs for Variety are uncorrelated. That;'s because they are between-plots.
Now look at the EMMs for nitro:
```r
> n.emm = emmeans(Oats.lmer, "nitro")
> vcov(n.emm)
         [,1]     [,2]     [,3]     [,4]
[1,] 27.04049 18.00945 18.00945 18.00945
[2,] 18.00945 27.04049 18.00945 18.00945
[3,] 18.00945 18.00945 27.04049 18.00945
[4,] 18.00945 18.00945 18.00945 27.04049
```
These means are correlated. That's because the nitro effects are within-plot. Note that the variance of the difference of two EMMs is 27.04049 + 27.04049 - 2*(18.00945) = 18.06208.

Here's a third possibility---estimating the plots as a fixed factor:
```r
> Oats.lm = lm(yield ~ Variety + factor(nitro) + Block:Variety, data = nlme::Oats)
> n.emmf = emmeans(Oats.lm, "nitro")
NOTE: A nesting structure was detected in the fitted model:
    Block %in% Variety
> zapsmall(vcov(n.emmf))
         [,1]     [,2]     [,3]     [,4]
[1,] 9.031046 0.000000 0.000000 0.000000
[2,] 0.000000 9.031046 0.000000 0.000000
[3,] 0.000000 0.000000 9.031046 0.000000
[4,] 0.000000 0.000000 0.000000 9.031046
```
In this case, the EMMs are uncorrelated, but the plot variations are *accounted for*, making the estimated variances smaller. This is more or less the equivalent of analyzing paired comparisons by using paired differences as the response. Note the variance of a difference of two of these EMMs is 9.031046 + 9.031046 = 18.06209: the same as for the lmer model! 

So, **it is really important to fit a model the accounts for subject effects**. Fitting a model with fixed subject effects will get the correlation structure for the within-subjects EMMs wrong, and under-estimate their SEs because the subject effects are not regarded as random. But the pairwise comparisons will still be usable because the subject effects cancel out---it then doesn't matter whether they were modeled as fixed or random. 

However (not demonstrated, but true -- I'll leave it as an exercise), the between-subjects EMMs will have under-estimated variances *and* under-estimated SEs for comparisons. I think you need to use `lme` (which I think you prefer over lmer) to fit a model that accounts for *random* subject effects.

**Comment by Generalized** [comment]
Thank you a lot for so detailed clarification!
I'm sorry for the confusion - of course I accounted for the subject, but .... forgot to write it explicitly in the gls correlation/weights :-D Accounting for them was exactly why I used the generalized least square and not lm
(in "my" industry we think rather with the residual covariance structure, much more often, than thinking with random effects, that's why my examples use gls rather than lme)

PS: you remembered my preferences! I'm... astonished :)

So now I get it. Assuming I use a model, which properly states what's between (treatment), within (time) and specify the cluster with repeated observations (patient_id):
1. when I compare at a single time point between treatments, the comparisons are "unpaired" (that's between factor).
2. when compare within a treatment but between time points, the comparisons are "paired".
3. in the case I compare both through a contrast as showed in my question - it's - here I have to do a homework, because I'm still not sure, but probably unpaired on differences (unpaired comparison of the outcome of 2 paired).

by paired/unpaired I mean appropriate denominator (standard deviation).

Thank you once again!

**Comment by rvlenth** [comment]
OK, and you can always check the covariances among means like I did in my example. One could argue that you are implicitly specfying random effects via the correlation structure you impose.

**Comment by Generalized** [comment]
Yes, both are naturally connected - the final covariance matrix is a result of combining  the R (residual) + G (random effect) covariance. Using one of them and zeroing or diagonalizing the other results in specific special cases*. When both are used, it's not that easy to convert one into another. The issue is in the scientific justification of the chosen approach and results coming from that, which are processed further (e.g. giving a word about the random effects, variance components).

/* except compound symmetry in R (which can be approximated by random intercepts, but the space of parameters is different, which happens to cause problems, which I faced not once). ? 

Thank you for your relentless efforts in bringing the emmeans, one of the most important packages R have even had.
All the best!
