### ISSUE TITLE
How to speedup EMTRENDS computations?

### ISSUE THREAD

**Issue by kauttoj** [rvlenth/emmeans#233]
I have a big multivariate BRMS model containing factors and continuous covariates with interactions. For factors, I can compute grid

`GRID = ref_grid(model,resp="Y1",nesting=list())`

which takes ~3 minutes and then I can use this to make pairwise contrasts, such as

```
ems = emmeans(GRID,pairwise ~ factor1,level = 0.95)
ems = emmeans(GRID,pairwise ~ factor1 | factor2,level = 0.95)
ems = emmeans(GRID,pairwise ~ factor1 | factor2*factor3,level = 0.95)
```

which are very fast because of precomputed GRID. However, apparently this is not possible with EMTRENDS, which cannot take precomputed GRID or equivalents to speed up computations, so I have to do 

```
emt = emtrends(model,pairwise ~ factor1,var = "covariate1", level = 0.95,nesting=list(),resp="Y1")
emt = emtrends(model,pairwise ~ factor1 | factor2,var = "covariate1",level = 0.95,nesting=list(),resp="Y1")
emt = emtrends(model,pairwise ~ factor1 | factor2*factor3,var = "covariate1", level = 0.95,nesting=list(),resp="Y1")
```

which each take ~3mins. I have 7 covariates (covariate1-7), so running this for all of them would take ~1 hour.

Is there any way to make emtrends computations faster via precomputing some data? I have read vignettes, FAQ and forums, but maybe I have missed something...

**Comment by rvlenth** [comment]
Your 3-minute overhead is for computing the reference grid. As the documentation states, `emtrends()` always starts from the model, because it needs to construct a reference grid for the required factor combinations, plus the required increments to compute difference quotients. The `GRID` you show does not include the increments for the covariate. Also, these grids are *different* for each covariate. 

So really I do not see a way to speed this up in a general way. And the fact that it takes 3 minutes to construct a reference grid means this is one heck of a huge model. I think your best best is to put all the code you need for these in a script, set it running, and take a relaxing coffee break, I suggest including a provision to incrementally save the results in files and removing no-longer-needed objects, because I suspect you may also run into memory issues.

**Comment by kauttoj** [comment]
Ok, thank you for the response. I'll just put it running on background or overnight. [It's still fast anyway compared to model fitting, which took ~4 days...].
