### ISSUE TITLE
emmeans fails for pscl::hurdle

### ISSUE THREAD

**Issue by strengejacke** [rvlenth/emmeans#238]
This seems to be rather new, because it used to work in my package tests, but since some days, checks fail. So the code `emmeans(m2, "mined")` _was_ working before...

``` r
library(pscl)
library(emmeans)
data("Salamanders", package = "glmmTMB")
m1 <- zeroinfl(count ~ mined | mined, dist = "poisson", data = Salamanders)
m2 <- hurdle(count ~ mined | mined, dist = "poisson", zero.dist = "poisson", data = Salamanders)

emmeans(m1, "mined")
#>  mined emmean     SE  df asymp.LCL asymp.UCL
#>  yes    0.295 0.0449 Inf     0.207     0.383
#>  no     2.265 0.1242 Inf     2.021     2.508
#> 
#> Confidence level used: 0.95

emmeans(m2, "mined")
#> Error in object@dffun(x, object@dfargs): object 'object' not found
```

<sup>Created on 2020-10-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rvlenth** [comment]
*Aaarghhh!* Well, I know exactly what happened, It is indeed rather new, as in "since less than a day ago."

`emmGrid` objects have slots named `dffun` and `dfrags`. "Exactly what happened" is that I noticed recently that `dffun` comes out with the working environment from the `emm_basis()` method attached to it; that is potentially a lot of overhead, and it *should* be unnecessary, because everything it needs should be in `dfrags`. So I stripped off that environment to save on unnecessary memory use. The catch is the word "should" above. The method for `hurdle` objects was poorly written and violates that design. 

Here is a patch that will work until the next CRAN release. Just put this function somewhere in your search path.

```r
emm_basis.hurdle = function(object, ...) {
    result = emmeans:::emm_basis.hurdle(object, ...)
    result$dffun = function(k, dfargs) dfargs$df
    result$dfargs = list(df = object$df.residual)
    result
}
```
With this patch, we get results again:
```r
> emmeans(m2, "mined")
 mined emmean     SE  df lower.CL upper.CL
 yes    0.295 0.0415 640    0.214    0.377
 no     2.265 0.1112 640    2.047    2.483

Confidence level used: 0.95
```

**Comment by strengejacke** [comment]
Thanks for your fast reply! Are you planning to submit a fix soon, or with the next "regular" CRAN submission? I was asked to fix the failing CRAN checks (that are related to this bug) in my package within two weeks. I could just deactivate the related tests that cause the failing CRAN checks, and everything would be ok then. Else, if you're planning a "hotfix" the next days, I wouldn't need to submit a package update with deactivated tests. I'm fine with either solution...

**Comment by rvlenth** [comment]
Ah. I'd have thought I'd be CCd on downstream issues. I certainly will respond if they ask for it to be fixed. Perhaps you can respond to them and tell them we have been in communication? I do have this fixed on my end and will be happy to update it for them.

Russ

Sent from my iPad

On Oct 24, 2020, at 12:17 PM, Daniel <notifications@github.com> wrote:

﻿

Thanks for your fast reply! Are you planning to submit a fix soon, or with the next "regular" CRAN submission? I was asked to fix the failing CRAN checks (that are related to this bug) in my package within two weeks. I could just deactivate the related tests that cause the failing CRAN checks, and everything would be ok then. Else, if you're planning a "hotfix" the next days, I wouldn't need to submit a package update with deactivated tests. I'm fine with either solution...

**Comment by rvlenth** [comment]
Looking again at this, they did a reverse-depend check already. But that must not have included your package. Can you tell me the name of your package? I'll correspond directly rather than triangulating you.

Sent from my iPad

On Oct 24, 2020, at 12:17 PM, Daniel <notifications@github.com> wrote:

﻿

Thanks for your fast reply! Are you planning to submit a fix soon, or with the next "regular" CRAN submission? I was asked to fix the failing CRAN checks (that are related to this bug) in my package within two weeks. I could just deactivate the related tests that cause the failing CRAN checks, and everything would be ok then. Else, if you're planning a "hotfix" the next days, I wouldn't need to submit a package update with deactivated tests. I'm fine with either solution...

**Comment by strengejacke** [comment]
The package affected is ggeffects: https://cran.r-project.org/web/checks/check_results_ggeffects.html

Since my package "suggests" your package, it's not checked in emmeans' revdep check.

**Comment by rvlenth** [comment]
Got it. I'll CC you when I write. Thanks, Daniel



Sent from my iPad

On Oct 24, 2020, at 1:02 PM, Daniel <notifications@github.com> wrote:

﻿

The package affected is ggeffects: https://cran.r-project.org/web/checks/check_results_ggeffects.html

Since my package "suggests" your package, it's not checked in emmeans' revdep check.

**Comment by rvlenth** [comment]
OK, package re-submitted. Hoping for the best

**Comment by strengejacke** [comment]
That was fast, thanks a lot!

**Comment by rvlenth** [comment]
It's on CRAN now. This should solve the problem.
