### ISSUE TITLE
Bayesian Indexes of Effect Existence/Significance

### ISSUE THREAD

**Issue by jmgirard** [rvlenth/emmeans#243]
For Bayesian models (e.g., rstanarm, brms), would you consider adding one or more [indexes of effect existence and significance](https://www.frontiersin.org/articles/10.3389/fpsyg.2019.02767/full) (e.g., probability of direction, ROPE percentages, or Bayes factors) to the emmGrid output, even if just as optional/non-default arguments? These could be called from a dependency on [bayestestR](https://easystats.github.io/bayestestR/index.html) or rewritten without too much trouble (especially for pd).

**Comment by rvlenth** [comment]
A quick look at **bayestestR** revealed that its developers are all familiar names to me -- people who have been very helpful in reporting bugs and suggesting features. It turns out that that package already seems to quite fully support **emmeans**. In fact, I discovered that **bayestestR** provides  no fewer than16 methods for `emmGrid` objects, including the three you mention:
```r
> b4bt = methods(class="emmGrid")
> library(bayestestR)
> setdiff(methods(class = "emmGrid"), b4bt)
 [1] "bayesfactor_parameters.emmGrid" "bayesfactor_restricted.emmGrid"
 [3] "ci.emmGrid"                     "describe_posterior.emmGrid"    
 [5] "equivalence_test.emmGrid"       "estimate_density.emmGrid"      
 [7] "eti.emmGrid"                    "hdi.emmGrid"                   
 [9] "mhdior.emmGrid"                 "p_direction.emmGrid"           
[11] "p_map.emmGrid"                  "p_rope.emmGrid"                
[13] "p_significance.emmGrid"         "point_estimate.emmGrid"        
[15] "rope.emmGrid"                   "si.emmGrid"  
```
Based on the quality of my interactions with its developers, I have every reason to believe that these methods are superior to anything I could add on my own!

**Comment by jmgirard** [comment]
This is amazing! I wonder if there is some way to let emmeans users know about these extensions (perhaps in documentation?).

**Comment by rvlenth** [comment]
I'm considering adding it to Suggests, and adding an illustration of, say, Bayes factor, to one or more of the existing vignette examples.

Sent from my iPad

On Nov 12, 2020, at 3:55 PM, Jeffrey Girard <notifications@github.com> wrote:

﻿

This is amazing! I wonder if there is some way to let emmeans users know about these extensions (perhaps in documentation?).

**Comment by rvlenth** [comment]
This I think is resolved, so closing.
