### ISSUE TITLE
Combining emmeans$contrasts

### ISSUE THREAD

**Issue by MaLiUHH** [rvlenth/emmeans#245]
Hello,
I would like to combine multiple contrasts outputs from emmeans in order to apply multiple comparisons correction correctly.
I receive an error message saying Error in rbind(deparse.level, ...) : All objects must have the same fixed effects.

I used diffobj in order to check for differences between outputs, but couldn't find any (except the values per se). And actually combining the same output twice works just fine.

I also tried to combine anova outputs and again, it works nicely. Now, I noticed that assigning the anova output a name automatically transforms it to a dataframe. This is not the case for the contrasts output, it states 'formal class emmGrid'.
Might this be related to the issue?

Thanks!

**Comment by rvlenth** [comment]
There are a few issues involved in what you report.

One is that `emmeans()` and `contrasts()` produce objects of class `emmGrid`. Those objects contain needed information about estimates and their covariances. But see the next one.

Another, suggested by the title of your report, is that under some conditions, such as a two-sided formula, `emmeans()` produces a `list` of `emmGrid` objects (and their class is `emm_list`). I don't think this is an issue in what you tried because you selected the list members you wanted, but I mention this for completeness.

Third, the `rbind()` method for `emmGrid` objects requires that those objects be based on the same fitted model -- as is documented. I believe the error message you report is because of there being different models. There is currently no way to combine objects based on different models. Doing so may be sensible in certain instances, but the mechanics of doing this reliably are extremely complex. 

Fourth, evidently you did something that converted the `emmGrid` objects in question to data frames -- e.g., via the `summary` or `as.data.frame` method. There is an `rbind` method for data frames, and that would result in a combined data frame, but the statistical information (covariances and such) are no longer present so there is no way to perform the correct multiplicity adjustment. Again, there are instances where there may be legitimate ways to do this, but again there are considerable complexities to ensure doing it right.

If I am correct that you tried to combine results from different models, you need to instead fit a single model that is appropriaten to the situation. For illustration: you have datasets dat1 and dat2 with response variable `y` and factors `A` and `B`. Do something like this:
```r
dat1$rep <- "1"
dat2$rep <- "2"
dat <- rbind(dat1, dat2)
mod <- lm(y ~ (A + B)*rep, data = dat)  # essentially separate A + B models for each rep
emmA <- emmeans(mod, ~ A | rep)
conA <- pairs(emm)   # pairwise comparisons of A for each B
test(conA, by = NULL, adjust = "mvt")
```
The final result combines (via `by = NULL`) the two sets of pairwise comparisons into one family, and computes adjusted P values for that family. 

BTW, don't try `adjust = "tukey"` here, because it isn't appropriate (Tukey adjustment is for a *single* set of pairwise comparisons) and it will refuse to apply that adjustment, changing it to Sidak.

I hope that clarifies some issues.

**Comment by MaLiUHH** [comment]
Thank you so much for your quick and detailed reply. That was indeed very helpful.
