### ISSUE TITLE
changing the data.frame the model was fit from affects emtrends?

### ISSUE THREAD

**Issue by brian-bucher** [rvlenth/emmeans#247]
I had an error occur, and after doing some searching and playing with code, I now realize that the error comes from the fact that emtrends is looking for the dataframe that was used to fit the model, rather than using what's in the fit, and I was changing the levels of the dataframe to play around with different settings.  I don't know if using the dataframe rather than fit was intentional, but perhaps it's responsible for some of the other errors I've seen as I've been searching for answers.

Is there some reason you wouldn't want to use what's stored in the fit, which can be seen by running `str(fit_A)` and scrolling down to `$ model` ?

```
#
# emmeans version 1.5.2-1
# R 4.0.3
# Windows 10
#

# This errors -------------------------------------------------------------

library(emmeans)

# create the dataset
set.seed(123)
s_avg <- 1:5
m_avg <- c("A", "B", "C")  # three years
v_avg <- c("L2", "L3", "L4") # three fields per year
df <- expand.grid(s=s_avg, m=m_avg, v=v_avg)
df$y <- as.numeric(as.factor(df$v)) + rnorm(nrow(df), mean=0, sd=1)

# Fit three models with different reference levels

fit_A <- lm(y ~ v + m + s + s:m , data=df)
df$m <- relevel(df$m, ref = "B")
fit_B <- lm(y ~ v + m + s + s:m , data=df)
df$m <- relevel(df$m, ref = "C")
fit_C <- lm(y ~ v + m + s + s:m , data=df)

# Try to see the slopes for s by m
emtrends(fit_A, var="s", specs="m")
# Error in X[, nm, drop = FALSE] : subscript out of bounds

emtrends(fit_B, var="s", specs="m")
# Error in X[, nm, drop = FALSE] : subscript out of bounds

emtrends(fit_C, var="s", specs="m")
# This works

# This does work ----------------------------------------------------------

library(emmeans)

# create the dataset
set.seed(123)
s_avg <- 1:5
m_avg <- c("A", "B", "C")  # three years
v_avg <- c("L2", "L3", "L4") # three fields per year
df <- expand.grid(s=s_avg, m=m_avg, v=v_avg)
df$y <- as.numeric(as.factor(df$v)) + rnorm(nrow(df), mean=0, sd=1)

df$m <- relevel(df$m, ref = "A")
fit_A <- lm(y ~ v + m + s + s:m , data=df)
emtrends(fit_A, var="s", specs="m")

df$m <- relevel(df$m, ref = "B")
fit_B <- lm(y ~ v + m + s + s:m , data=df)
emtrends(fit_B, var="s", specs="m")

df$m <- relevel(df$m, ref = "C")
fit_C <- lm(y ~ v + m + s + s:m , data=df)
emtrends(fit_C, var="s", specs="m")


# emtrends needs the data.frame to still exist? ---------------------------

library(emmeans)

# create the dataset
set.seed(123)
s_avg <- 1:5
m_avg <- c("A", "B", "C")  # three years
v_avg <- c("L2", "L3", "L4") # three fields per year
df <- expand.grid(s=s_avg, m=m_avg, v=v_avg)
df$y <- as.numeric(as.factor(df$v)) + rnorm(nrow(df), mean=0, sd=1)

fit_A <- lm(y ~ v + m + s + s:m , data=df)
rm(df)
emtrends(fit_A, var="s", specs="m")

# Yet the data still exists in fit_A which can be seen by running
# str(fit_A) and scrolling down to "$ model"
```

**Comment by rvlenth** [comment]
Both emmeans and emtrends rely on reconstructing the data. That is necessary to find out the levels of factors and means of covariates. So if you change the data, you change the results.

Sent from my iPad

On Dec 5, 2020, at 2:26 PM, brian-bucher <notifications@github.com> wrote:

﻿

I had an error occur, and after doing some searching and playing with code, I now realize that the error comes from the fact that emtrends is looking for the dataframe that was used to fit the model, rather than using what's in the fit, and I was changing the levels of the dataframe to play around with different settings. I don't know if using the dataframe rather than fit was intentional, but perhaps it's responsible for some of the other errors I've seen as I've been searching for answers.

Is there some reason you wouldn't want to use what's stored in the fit, which can be seen by running str(fit_A) and scrolling down to $ model ?

#
# emmeans version 1.5.2-1
# R 4.0.3
# Windows 10
#

# This errors -------------------------------------------------------------

library(emmeans)

# create the dataset
set.seed(123)
s_avg <- 1:5
m_avg <- c("A", "B", "C")  # three years
v_avg <- c("L2", "L3", "L4") # three fields per year
df <- expand.grid(s=s_avg, m=m_avg, v=v_avg)
df$y <- as.numeric(as.factor(df$v)) + rnorm(nrow(df), mean=0, sd=1)

# Fit three models with different reference levels

fit_A <- lm(y ~ v + m + s + s:m , data=df)
df$m <- relevel(df$m, ref = "B")
fit_B <- lm(y ~ v + m + s + s:m , data=df)
df$m <- relevel(df$m, ref = "C")
fit_C <- lm(y ~ v + m + s + s:m , data=df)

# Try to see the slopes for s by m
emtrends(fit_A, var="s", specs="m")
# Error in X[, nm, drop = FALSE] : subscript out of bounds

emtrends(fit_B, var="s", specs="m")
# Error in X[, nm, drop = FALSE] : subscript out of bounds

emtrends(fit_C, var="s", specs="m")
# This works

# This does work ----------------------------------------------------------

library(emmeans)

# create the dataset
set.seed(123)
s_avg <- 1:5
m_avg <- c("A", "B", "C")  # three years
v_avg <- c("L2", "L3", "L4") # three fields per year
df <- expand.grid(s=s_avg, m=m_avg, v=v_avg)
df$y <- as.numeric(as.factor(df$v)) + rnorm(nrow(df), mean=0, sd=1)

df$m <- relevel(df$m, ref = "A")
fit_A <- lm(y ~ v + m + s + s:m , data=df)
emtrends(fit_A, var="s", specs="m")

df$m <- relevel(df$m, ref = "B")
fit_B <- lm(y ~ v + m + s + s:m , data=df)
emtrends(fit_B, var="s", specs="m")

df$m <- relevel(df$m, ref = "C")
fit_C <- lm(y ~ v + m + s + s:m , data=df)
emtrends(fit_C, var="s", specs="m")


# emtrends needs the data.frame to still exist? ---------------------------

library(emmeans)

# create the dataset
set.seed(123)
s_avg <- 1:5
m_avg <- c("A", "B", "C")  # three years
v_avg <- c("L2", "L3", "L4") # three fields per year
df <- expand.grid(s=s_avg, m=m_avg, v=v_avg)
df$y <- as.numeric(as.factor(df$v)) + rnorm(nrow(df), mean=0, sd=1)

fit_A <- lm(y ~ v + m + s + s:m , data=df)
rm(df)
emtrends(fit_A, var="s", specs="m")

# Yet the data still exists in fit_A which can be seen by running
# str(fit_A) and scrolling down to "$ model"

**Comment by brian-bucher** [comment]
Ok. Apparently there's some reason to have emmeans/emtrends rely on the original dataframe rather than the data and variable that got stored in the model itself, but I'm not experienced enough in R to understand why that would be.  Thanks.  I'm learning your package and it looks great.

**Comment by rvlenth** [comment]
I thought about this some while I was taking a walk. It's been 7+ years since I wrote that part of the code, and I believe that maybe I was thinking that the `$model` slot is not guaranteed to exist (one can do `lm(..., model = FALSE)` to suppress it). But nonetheless, it does usually exist, and it makes sense to use it if it is there. I'll look at this and try to find a non-awkward way to do this.

In the meantime, if you do
```r
emtrends(..., data = model.frame(fit_A))
```
it will use that internal data! 

I'm reopening this issue as I want to address it better.

**Comment by brian-bucher** [comment]
Ok, glad I found something you consider interesting.  I did try the call using data=model.frame(fit_A), but I get an error.  However, even if I just use the same dataframe that was used in fitting the model I get the same error.

```
library(emmeans)
set.seed(123)
s_avg <- 1:5
m_avg <- c("A", "B", "C")  # three years
v_avg <- c("L2", "L3", "L4") # three fields per year
df <- expand.grid(s=s_avg, m=m_avg, v=v_avg)
df$y <- as.numeric(as.factor(df$v)) + rnorm(nrow(df), mean=0, sd=1)

fit_A <- lm(y ~ v + m + s + s:m , data=df)
emtrends(fit_A, var="s", specs="m", data = model.frame(fit_A) )
emtrends(fit_A, var="s", specs="m", data = df )

# Both times I get the same error:
# Error in ref_grid(object = list(coefficients = c(`(Intercept)` = 1.43530191735432,  : 
# formal argument "data" matched by multiple actual arguments
```

**Comment by rvlenth** [comment]
Right. If you changed the data - especially the reference levels of factors -- after the model was fitted, that changes the names of the regression coefficients, and that really messes things up. Not sure why the model.frame didn't work for you. It does work for me.

Sent from my iPhone

On Dec 5, 2020, at 6:06 PM, brian-bucher <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, glad I found something you consider interesting. I did try the call using data=model.frame(fit_A), but I get an error. However, even if I just use the same dataframe that was used in fitting the model I get the same error.

library(emmeans)
set.seed(123)
s_avg <- 1:5
m_avg <- c("A", "B", "C")  # three years
v_avg <- c("L2", "L3", "L4") # three fields per year
df <- expand.grid(s=s_avg, m=m_avg, v=v_avg)
df$y <- as.numeric(as.factor(df$v)) + rnorm(nrow(df), mean=0, sd=1)

fit_A <- lm(y ~ v + m + s + s:m , data=df)
emtrends(fit_A, var="s", specs="m", data = model.frame(fit_A) )
emtrends(fit_A, var="s", specs="m", data = df )

# Both times I get the same error:
# Error in ref_grid(object = list(coefficients = c(`(Intercept)` = 1.43530191735432,  :
# formal argument "data" matched by multiple actual arguments

**Comment by rvlenth** [comment]
Oops, looking again I see that's a different error not in emmeans but peculiar to emtrends. Unfortunately, that means there are two things I need to fix.

Sent from my iPhone

On Dec 5, 2020, at 6:06 PM, brian-bucher <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, glad I found something you consider interesting. I did try the call using data=model.frame(fit_A), but I get an error. However, even if I just use the same dataframe that was used in fitting the model I get the same error.

library(emmeans)
set.seed(123)
s_avg <- 1:5
m_avg <- c("A", "B", "C")  # three years
v_avg <- c("L2", "L3", "L4") # three fields per year
df <- expand.grid(s=s_avg, m=m_avg, v=v_avg)
df$y <- as.numeric(as.factor(df$v)) + rnorm(nrow(df), mean=0, sd=1)

fit_A <- lm(y ~ v + m + s + s:m , data=df)
emtrends(fit_A, var="s", specs="m", data = model.frame(fit_A) )
emtrends(fit_A, var="s", specs="m", data = df )

# Both times I get the same error:
# Error in ref_grid(object = list(coefficients = c(`(Intercept)` = 1.43530191735432,  :
# formal argument "data" matched by multiple actual arguments

**Comment by rvlenth** [comment]
I have both errors fixed, I hope:

``` r
require(emmeans)
#> Loading required package: emmeans
data(fiber)

fiber.lm = lm(strength ~ machine * diameter, data = fiber)

emtrends(fiber.lm, "machine", var = "diameter")
#>  machine diameter.trend    SE df lower.CL upper.CL
#>  A                1.104 0.194  9    0.666     1.54
#>  B                0.857 0.224  9    0.351     1.36
#>  C                0.864 0.208  9    0.394     1.33
#> 
#> Confidence level used: 0.95

# works when we supply data
emtrends(fiber.lm, "machine", var = "diameter", data = fiber[-c(3,7,11), ])
#>  machine diameter.trend    SE df lower.CL upper.CL
#>  A                1.104 0.194  9    0.666     1.54
#>  B                0.857 0.224  9    0.351     1.36
#>  C                0.864 0.208  9    0.394     1.33
#> 
#> Confidence level used: 0.95

# works correctly after changing data
fiber$machine = relevel(fiber$machine, ref = "C")
emtrends(fiber.lm, "machine", var = "diameter")
#>  machine diameter.trend    SE df lower.CL upper.CL
#>  A                1.104 0.194  9    0.666     1.54
#>  B                0.857 0.224  9    0.351     1.36
#>  C                0.864 0.208  9    0.394     1.33
#> 
#> Confidence level used: 0.95

# fails if we supply bad data
emtrends(fiber.lm, "machine", var = "diameter", data = fiber)
#> Error in X[, nm, drop = FALSE]: subscript out of bounds
```

<sup>Created on 2020-12-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

You may install from GitHub or wait until I update to CRAN, which will be within a week I think.

**Comment by rvlenth** [comment]
Well, crud. It didn't take me long to notice how this "fix" creates other problems...
```r
> example(pigs)

pigs>   pigs.lm <- lm(log(conc) ~ source + factor(percent), data = pigs)

pigs>   emmeans(pigs.lm, "source")
Error in `[.data.frame`(tbl, , vars, drop = FALSE) : 
  undefined columns selected
```
This happens because
```r
> head(pigs.lm$model)
  log(conc) source factor(percent)
1  3.325036   fish               9
2  3.165475   fish               9
3  3.449988   fish              12
4  3.349904   fish              12
5  3.490429   fish              12
6  3.526361   fish              15
```
That is, the frame that is saved with the model includes any transformations of the response or predictors, including modified names for those columns. Now I remember why this was so thorny.

I'm afraid I am going to have to revert to the old code. Sorry.

**Comment by rvlenth** [comment]
I did fix the error with the data argument though. So now here's what we can and cannot do:

``` r
require(emmeans)
#> Loading required package: emmeans

fiber.lm  = lm(strength ~ machine*diameter, data = fiber)
fibersqrt.lm = lm(strength ~ machine*sqrt(diameter), data = fiber)

# works out of the box
emtrends(fiber.lm, "machine", "diameter")
#>  machine diameter.trend    SE df lower.CL upper.CL
#>  A                1.104 0.194  9    0.666     1.54
#>  B                0.857 0.224  9    0.351     1.36
#>  C                0.864 0.208  9    0.394     1.33
#> 
#> Confidence level used: 0.95
emtrends(fibersqrt.lm, "machine", "diameter")
#>  machine diameter.trend    SE df lower.CL upper.CL
#>  A                1.142 0.209  9    0.670     1.61
#>  B                0.884 0.239  9    0.344     1.42
#>  C                0.767 0.196  9    0.323     1.21
#> 
#> Confidence level used: 0.95

# fails when we change the data
fiber$machine = relevel(fiber$machine, ref = "C")
emtrends(fiber.lm, "machine", "diameter")
#> Error in X[, nm, drop = FALSE]: subscript out of bounds

# ... but works if we supply the original data
emtrends(fiber.lm, "machine", "diameter", data = fiber.lm$model)
#>  machine diameter.trend    SE df lower.CL upper.CL
#>  A                1.104 0.194  9    0.666     1.54
#>  B                0.857 0.224  9    0.351     1.36
#>  C                0.864 0.208  9    0.394     1.33
#> 
#> Confidence level used: 0.95


### Extra ssues with predictor transformations
# Doesn't work because $model slot has wrong data
emtrends(fibersqrt.lm, "machine", "diameter", data = fibersqrt.lm$model)
#> Error in `[.data.frame`(tbl, , vars, drop = FALSE): undefined columns selected

# but works if we can get the original data
emtrends(fibersqrt.lm, "machine", "diameter", data = emmeans::fiber)
#>  machine diameter.trend    SE df lower.CL upper.CL
#>  A                1.142 0.209  9    0.670     1.61
#>  B                0.884 0.239  9    0.344     1.42
#>  C                0.767 0.196  9    0.323     1.21
#> 
#> Confidence level used: 0.95
```

<sup>Created on 2020-12-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rvlenth** [comment]
I'm going to go ahead and close. I'm sorry I can't do more on recovering built-in data -- which sometimes works but not reliably. Thanks for the report, and I'm also glad to have uncovered another bug that I *was* able to fix!

**Comment by rvlenth** [comment]
I promise, this'll be the last comment on this unless you have questions. I decided on a compromise solution: By examining the model formula, we can tell whether the model formula has function calls. If it doesn't, we can use `object$model` as the data;
otherwise, we have to rely on the existing data and hope it hasn't disappeared or been changed. So now we have a little bit more success:

``` r
require(emmeans)
#> Loading required package: emmeans

fiber.lm  = lm(strength ~ machine*diameter, data = fiber)
fibersqrt.lm = lm(strength ~ machine*sqrt(diameter), data = fiber)

# works out of the box
emtrends(fiber.lm, "machine", "diameter")
#>  machine diameter.trend    SE df lower.CL upper.CL
#>  A                1.104 0.194  9    0.666     1.54
#>  B                0.857 0.224  9    0.351     1.36
#>  C                0.864 0.208  9    0.394     1.33
#> 
#> Confidence level used: 0.95

emtrends(fibersqrt.lm, "machine", "diameter")
#>  machine diameter.trend    SE df lower.CL upper.CL
#>  A                1.142 0.209  9    0.670     1.61
#>  B                0.884 0.239  9    0.344     1.42
#>  C                0.767 0.196  9    0.323     1.21
#> 
#> Confidence level used: 0.95

# DOESN'T fail when we change the data
fiber$machine = relevel(fiber$machine, ref = "C")
emtrends(fiber.lm, "machine", "diameter")
#>  machine diameter.trend    SE df lower.CL upper.CL
#>  A                1.104 0.194  9    0.666     1.54
#>  B                0.857 0.224  9    0.351     1.36
#>  C                0.864 0.208  9    0.394     1.33
#> 
#> Confidence level used: 0.95

### Extra issues with predictor transformations
# Doesn't work because $model slot can't be used, so reverts to altered fiber data
emtrends(fibersqrt.lm, ~ machine | diameter, "diameter", 
         at = list(diameter = c(16, 24, 32)))
#> Error in X[, nm, drop = FALSE]: subscript out of bounds

# but works if we can get the original data
emtrends(fibersqrt.lm, ~ machine | diameter, "diameter", data = emmeans::fiber,
         at = list(diameter = c(16, 24, 32)))
#> diameter = 16:
#>  machine diameter.trend    SE df lower.CL upper.CL
#>  A                1.403 0.257  9    0.823     1.98
#>  B                1.086 0.293  9    0.422     1.75
#>  C                0.942 0.241  9    0.397     1.49
#> 
#> diameter = 24:
#>  machine diameter.trend    SE df lower.CL upper.CL
#>  A                1.146 0.209  9    0.672     1.62
#>  B                0.887 0.240  9    0.345     1.43
#>  C                0.769 0.197  9    0.324     1.21
#> 
#> diameter = 32:
#>  machine diameter.trend    SE df lower.CL upper.CL
#>  A                0.992 0.181  9    0.582     1.40
#>  B                0.768 0.207  9    0.298     1.24
#>  C                0.666 0.170  9    0.281     1.05
#> 
#> Confidence level used: 0.95
```

<sup>Created on 2020-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by brian-bucher** [comment]
Sounds good.  Once I update from CRAN I'll verify with my code as well, though I don't have any doubts it'll work.  Mainly my hope was to be able to contribute in a small way, so I'm glad I was able to do that.  Thanks again for the package and your diligence in maintaining.  Much appreciated.
