### ISSUE TITLE
use of emmeans with models from survey library

### ISSUE THREAD

**Issue by coreysparks** [rvlenth/emmeans#248]
Hi, I was curious if your package could be extended to include the models from the survey library. Notably, svyglm() which fits glm's to complex survey design data.
Thank you
-Corey

**Comment by coreysparks** [comment]
Actually, these can be accommodated by supplying the dataframe with the original data, so it's a work around.

**Comment by rvlenth** [comment]
Glad you got it to work. I suppose it's inheriting the method for `lm/glm` objects; makes me wonder why it doesn't recover the data. I'll try to remember to take a look. If there is a `$model` component and there are no predictor transformations, it may work without specifying `data` (because the model frame is the same as a the model data in that case).

**Comment by coreysparks** [comment]
The svyglm() embeds the data in a design object within the model, so it's not directly accessible like regular glm()

Corey Sparks, PhD
Associate professor and Graduate Advisor
Department of Demography
The University of Texas at San Antonio
em: corey 'dot' sparks 'at' utsa 'dot' edu
@CoreySparks1
coreysparks.github.io

Co-Editor in Chief
Population Research and Policy Review
https://link.springer.com/journal/11113

________________________________

**Comment by rvlenth** [comment]
Hi, I'm re-opening so I remember to look at this again.

**Comment by rvlenth** [comment]
OK, I think I have this working without requiring `data` in the call:
``` r
require(survey, quietly = TRUE)
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart
require(emmeans, quietly = TRUE)

# from example for svyglm
data(api)
dstrat<-svydesign(id=~1,strata=~stype, weights=~pw, data=apistrat, fpc=~fpc)

svymod <- svyglm(api00 ~ ell + meals + mobility, design = dstrat)
emmeans(svymod, ~ mobility, at = list(mobility = c(10, 15, 20)))
#>  mobility emmean   SE  df asymp.LCL asymp.UCL
#>        10    672 5.18 Inf       662       682
#>        15    673 4.43 Inf       664       682
#>        20    674 4.48 Inf       665       683
#> 
#> Confidence level used: 0.95

svymod2 <- svyglm(api00 ~ ell + meals + sqrt(mobility), design = dstrat)
emmeans(svymod2, ~ mobility, at = list(mobility = c(10, 15, 20)))
#>  mobility emmean   SE  df asymp.LCL asymp.UCL
#>        10    669 5.37 Inf       659       680
#>        15    673 4.36 Inf       664       681
#>        20    676 4.89 Inf       666       685
#> 
#> Confidence level used: 0.95
```

<sup>Created on 2020-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I believe that the first one does now work in **emmeans** 1.5.3 due to its added capability to try to recover the data from the `$model` component, if present. However, the second one will not work in that version because the model feram contains `sqrt(mobility)` rather than `mobility` itself.

I also added `svyglm` to the ``models` vignette.
