### ISSUE TITLE
reg_grid with polynomial transformation

### ISSUE THREAD

**Issue by DominiqueMakowski** [rvlenth/emmeans#26]
I am fitting a bayesian model as follows:

```r
df <- data.frame(
                 RT = rnorm(100, 30, .2), 
                 Stress = runif(100, 3, 5))

fit <- rstanarm::stan_glm(RT ~ poly(Stress, 2, raw=T), data=df)
```

I'd like to extract the reference grid (to further predict the outcome):

```r
ref_grid <- emmeans::ref_grid(fit, at = list(
  Stress = seq(min(df$Stress),
            max(df$Stress),
            length.out = 10)))
```
But it says the following:
``` 
Error in model.frame.default(formula = ~Stress + T, data = df, drop.unused.levels = TRUE,  : 
  variables differ in length (found for 'T')
Error in emmeans::ref_grid(fit, at = list(Stress = seq(min(df$Stress),  : 
  Perhaps a 'data' or 'params' argument is needed
```

What can I do?

Thanks for your help!

**Comment by rvlenth** [comment]
Use raw = TRUE in your call to poly(). My code uses ‘all.vars()’ to find the variable names…

R> all.vars(~ poly(x, raw = T))
[1] "x" "T"

R> all.vars(~ poly(x, raw = TRUE))
[1] "x"

R tries to accommodate users who specify T and F instead of TRUE and FALSE, but it is hit and miss. I don’t ever use those abbreviations because they are unreliable.

Yes, only the fixed effects are included in the reference grid.

Russ

**Comment by DominiqueMakowski** [comment]
It works like a charm using TRUE, thanks I didn't know it was unreliable!

Many thanks, good luck with that awesome package ;)
