### ISSUE TITLE
Layout of plot from emmip()

### ISSUE THREAD

**Issue by georgeford22** [rvlenth/emmeans#261]
Hi,
Not sure if I am posting in the right place as new to this.

On plotting an emmip graph, I have 5 graphs in one and the last one is on the top line when I want on the bottom line. Do you know how to change this? 

this is the code:
emmip(TD_location_interaction_model, ~  match_location|position, CIs = TRUE)
![EMMIP Graph](https://user-images.githubusercontent.com/80101728/110106964-3c9c9200-7da2-11eb-8398-2fadc7793699.png)

**Comment by rvlenth** [comment]
It is definitely appropriate to post this issue here. My only request is that next time, you give a better description of the issue. (I renamed it.)

Sadly, my answer is "I don't know." `emmip()` produces an object of class `ggplot` -- which actually contains the specifications for the plot. The plot itself isn't made until it is "printed." And mode plot specifications can be added (literally - using the `+` operator. So the basic strategy would be like this:
```r
plt <- emmip(TD_location_interaction_model, ~ match_location|position, CIs = TRUE)
plt + something(...)
```
where `something()` is a call to some function(s) in the **ggplot2** package. I was able tom muddle through enough of that package to make `emmip()` work, but I am far from an expert. It looks like `facet_wrap()` may offer what you need; but I won't swear by it. You can specify the number of rows and columns, and what order they go in.

**Comment by georgeford22** [comment]
> It is definitely appropriate to post this issue here. My only request is that next time, you give a better description of the issue. (I renamed it.)
> 
> Sadly, my answer is "I don't know." `emmip()` produces an object of class `ggplot` -- which actually contains the specifications for the plot. The plot itself isn't made until it is "printed." And mode plot specifications can be added (literally - using the `+` operator. So the basic strategy would be like this:
> 
> ```r
> plt <- emmip(TD_location_interaction_model, ~ match_location|position, CIs = TRUE)
> plt + something(...)
> ```
> 
> where `something()` is a call to some function(s) in the **ggplot2** package. I was able tom muddle through enough of that package to make `emmip()` work, but I am far from an expert. It looks like `facet_wrap()` may offer what you need; but I won't swear by it. You can specify the number of rows and columns, and what order they go in.

**Comment by rvlenth** [comment]
Good question. The reason the labels show up the way they do is that I use `ggplot2::label_both()`. It may be possible to add `facet_wrap(something, labeller = "label_value")` but I could not get this to work myself.

I did add an argument `facetlab` to `emmip_ggplot()` to facilitate this. The default is `"label_context"` which in your case will give you just the levels, like you want, but in general it allows the user to specify which labeller to use. Once I push it to GitHub, you can install the revised package. I will be sending an update to CRAN before too long, then it will be there.

**Comment by rvlenth** [comment]
I am closing this as I think it is mostly resolved. But you may still comment. Note then updated function is now in CRAN emmeans 1.5.5-1
