### ISSUE TITLE
emmeans for metafor

### ISSUE THREAD

**Issue by itchyshin** [rvlenth/emmeans#269]
May I request you to have `emmeans` work for `rma` and `rma.mv` objectives from the `metafor` package?

I have tried but failed. Very much appreciated.

**Comment by rvlenth** [comment]
I'll take a look and see how feasible it is

**Comment by itchyshin** [comment]
Many thanks! @rvlenth

**Comment by rvlenth** [comment]
At first glance, it appears that `qdrg()` works pretty well...
```r
> # An example from predict.rma
> res <- rma(measure="RR", ai=tpos, bi=tneg, ci=cpos, di=cneg,
+            mods = ~ ablat + factor(alloc), data=dat.bcg)

> RG = qdrg(object = res, data = dat.bcg)
Warning message:
In ref_grid(result, ...) :
  There are unevaluated constants in the response formula
Auto-detection of the response transformation may be incorrect

> RG
'emmGrid' object with variables:
    ablat = 33.462
    alloc = alternate, random, systematic
Transformation: “factor” 
```
This message reflects a small issue in that it gets confused due to the formula not having a left-hand side, and thinks it detects a response transformation. But we can ignore it, or use `update()` to get rid of it
```r
> emmeans(update(RG, tran = NULL), "alloc")
 alloc      emmean    SE  df asymp.LCL asymp.UCL
 alternate  -0.619 0.294 Inf     -1.19   -0.0442
 random     -0.887 0.191 Inf     -1.26   -0.5123
 systematic -0.561 0.244 Inf     -1.04   -0.0822

Confidence level used: 0.95 
```

**Comment by itchyshin** [comment]
Wow, it's great. Let me try more especially with `rma.mv`. If I have an issue, I get back to you.

**Comment by rvlenth** [comment]
I fixed `qdrg()` so it doesn't get confused about response transformations. 
```r
# Previous example
> qdrg(object = res, data = dat.bcg)
'emmGrid' object with variables:
    ablat = 33.462
    alloc = alternate, random, systematic
```
(This will work for you only after I push this to GitHub and you install it from there.)

Also, I note that not all `rma` objects have a formula, and we require one. So in those cases, you may have to specify `formula`, `coef`, `vcov`, instead of `object`.

It does seem to work with `rma.mv` objects as well:
```r
# with last example for rma.mv, but I named it `res.mv`:
> MRG = qdrg(object = res.mv, data = dat.long)
> MRG
'emmGrid' object with variables:
    group = 1, 2
> emmeans(MRG, "group")
 group emmean    SE  df asymp.LCL asymp.UCL
 1      -4.84 0.353 Inf     -5.53     -4.15
 2      -4.10 0.453 Inf     -4.98     -3.21

Confidence level used: 0.95 
```

**Comment by itchyshin** [comment]
@rvlenth - this is really fantastic so my test here.

I have a quite complicated model (in terms of random effects) but I have 1 categorical variable and 2 continuous variables. 

```r
> # test
> mod <- rma.mv(yi, vi,
+                mods=~ 1 + vi + 
+                 year.c +
+                 CaptivityC, 
+               random=list(~ 1 | Species.updated, # phylo effect
+                          ~ 1 | Species, # non-phylo effect
+                          ~ 1 | study, 
+                         ~ 1 | obsID), 
+                   R = list(Species.updated = phylo_cor), #phylogenetic relatedness
+                   method="REML",
+                   test="t", # using t dist rather than z
+                   data=dataset.r)
> 
> # preparation to get marginalised mean (when vi = 0 and year.c = 0)
> res <- qdrg(object = mod, data = dataset.r, at = list(vi = 0, year.c = 0))
> # marginalized overall mean at vi = 0 and year.c = 0
> emmeans(res.publication.bias.model.r, specs = ~1, df = 104 - 7) # using effect size - 7 
 1       emmean     SE df lower.CL upper.CL
 overall  0.261 0.0729 97    0.116    0.406

Results are averaged over the levels of: CaptivityC 
Degrees-of-freedom method: user-specified 
Confidence level used: 0.95 
> # marginalised means for different levels for CaptivityC
> emmeans(res, specs = "CaptivityC", df = 104 - 7)
 CaptivityC emmean     SE df lower.CL upper.CL
 FC          0.245 0.0742 97   0.0972    0.392
 FW          0.235 0.1154 97   0.0063    0.464
 WCT         0.275 0.0778 97   0.1208    0.430
 WCT&FC      0.426 0.1732 97   0.0818    0.769
 WCT&FW      0.125 0.1414 97  -0.1557    0.406

Degrees-of-freedom method: user-specified 
Confidence level used: 0.95 
```
So it does everything I want to do, but I tried to change `weights` arguments but they do not seem to have any effects. Although we certainly have different frequencies for different groups.

```r
> emmeans(res, specs = "CaptivityC", df = 104 - 7, weights = "cells")
 CaptivityC emmean     SE df lower.CL upper.CL
 FC          0.245 0.0742 97   0.0972    0.392
 FW          0.235 0.1154 97   0.0063    0.464
 WCT         0.275 0.0778 97   0.1208    0.430
 WCT&FC      0.426 0.1732 97   0.0818    0.769
 WCT&FW      0.125 0.1414 97  -0.1557    0.406

Degrees-of-freedom method: user-specified 
Confidence level used: 0.95 
> emmeans(res, specs = "CaptivityC", df = 104 - 7, weights = "equal")
 CaptivityC emmean     SE df lower.CL upper.CL
 FC          0.245 0.0742 97   0.0972    0.392
 FW          0.235 0.1154 97   0.0063    0.464
 WCT         0.275 0.0778 97   0.1208    0.430
 WCT&FC      0.426 0.1732 97   0.0818    0.769
 WCT&FW      0.125 0.1414 97  -0.1557    0.406

Degrees-of-freedom method: user-specified 
Confidence level used: 0.95 
> res@grid
  vi year.c CaptivityC .wgt.
1  0      0         FC    50
2  0      0         FW    10
3  0      0        WCT    36
4  0      0     WCT&FC     3
5  0      0     WCT&FW     5
```
I tried `update` and few other things but no luck. Any help will be appreciated.

**Comment by rvlenth** [comment]
The weights will not make any difference unless you are averaging over something! Here you have 5 different CaptivityC levels, each with its own weight. Those weights won't be used as long as you keep them separate. On the other hand, if you compute emmeans(res, ~ 1, weights = "prop") then you WILL get different results than with weights = "equal")

Sent from my iPad

On Apr 7, 2021, at 7:03 PM, Shinichi Nakagawa ***@***.***> wrote:

﻿

@rvlenth<https://github.com/rvlenth> - this is really fantastic so my test here.

I have a quite complicated model (in terms of random effects) but I have 1 categorical variable and 2 continuous variables.

> # test
> mod <- rma.mv(yi, vi,
+                mods=~ 1 + vi +
+                 year.c +
+                 CaptivityC,
+               random=list(~ 1 | Species.updated, # phylo effect
+                          ~ 1 | Species, # non-phylo effect
+                          ~ 1 | study,
+                         ~ 1 | obsID),
+                   R = list(Species.updated = phylo_cor), #phylogenetic relatedness
+                   method="REML",
+                   test="t", # using t dist rather than z
+                   data=dataset.r)
>
> # preparation to get marginalised mean (when vi = 0 and year.c = 0)
> res <- qdrg(object = mod, data = dataset.r, at = list(vi = 0, year.c = 0))
> # marginalized overall mean at vi = 0 and year.c = 0
> emmeans(res.publication.bias.model.r, specs = ~1, df = 104 - 7) # using effect size - 7
 1       emmean     SE df lower.CL upper.CL
 overall  0.261 0.0729 97    0.116    0.406

Results are averaged over the levels of: CaptivityC
Degrees-of-freedom method: user-specified
Confidence level used: 0.95
> # marginalised means for different levels for CaptivityC
> emmeans(res, specs = "CaptivityC", df = 104 - 7)
 CaptivityC emmean     SE df lower.CL upper.CL
 FC          0.245 0.0742 97   0.0972    0.392
 FW          0.235 0.1154 97   0.0063    0.464
 WCT         0.275 0.0778 97   0.1208    0.430
 WCT&FC      0.426 0.1732 97   0.0818    0.769
 WCT&FW      0.125 0.1414 97  -0.1557    0.406

Degrees-of-freedom method: user-specified
Confidence level used: 0.95

So it does everything I want to do, but I tried to change weights arguments but they do not seem to have any effects. Although we certainly have different frequencies for different groups.

> emmeans(res, specs = "CaptivityC", df = 104 - 7, weights = "cells")
 CaptivityC emmean     SE df lower.CL upper.CL
 FC          0.245 0.0742 97   0.0972    0.392
 FW          0.235 0.1154 97   0.0063    0.464
 WCT         0.275 0.0778 97   0.1208    0.430
 WCT&FC      0.426 0.1732 97   0.0818    0.769
 WCT&FW      0.125 0.1414 97  -0.1557    0.406

Degrees-of-freedom method: user-specified
Confidence level used: 0.95
> emmeans(res, specs = "CaptivityC", df = 104 - 7, weights = "equal")
 CaptivityC emmean     SE df lower.CL upper.CL
 FC          0.245 0.0742 97   0.0972    0.392
 FW          0.235 0.1154 97   0.0063    0.464
 WCT         0.275 0.0778 97   0.1208    0.430
 WCT&FC      0.426 0.1732 97   0.0818    0.769
 WCT&FW      0.125 0.1414 97  -0.1557    0.406

Degrees-of-freedom method: user-specified
Confidence level used: 0.95
> ***@***.***
  vi year.c CaptivityC .wgt.
1  0      0         FC    50
2  0      0         FW    10
3  0      0        WCT    36
4  0      0     WCT&FC     3
5  0      0     WCT&FW     5

I tried update and few other things but no luck. Any help will be appreciated.

**Comment by itchyshin** [comment]
@rvlenth - thanks for your quick reply. Ahhh it makes sense (I was somehow confused) and I do get different estimates. 

```r
>  emmeans(res, ~1, df = 104 - 7, weights = "cells")
 1       emmean     SE df lower.CL upper.CL
 overall  0.254 0.0637 97    0.127     0.38

Results are averaged over the levels of: CaptivityC 
Degrees-of-freedom method: user-specified 
Confidence level used: 0.95 
>  emmeans(res,  ~1, df = 104 - 7, weights = "equal")
 1       emmean     SE df lower.CL upper.CL
 overall  0.261 0.0729 97    0.116    0.406

Results are averaged over the levels of: CaptivityC 
Degrees-of-freedom method: user-specified 
Confidence level used: 0.95 
```
This is great as I wanted either "prop" or "cells" over "equal" or "flat"

Thanks - I will try a few more things before closing this issue.

**Comment by itchyshin** [comment]
@rvlenth - it seems all working for me. Do you have a plan to put this version to CRAN? I plan to write several R functions using `emmeans()` for this package - https://github.com/itchyshin/orchard_plot. Could you let me know once the version that includes this little fix goes on CRAN. Thank you so much!!

**Comment by rvlenth** [comment]
I will be sending the update to CRAN fairly soon. The last update was March 21 and they don't want them more often than once a month, so it could be any time. However, I need to update a few minor things, do some testing and checking, etc. so it could still be a week or two. But not long.

Another thing you could do to get it even earlier is install this latest version directly from GitHub. Just follow the directions on the "<>Code" tab.

**Comment by itchyshin** [comment]
Much appreciated - yes for now - I will do `remotes::install_github("rvlenth/emmeans", dependencies = TRUE, build_opts = "")`
