### ISSUE TITLE
emmeans for gam vs gamm

### ISSUE THREAD

**Issue by rubeenmp** [rvlenth/emmeans#270]
Hi!

I am a fairly new user of the emmeans package. Now, I am modeling some data with Generalized Additive Mixed Models and extracting estimated marginal means from those models. Using the mgcv package you can create those models by including random effects in two ways:

1. Using the gam function with the bs="re".
2. With the gamm function using the random argument.

In the gam function case, the random effects are included in the reference grid as if they were fixed effects. In the gamm function case, the random effects aren´t included on the reference grid. 

Therefore, should the random effects be included on the reference grid? Are the random effects used to compute the estimated marginal means? 

The difference between how both functions take into account the random effects to compute estimated marginal means is just due to the fact that they are using random effects in different ways to compute the model, but conceptually they are both valid?

Thanks.

**Comment by rvlenth** [comment]
The `emmeans` interface for most models mostly covers the case where the random effects are marginalized out, as you describe for `gamm`. Then inferences for fixed effects apply to the whole population over which those random effects vary. Accordingly, I suspect that uou will find the SEs of estimates based on `gamm()` will be larger than those obtained by `gam()` after averaging over the random effects; because in the latter, we are *conditioning* on the particular random effects that you actually encountered. This is pretty much the same thing as viewing them as fixed effects.

As for what you "should" do, I will sidestep trying to answer that. It depends on the scope of the inferences you are making.

**Comment by rubeenmp** [comment]
Thanks for your time. Your answer has helped me a lot.
