### ISSUE TITLE
Different CIs using print() vs as.data.frame

### ISSUE THREAD

**Issue by timdisher** [rvlenth/emmeans#271]
Thank you for the great package! I am noticing that when pairwise contrasts are calculated that  the confidence intervals are different depending on whether you are using print/summary vs as.data.frame on the emmeans object. Is there any sense which of these is the "correct" one or why there would be a difference? I think this might be because as.data.frame on the pairwise object does bonferonni adjustment as if the emmeans and contrast list elements were all one object? Not sure if this is intended behaviour but if so please feel free to close.

```
Oats.lmer <- lme4::lmer(yield ~ Variety + factor(nitro) + (1|Block/Variety),
                        data = nlme::Oats, subset = -c(1,2,3,5,8,13,21,34,55))

Oats.emm.n <- emmeans(Oats.lmer, "nitro")

# These CIs are the same both ways
Oats.emm.n
as.data.frame(Oats.emm.n)


Oats.emm.pairwise <- emmeans(Oats.lmer, pairwise ~ Variety, infer = c(TRUE, TRUE))

# These CIs are very different
Oats.emm.pairwise
as.data.frame(Oats.emm.pairwise)

# These are the same again
Oats.emm.pairwise
as.data.frame(summary(Oats.emm.pairwise))
```

**Comment by rvlenth** [comment]
Your `Oats.emm.n` is an object of class `emmGruid`, and your `Oats.emm.pairwise` is of class `emm_list`, which is a list of  `emmGrid` objects. Meanwhich, `as.data.frame()` is a generic function which has methods for all kinds of classes, including `emmGrid`, `emm_list`, and `data.frame`. Those methods all do different things. It turns out that the `as.data.frame` method for an `emm_list` calls `rbind` and then `as.data.frame`:
```r
> rbind(Oats.emm.pairwise)
 Variety     contrast                 emmean   SE   df lower.CL upper.CL t.ratio p.value
 Golden Rain .                        105.24 7.53 8.46     79.5    131.0 13.973  <.0001 
 Marvellous  .                        108.47 7.48 8.28     82.7    134.2 14.496  <.0001 
 Victory     .                         96.93 7.64 8.81     71.1    122.8 12.685  <.0001 
 .           Golden Rain - Marvellous  -3.23 6.55 9.56    -24.9     18.5 -0.493  1.0000 
 .           Golden Rain - Victory      8.31 6.71 9.80    -13.8     30.4  1.238  1.0000 
 .           Marvellous - Victory      11.54 6.67 9.80    -10.4     33.5  1.729  0.6904 

Results are averaged over some or all of the levels of: nitro 
Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 
Conf-level adjustment: bonferroni method for 6 estimates 
P value adjustment: bonferroni method for 6 tests
```
... and `as.data.frame()` on this essentially just strips off the annotations. But there are two (or in general potentially more) elements of this list in that are combined into one family, so it defaults to Boneffoni adjustment.
With `as.data.frame(summary(Oats.emm.pairwise))`, `the `summary()` result is a list of two `summary_emm` objects, which are actually an extension of `data.frame`, so the `as.data.frame` of this result uses the existing method `as.data.frame` method, which is not part of the **emmeans** package at all.

So I would say that you could regard this -- not as a bug -- but as a rich choice of ways to display the same results in data.frame format.

My (fairly strong) recommendation is to generally *avoid using `as.data.frame` at all*. If you use `summary`, `confint`, `test`, or `print`, you already obtain something that inherits from `data.frame`. So if you need to extract results, just use `summary`. For example, 
```r
> (CI <- confint(Oats.emm.pairwise)[[1]])
 Variety     emmean   SE   df lower.CL upper.CL
 Golden Rain  105.2 7.53 8.46     88.0      122
 Marvellous   108.5 7.48 8.28     91.3      126
 Victory       96.9 7.64 8.81     79.6      114

Results are averaged over the levels of: nitro 
Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 

> class(CI)
[1] "summary_emm" "data.frame" 

> plot(emmean ~ SE, data = CI)
```
![image](https://user-images.githubusercontent.com/26777519/114928927-c8b9c480-9df8-11eb-8d05-a6f7320615d3.png)

And what happens when you use `as.data.frame` is that you lose all the annotations (d.f. method, confidence level, etc.) that are important pieces of information. (The other thing that typically happens is that the remaining results are displayed in way more precision that is justified.)

**Comment by timdisher** [comment]
Thank you! This is a great explanation

**Comment by rvlenth** [comment]
Closing this issue as I think it's resolved.
