### ISSUE TITLE
Negative Confidence Intervals

### ISSUE THREAD

**Issue by delucalab** [rvlenth/emmeans#272]
I recently ran a linear mixed effects model (sample size upwards of 100) using the lme4 package after transforming data using log(1+x). Afterwards, I used emmeans to backtransform the data and get point estimates, confidence intervals, and contrasts. I noticed that some lower confidence intervals were negative which is theoretically impossible since the back transformed data is a proportion between 0 and 1. Any insight on why this may be? I was advised to generate bootstrapped confidence intervals to bypass this issue. Would that be a good approach?

In addition, is there a way to pull individual estimates so that I can plot them along with the means generated from the package?

**Comment by rvlenth** [comment]
I really have no idea what you did, since "using emmeans" could mean a lot of things, but it does not back-transform *data* since it works with models, not the data. There is no guarantee that confidence intervals will lie within the same range as the estimates, in fact they typically don't. 

There are a lot of moving parts with transformations. If you use `emmeans()` like this:
```r
mod <- lmer(log(y + 1) ~ ...)
emmeans(mod, ~ treatment, type = "response")
```
then what will happen is that the means and CIs will be computed on the log(y + 1) scale, then the means and endpoints will be back-transformed. For the log(y + 1) transformation, the inverse is exp(z) - 1, which will result in values between -1 and infinity. So the CIs are not guaranteed to be positive. If you use bootstrapping or simulation something with that transformation, it *still* could result in negative-going intervals.

I would also comment that this is a very unusual transformation to be using if the y values fall in [0, 1]. In fact, it is very nearly the same as the linear transformation z = 0.69 * y:
```r
> y = seq(0,1,by=.005)
> plot(log(y+1) ~ y, type = "l")
```
![image](https://user-images.githubusercontent.com/26777519/116431905-d1a19180-a80d-11eb-9630-45b573d0e487.png)

More typically, people use a logit or arcsin-sqrt transformation for such values. The latter works even with hard 0s and 1s in the data. Both of those are guaranteed to back-transform to the interval [0, 1]. See `? make.tran` and consider `type = "asin.sqrt"`

**Comment by delucalab** [comment]
Thank you so much! This is very helpful! I will try the asin.sqrt transformation. 

As an aside, this is likely quite a naive question, how can I go about pulling the individual estimates that make up the marginal mean? I want to be able to ultimately plot individual values, the marginal mean, and the confidence intervals.

**Comment by rvlenth** [comment]
There as a plot() and an as.data.frame() method. I have put a lot of effort into writing documentation and I invite you to read at least vignettes("basic", "emmeans"). There is also an index of vignette topics.

Sent from my iPad

On Apr 28, 2021, at 2:14 PM, delucalab ***@***.***> wrote:

﻿

Thank you so much! This is very helpful! I will try the asin.sqrt transformation.

As an aside, this is likely quite a naive question, how can I go about pulling the individual estimates that make up the marginal mean? I want to be able to ultimately plot individual values, the marginal mean, and the confidence intervals.

**Comment by delucalab** [comment]
Thank you! I had read some the vignettes and they were very helpful and saw how to plot the point estimates and confidence intervals as well as summarize data into a data frame. I just didn't come across how to extract the individual estimates that make up the group marginal mean but maybe I missed it as this is all new to me? Thanks again and I very much appreciate all the time you put into developing this really helpful package.

**Comment by rvlenth** [comment]
If you do dat <- summary(emmeans(...)), dat inherits from data.frame and you can use it as such.

Sent from my iPad

On Apr 28, 2021, at 5:00 PM, delucalab ***@***.***> wrote:

﻿

Thank you! I had read some the vignettes and they were very helpful and saw how to plot the point estimates and confidence intervals as well as summarize data into a data frame. I just didn't come across how to extract the individual estimates that make up the group marginal mean but maybe I missed it as this is all new to me? Thanks again and I very much appreciate all the time you put into developing this really helpful package.

**Comment by rvlenth** [comment]
I think this issue is resolved, so am closing it.
