### ISSUE TITLE
Error with ref_grid function with clmm model

### ISSUE THREAD

**Issue by phaegeli** [rvlenth/emmeans#276]
I am writing you because I seem to have come across a potential bug in the ref_grid function of the emmeans package when working with a clmm model and trying to compute comparisons between exceedance probabilities.

Below you will find the R code that walks you through the data and the error with some comparisons to other models (polr, clm) where the function works as expected. 

I hope this information allows you to find the error. Please let me know if you have any questions or require additional information.  

Having this work properly would be tremendously helpful for us as it would allows us to do our complete analysis with the emmeans functions in a very consistent way.

Thanks for all your work on this packages. It have been an amazing help for making the results of our somewhat complicated models more tangible for our applied community. 

``` R

## ======================================== ##
## Demo of error message with grid function ##
## ======================================== ##

require(MASS)
require(ordinal)
require(emmeans)

## ---- LOADING DATA FILE ---- 
load(url("https://data.avalancheresearch.ca/EmmeansDataAndModels.RData"))

## ---- OVERVIEW OF DATA MODEL ---- 
str(ModelData)
## The dataframe consists of data from a survey that examined how
## users understand of advice in a warning report

## One of the dependent variables is participants rating of their 
## understanding of statements on an ordinal scale that ranges from
## Very difficult (VDiff) to Very easy (VEasy)
summary(ModelData$Under)

## We are modelling participants understanding rating as a function of their backgrounds and modifications we made to the statements.
## The modifications are included in the JargonExplN variable
summary(ModelData$JargonExplN)
## JargM = More jargon
## JargL = Less jargon
## NoExpl = No explanation
## Expl = Added explanation

## ---- ESTIMATING MODEL ---- 
## Since survey participants assessed mutiple statement, I needs to estimate the model as a mixed effects model. 
## But I am also estimating is with the polr function first to highlight the error
if (!exists("polr_fit")) polr_fit <- polr(Under ~ BackgrAvTraining*JargonExplN + TrvlAdv_AttenNum + BackgrYrsOfExp + BackgrDaysPerYrNum + BullUseType, data = ModelData)
if (!exists("clm_fit")) clm_fit <- clm(Under ~ BackgrAvTraining*JargonExplN + TrvlAdv_AttenNum + BackgrYrsOfExp + BackgrDaysPerYrNum + BullUseType, data = ModelData)
if (!exists("clmm_fit")) clmm_fit <- clmm(Under ~ BackgrAvTraining*JargonExplN + TrvlAdv_AttenNum + BackgrYrsOfExp + BackgrDaysPerYrNum + BullUseType + (1|Id) + (1|StatCode/VersionCode), data = ModelData)

## ---- COMPARISONS ----
## We are interested in specific comparisons and to make the results more tangible to 
## our readers, we would like to use probability of choosing 'Easy' or 'Very easy' to
## illustrate the results. This is the exceedance probability for the SWEasy|Easy cut.

## 1) To illustrate a case where it works as expected, I am using the polr_fit model first.
## POLR Model: Testing differences in more and less jargon per training level
grid_polr <- ref_grid(polr_fit, transform = "response", mode = "exc.prob", 
                 at = list(JargonExplN = c("JargM", "JargL"), 
                           cut = "SWEasy|Easy"))
emmeans(grid_polr, specs = pairwise ~ JargonExplN, by = "BackgrAvTraining")
## -> Desired outcome: Significant differences for participants with none or introductory training

## 2) Let's try to the clmm_fit model next.
## CLMM Model: Testing differences in more and less jargon per training level
grid_clmm1 <- ref_grid(clmm_fit, transform = "response", mode = "exc.prob", 
                 at = list(JargonExplN = c("JargM", "JargL"), 
                           cut = "SWEasy|Easy"))
## -> ERROR MESSAGE despite using the same settings as in the call with the polr model.
emmeans(grid_clmm1, specs = pairwise ~ JargonExplN, by = "BackgrAvTraining")

## But it works with the default for the mode parameter
grid_clmm2 <- ref_grid(clmm_fit, transform = "response", mode = "latent", 
                 at = list(JargonExplN = c("JargM", "JargL"), 
                           cut = "SWEasy|Easy"))
emmeans(grid_clmm2, specs = pairwise ~ JargonExplN, by = "BackgrAvTraining")
## -> So, I know that the differences are there, I am just not getting them in the
##    desired format

## cum.prob gives you the same error as exc.prob
grid_clmm3 <- ref_grid(clmm_fit, transform = "response", mode = "cum.prob", 
                 at = list(JargonExplN = c("JargM", "JargL"), 
                           cut = "SWEasy|Easy"))

## 3) Things work just fine with the CLM Model
## CLM Model: Testing differences in more and less jargon per training level
grid_clm <- ref_grid(clm_fit, transform = "response", mode = "exc.prob", 
                 at = list(JargonExplN = c("JargM", "JargL"), 
                           cut = "SWEasy|Easy"))
emmeans(grid_clm, specs = pairwise ~ JargonExplN, by = "BackgrAvTraining")
## -> Works again as expected

```

**Comment by rvlenth** [comment]
I will look at it. But may I suggest that when you submit future bug reports, you never re-use the same variable name?For example, the object 'grid' is defined at least 4 times, and there may be other duplicate names I didn't notice. This makes it very confusing to compare the results and to know what we are talking about at a given step.

Sent from my iPad

On May 4, 2021, at 6:36 PM, phaegeli ***@***.***> wrote:

﻿

I am writing you because I seem to have come across a potential bug in the ref_grid function of the emmeans package with working with an clmm model and trying to compute comparisons between exceedance probabilities.

Below you will find the R code walks you through the data and the error with some comparisons to other models (polr, clm) where the function works as expected.

I hope this information allows you to find the error. Please let me know if you have any questions or require additional information.

Having this work properly would be tremendously helpful for us as it would allows us to do our complete analysis with the emmeans functions in a very consistent way.

Thanks for all your work on this packages. It have been an amazing help for making the results of our somewhat complicated models more tangible for our applied community.

## ======================================== ##
## Demo of error message with grid function ##
## ======================================== ##

require(MASS)
require(ordinal)
require(emmeans)

## ---- LOADING DATA FILE ----
load(url("https://data.avalancheresearch.ca/EmmeansDataAndModels.RData"))

## ---- OVERVIEW OF DATA MODEL ----
str(ModelData)
## The dataframe consists of data from a survey that examined how
## users understand of advice in a warning report

## One of the dependent variables is participants rating of their
## understanding of statements on an ordinal scale that ranges from
## Very difficult (VDiff) to Very easy (VEasy)
summary(ModelData$Under)

## We are modelling participants understanding rating as a function of their backgrounds and modifications we made to the statements.
## The modifications are included in the JargonExplN variable
summary(ModelData$JargonExplN)
## JargM = More jargon
## JargL = Less jargon
## NoExpl = No explanation
## Expl = Added explanation

## ---- ESTIMATING MODEL ----
## Since survey participants assessed mutiple statement, I needs to estimate the model as a mixed effects model.
## But I am also estimating is with the polr function first to highlight the error
if (!exists("polr_fit")) polr_fit <- polr(Under ~ BackgrAvTraining*JargonExplN + TrvlAdv_AttenNum + BackgrYrsOfExp + BackgrDaysPerYrNum + BullUseType, data = ModelData)
if (!exists("clm_fit")) clm_fit <- clm(Under ~ BackgrAvTraining*JargonExplN + TrvlAdv_AttenNum + BackgrYrsOfExp + BackgrDaysPerYrNum + BullUseType, data = ModelData)
if (!exists("clmm_fit")) clmm_fit <- clmm(Under ~ BackgrAvTraining*JargonExplN + TrvlAdv_AttenNum + BackgrYrsOfExp + BackgrDaysPerYrNum + BullUseType + (1|Id) + (1|StatCode/VersionCode), data = ModelData)

## ---- COMPARISONS ----
## We are interested in specific comparisons and to make the results more tangible to
## our readers, we would like to use probability of choosing 'Easy' or 'Very easy' to
## illustrate the results. This is the exceedance probability for the SWEasy|Easy cut.

## 1) To illustrate a case where it works as expected, I am using the polr_fit model first.
## POLR Model: Testing differences in more and less jargon per training level
grid <- ref_grid(polr_fit, transform = "response", mode = "exc.prob",
                 at = list(JargonExplN = c("JargM", "JargL"),
                           BackgrAvTraining = c("None", "Intro", "Adv", 'Prof'),
                           cut = "SWEasy|Easy"))
emmeans(grid, specs = pairwise ~ JargonExplN, by = "BackgrAvTraining")
## -> Desired outcome: Significant differences for participants with none or introductory training

## 2) Let's try to the clmm_fit model next.
## CLMM Model: Testing differences in more and less jargon per training level
grid <- ref_grid(clmm_fit, transform = "response", mode = "exc.prob",
                 at = list(JargonExplN = c("JargM", "JargL"),
                           BackgrAvTraining = c("None", "Intro", "Adv", 'Prof'),
                           cut = "SWEasy|Easy"))
## -> ERROR MESSAGE despite using the same settings as in the call with the polr model.
emmeans(grid, specs = pairwise ~ JargonExplN, by = "BackgrAvTraining")

## But it works with the default for the mode parameter
grid <- ref_grid(clmm_fit, transform = "response", mode = "latent",
                 at = list(JargonExplN = c("JargM", "JargL"),
                           BackgrAvTraining = c("None", "Intro", "Adv", 'Prof'),
                           cut = "SWEasy|Easy"))
emmeans(grid, specs = pairwise ~ JargonExplN, by = "BackgrAvTraining")
## -> So I know that the differences are there, I am just not getting them in the
##    desired format

## cum.prob gives you the same error as exc.prob
grid <- ref_grid(clmm_fit, transform = "response", mode = "cum.prob",
                 at = list(JargonExplN = c("JargM", "JargL"),
                           BackgrAvTraining = c("None", "Intro", "Adv", 'Prof'),
                           cut = "SWEasy|Easy"))

## 3) Things work just fine with the CLM Model
## CLM Model: Testing differences in more and less jargon per training level
grid <- ref_grid(clm_fit, transform = "response", mode = "exc.prob",
                 at = list(JargonExplN = c("JargM", "JargL"),
                           BackgrAvTraining = c("None", "Intro", "Adv", 'Prof'),
                           cut = "SWEasy|Easy"))
emmeans(grid, specs = pairwise ~ JargonExplN, by = "BackgrAvTraining")
## -> Works again as expected

**Comment by phaegeli** [comment]
Thanks, Russell! I have updated the code, and there should not be any duplicate names anymore.

**Comment by rvlenth** [comment]
You did not say what the error message was, so here it is:
```r
> ref_grid(clmm_fit, transform = "response", mode = "exc.prob", 
+          at = list(JargonExplN = c("JargM", "JargL"), 
+                    cut = "SWEasy|Easy"))
 Error in ref_grid(clmm_fit, transform = "response", mode = "exc.prob",  : 
  Reference grid is empty due to mismatched levels in 'at' 
```

This is what I get if I take the `at` part out:
```r
> bigRG = ref_grid(clmm_fit, transform = "response", mode = "exc.prob")
> bigRG
'emmGrid' object with variables:
    BackgrAvTraining = None, Intro, Adv, Prof
    JargonExplN = JargM, JargL, NoExpl, Expl
    TrvlAdv_AttenNum = 2.4342
    BackgrYrsOfExp = First year, 2-5 yrs, 6-10 yrs, 11-20 yrs, 20+ yrs
    BackgrDaysPerYrNum = 3.4415
    BullUseType = A, B, C, D, E, F
    cut = multivariate response levels: 1|2, 2|3, 3|4, 4|5, 5|6
```
Note that there is no level of `cut` that is equal to `"SWEasy|Easy"` - which explains the error message. apparently, you have a stale version of your `clmm_fit` object. I tried re-fitting the model to verify this, but I ran out of patience as this is a monster of a data set and model.

Anyway, I am confident that the issue report is not due to a bug in `emmeans`.

**Comment by phaegeli** [comment]
Thank you very much for helping me out with this. Much appreciated!
