### ISSUE TITLE
remove `plyr` dependency 

### ISSUE THREAD

**Issue by elong0527** [rvlenth/emmeans#298]
`plyr` is retired. Is it possible to remove the dependency?

**Comment by rvlenth** [comment]
I am trying to understand your concern. The package uses the functions `plyr::aaply`, `plyr::alply` and `plyr::id` in various places, where there is a need for a capability similar to `base::apply` but with a multidimensional array. These functions serve that purpose very nicely.

Here is some context regarding dependency issues:
```r
> tools::package_dependencies(c("emmeans", "plyr", "dplyr", "purrr"), recursive = TRUE)
$emmeans
 [1] "estimability" "graphics"     "methods"      "numDeriv"     "stats"        "utils"       
 [7] "plyr"         "mvtnorm"      "xtable"       "Rcpp"        

$plyr
[1] "Rcpp"    "methods" "utils"  

$dplyr
 [1] "ellipsis"   "generics"   "glue"       "lifecycle"  "magrittr"   "methods"    "R6"        
 [8] "rlang"      "tibble"     "tidyselect" "utils"      "vctrs"      "pillar"     "cli"       
[15] "crayon"     "fansi"      "utf8"       "pkgconfig"  "purrr"      "grDevices" 

$purrr
[1] "magrittr" "rlang"    "utils"   

> tools::package_dependencies("plyr", reverse = TRUE)
$plyr
  [1] "abbyyR"                    "abctools"                  "acc"                      
     . . . (rows omitted) . . .
[706] "zdeskR"                    "zebu"                      "zoon"                     
[709] "zTree"

> package_dependencies("plyr", reverse = TRUE, recursive=TRUE)
$plyr
   [1] "abbyyR"                    "abctools"                  "acc"  
     . . . (rows omitted) . . .
[1000] "ggsn"                     
 [ reached getOption("max.print") -- omitted 988 entries ]
```
Since there are over 700 packages that directly depend on or import **plyr** (and nearly 2000 if we count indirect cases), I think it is here for the long term; and even if I were to remove **plyr** as an import, there's a very good chance you would still need it installed to support some other packages you use.  

From the README file in the [CRAN page](https://cran.r-project.org/package=plyr), we have:

> plyr is retired: this means only changes necessary to keep it on CRAN will be made. 
> We recommend using dplyr (for data frames) or purrr (for lists) instead.

There is no expression of a plan to deprecate the package, just that no further development will be made; indeed, it expresses an intent to keep in on CRAN.

It is not clear from quick review what functions in **dplyr** or **purrr** could be used as substitutes for `aaply` or `alply`, but even if found, using either of them in place of **plyr** would *increase* the number of dependencies in **emmeans** (we don't need **magrittr** or **rlang**, and **methods** is already needed for other reasons).

So I just don't see why dependency on **plyr** is a problem. If you disagree, please explain.

**Comment by elong0527** [comment]
Thanks for the clarification. Removing `plyr` is just a recommendation. 

This is identified while we try to qualify `emmeans` for regulatory purpose. 

It could be challenge to justify the criteria to qualify a retired package like `plyr`.  

In `purrr`, my understanding is that `array` needs to be converted to `list` before using other functions.

**Comment by rvlenth** [comment]
I posted a question to the package-developers discussion list, so maybe I'll get more insight.

I already have working code, so I am reluctant to risk messing it up. It is not clear that their use of "retired" is anything except loose (and apparently misleading) language, and maybe the best solution would be to get the **plyr** developers to change how they describe its status. 

What do *you* think "retired" means, in the eyes of your regulators? And is it consistent with a package that has over 700 direct reverse dependencies?

**Comment by elong0527** [comment]
By reading the tidyverse lifecycle page, it seems "Superseded" is a proper term. 

https://lifecycle.r-lib.org/articles/stages.html#superseded

From [R-FDA](https://www.r-project.org/doc/R-FDA.pdf) document, my understanding of a retired package is "No further development, bug fixes or patches are made available for the retired versions.". So it could be a red flag from qualification perspective. 

I share the pain to modify working code. Alternatively, we can argue from the package dependency perspective. In other words, if the usage of `plyr` in `emmeans` has been properly tested, we shall be fine. (by checking the code coverage report)

**Comment by rvlenth** [comment]
I'm pretty close to getting this resolved, using `base::apply()` in place of `plyr::aaply()`. With vector margins, it doesn't necessarily come out in the same form, but I have resolved all those except for the one situation where I use `plyr::aaply(..., .drop = FALSE)` which isn't supported by `apply()` except maybe I can hack my way through somehow using `simplify = FALSE`. That affects only the case with `emmeans(..., weights = "outer")`.

Soon, I will commit the interim version anyway, which has no **plyr** dependence. And then (on another PC) will do something to fix outer weights.

**Comment by rvlenth** [comment]
With the latest commit, everything seems to be in order. So the next CRAN update of **emmeans**, coming fairly soon, will no longer depend on **plyr**. All in all, that is a good change. I'll close this as it's resolved, but that does nor prevent comments or reopening if you deem it unfinished.
