### ISSUE TITLE
Error in .est.se.df when using GAMLSS models

### ISSUE THREAD

**Issue by DInfanger** [rvlenth/emmeans#323]
The version 1.7.1-1 of emmeans produces an error when using a GAMLSS (v. 5.3-4) model. Re-installing version 1.7.0, the code works fine without errors.

I could track the error to the function `.est.se.df` when it is assigning names to the `result` data frame. Here is a reproducible example:

```r
library(emmeans)
library(gamlss)

mtcars$cyl <- factor(mtcars$cyl)

cars_mod <- gamlss(mpg ~ cyl + disp, data = mtcars, dist = NO)

emmeans(cars_mod, "cyl")
Error in names(result) <- c(misc$estName, "SE", "df") : 
  'names' attribute [3] must be the same length as the vector [2]
```

**Comment by rvlenth** [comment]
OK, what I've found is this:
```r
> EMM <- emmeans(cars_mod, "cyl")
> EMM@dfargs
$df
logical(0)
```
... which in turn is a result of a change I made in the code for `glm` models (from which `gamlss` inherits) to show `df.residual(object)` instead of `Inf` when the family is "gaussian" or "gamma". (see the NEWS file). In turn, this is because `gamlss` objects do not in fact fully inherit from `glm`. Note:
```r
> family(cars_mod)
[1] "NO"     "Normal"

> mod_glm <- glm(mpg ~ cyl + disp, data = mtcars)
> family(mod_glm)

Family: gaussian 
Link function: identity 
```
So we have a `character` object where I am expecting a `family` object. This will require a hack of some sort in the support code for `gamlss` objects. 

What I decided to do is add a hack to make it pretend it's gaussian if the first element of `$family` is "NO" or "GA", so it'll use `df.residual` in those cases. So with that change, we get
```r
> emmeans(cars_mod, "cyl")
 cyl emmean   SE df lower.CL upper.CL
 4     23.2 1.50 27     20.2     26.3
 6     18.4 1.14 27     16.1     20.8
 8     18.4 1.42 27     15.5     21.4

Confidence level used: 0.95 
```
... whereas in earlier versions we got `Inf` d.f. for the CIs. From your perspective, are there other gamlss families where we should honor the d.f.? (I'll ask the developer too)

**Comment by DInfanger** [comment]
Thank you for looking into this.

> From your perspective, are there other gamlss families where we should honor the d.f.?

Not that I can think of at the moment (but I'm not sure if I'm the best person to ask). I'm interested in what the developer(s) have to say. What I find a little confusing is that the `summary` function from GAMLSS uses the _t_-distribution for all its Wald tests, even for models such as logistic regressions.

**Comment by rvlenth** [comment]
I decided not to ask the developer. I looked at `summary.gamlss` and see that often they use d.f. where many of the rest of us would not. So I looked through the available families and settled on a somewhat expanded list:
```
c("BCCG", "BCPE", "BCT", "GA", "GT", "NO", "NOF", "TF")
```
-- but also restrict its use to the "mu" part of the model. For example:
```
> GA_mod = gamlss(mpg ~ cyl + disp, data = mtcars, fam = GA())
GAMLSS-RS iteration 1: Global Deviance = 150.0223 
GAMLSS-RS iteration 2: Global Deviance = 150.0223 

> emmeans(GA_mod, "cyl")
 cyl emmean     SE df lower.CL upper.CL
 4     3.09 0.1104 27     2.86     3.31
 6     2.91 0.0606 27     2.79     3.04
 8     2.90 0.1114 27     2.67     3.13

Results are given on the log (not the response) scale. 
Confidence level used: 0.95 

> emmeans(GA_mod, "1", what = "sigma")
 1       emmean    SE  df asymp.LCL asymp.UCL
 overall  -2.04 0.222 Inf     -2.47      -1.6

Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
```
Note that we have 27 d.f. for the mu part of the model but Inf for the sigma part. 

It is easy enough to override the d.f.
```
> emmeans(GA_mod, "cyl", df = Inf)
 cyl emmean     SE  df asymp.LCL asymp.UCL
 4     3.09 0.1104 Inf      2.87      3.30
 6     2.91 0.0606 Inf      2.79      3.03
 8     2.90 0.1114 Inf      2.68      3.12

Degrees-of-freedom method: user-specified 
Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
```

**Comment by rvlenth** [comment]
I think this is resolved now, so closing.
