### ISSUE TITLE
[Feature proposal] emmeans for: geeM and wgeesel (and maybe CRTgeeDR)

### ISSUE THREAD

**Issue by hugesingleton** [rvlenth/emmeans#341]
The list of models supported by emmeans is impressive. There are both gee and geepack on it. Yet there are packages offering additional features, like [wgeesel ](https://cran.r-project.org/web/packages/wgeesel) (GEE for data MAR via IPW or double robust GEE via [CRTgeeDR](https://cran.r-project.org/web/packages/CRTgeeDR/index.html) ), or [geeM ](https://cran.r-project.org/web/packages/geeM) (fast, no external dependencies).

It would be great, if they were supported by the emmeans, especially the joint_tests, as neither of them give type-3 (or even type 1) Wald's assessment of main and interaction effects :(

PS: maybe the [mmmgee](https://cran.r-project.org/web/packages/mmmgee/) package will give you some useful ideas, just in case.

**Comment by rvlenth** [comment]
For your own use, the best approach at least initially is to try to use qdrg() – sometimes, but seldom, the simplest interface works (providing the object argument). Usually, you need to provide most of the rest of the arguments instead.

Please keep in mind that unresponsive developers are a big problem for me too, in trying to support their stuff!

Russ

From: hugesingleton ***@***.***>
Sent: Tuesday, March 29, 2022 11:20 AM
To: rvlenth/emmeans ***@***.***>
Cc: Lenth, Russell V ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [rvlenth/emmeans] [Feature proposal] emmeans for: geeM and wgeesel (and maybe CRTgeeDR) (Issue #341)


I see. The problem is they often either don't respond or rarely update the packages. But I will notice. Maybe better I will go through the documentation you mentioned and try to implement it on my own, as I doubt they agree.

**Comment by hugesingleton** [comment]
Just to make sure - if I re-create (with new names, matching the package name) all the functions for "gee" here [helpers.r](https://github.com/rvlenth/emmeans/blob/f8c454d44fe0de8e71b6fdbf1626b87347b9353a/R/helpers.R) will it suffice?

OK, I tried this (data comes from this issue: https://github.com/rvlenth/emmeans/issues/339)

m_geem <- geem(SucN ~ Time, family=binomial(link = "logit"), data=d, id=ID, corstr = "exchangeable", sandwich = TRUE)
summary(m_geem)


mq <- qdrg(formula=SucN ~ Time, data=d, coef = coef(m_geem), vcov = as.matrix(m_geem $var), df = Inf)
> joint_tests (mq)
 model term df1 df2 F.ratio p.value
 Time         3 Inf   2.176  0.0886

> emmeans(mq, specs = ~Time)
 Time emmean    SE  df asymp.LCL asymp.UCL
 M0   -2.197 1.054 Inf     -4.26    -0.131
 M1   -0.847 0.690 Inf     -2.20     0.505
 M2    0.405 0.645 Inf     -0.86     1.671
 M3    0.847 0.690 Inf     -0.51     2.200

Confidence level used: 0.95 

And it agrees with geeglm:

> m_geepack <- geeglm(SucN ~ Time, family=binomial(link = "logit"), data=d, id=ID, corstr = "exchangeable", std.err="san.se")
> joint_tests(m_geepack)
 model term df1 df2 F.ratio p.value
 Time         3 Inf   2.176  0.0886

> emmeans(m_geepack, specs = ~Time)
 Time emmean    SE  df asymp.LCL asymp.UCL
 M0   -2.197 1.054 Inf     -4.26    -0.131
 M1   -0.847 0.690 Inf     -2.20     0.505
 M2    0.405 0.645 Inf     -0.86     1.671
 M3    0.847 0.690 Inf     -0.51     2.200

Covariance estimate used: vbeta 
Results are given on the logit (not the response) scale. 
Confidence level used: 0.95

**Comment by rvlenth** [comment]
I think this issue is inactive and resolved, or referred to another, so am closing it.

**Comment by danielinteractive** [comment]
@hugesingleton Hi - I think we crossed paths before on Satterthwaite and related things :-) - can you share the code for `emmeans` interface for `geeM`? or maybe we can do a fork together of the repo etc. later as well?
Since I just came across the `geeM` package and it seems to give nice results - I just need the `emmeans` on top. (I tried tweaking the good old `gee` but it is not giving as good results I see.)

**Comment by rvlenth** [comment]
Looking back at some of the above stuff about joint_tests, I might mention that covariates get skipped over by `joint_tests()` unless you create the reference grid with two different covariate values - because it is impossible to estimate the effect of a covariate from a reference grid that has just one value for it. So in the above, you might consider:
```
m_wgee_q <- qdrg(formula=SucN ~ Time * Result, data=d, coef = m_wgee$beta, 
    vcov = m_wgee$var, df = Inf, at = list(Result = 3:4))
joint_tests(m_wgee_q)
```

**Comment by cg091** [comment]
I tried the solutions proposed above but couldn’t get them to run without errors. So I wrote my own code to perform GEE analysis with emmeans and geepack. The script loads the data, fits a GEE model with Wang-Long variance correction, runs joint tests, computes estimated marginal means, and performs pairwise and simple effects contrasts.

I’d appreciate any feedback on this approach or suggestions to improve or fix potential issues.

```
# Load required packages
library(emmeans)
library(geesmv)
library(geepack)
library(Matrix)

# 1. Load your new dataset
# Replace with your own filepath or data import method
df <- read.csv("path/to/your/new_dataset.csv")

# 2. Check and prepare variables: Assume your dataset has:
# - ID column for subjects (must be factor or character)
# - response variable (e.g. Duration or any continuous outcome)
# - factor1 and factor2 (two factors, categorical variables)

df$ID <- as.factor(df$ID)  # Ensure ID is factor
df$factor1 <- as.factor(df$factor1)  # First factor
df$factor2 <- as.factor(df$factor2)  # Second factor

# 3. Define formula for GEE
# Replace 'response_var' with your dependent variable
formula_obj <- response_var ~ factor1 * factor2

# 4. Fit initial GEE model with independence working correlation
initial_model <- geeglm(formula = formula_obj,
                        family = gaussian,
                        data = df,
                        id = df$ID,
                        corstr = "independence")

# 5. Get coefficients from the model
coef_est <- coef(initial_model)

# 6. Compute Wang-Long variance-covariance matrix with exchangeable correlation
vcov_matrix <- GEE.var.wl(
  formula = formula_obj,
  id = df$ID,
  family = gaussian,
  data = df,
  corstr = 'exchangeable'
)

vcov_beta <- vcov_matrix$cov.beta

# 7. Add small epsilon to diagonal if needed for positive definiteness
epsilon <- 1e-8
if (any(eigen(vcov_beta, symmetric = TRUE)$values <= 0)) {
  vcov_beta <- vcov_beta + diag(epsilon, nrow(vcov_beta))
}

# 8. Create qdrg object using the corrected vcov matrix
qdrg_obj <- qdrg(formula = formula_obj,
                 data = df,
                 coef = coef_est,
                 vcov = vcov_beta,
                 df = Inf)

# 9. Run joint tests for overall factor effects
joint_test_results <- joint_tests(qdrg_obj)
print(joint_test_results)

# 10. Get emmeans for main effects and interaction
emmeans_factor1 <- emmeans(qdrg_obj, ~ factor1)
emmeans_factor2 <- emmeans(qdrg_obj, ~ factor2)
emmeans_interaction <- emmeans(qdrg_obj, ~ factor1 * factor2)

# 11. Pairwise comparisons
pairwise_factor1 <- pairs(emmeans_factor1)
pairwise_factor2 <- pairs(emmeans_factor2)
pairwise_interaction <- pairs(emmeans_interaction)

# 12. Simple effects if desired
simple_factor1_by_factor2 <- pairs(emmeans(qdrg_obj, ~ factor1 | factor2))
simple_factor2_by_factor1 <- pairs(emmeans(qdrg_obj, ~ factor2 | factor1))

# 13. Custom contrasts example:
# Define contrasts over factor1 levels within each factor2 level
# Adjust vectors based on number of levels in factor1

emmeans_for_contrasts <- emmeans(qdrg_obj, ~ factor1 | factor2)

# Example: contrast first vs last level of factor1
custom_contrast <- contrast(emmeans_for_contrasts,
                            list("Last vs First" = c(-1, rep(0, length(levels(df$factor1)) - 2), 1)))

print(custom_contrast)

# 14. Plot interaction means with confidence intervals
emmip_plot <- emmip(qdrg_obj, factor2 ~ factor1,
                   CIs = TRUE,
                   style = "factor")
print(emmip_plot)
`
```
