### ISSUE TITLE
Issue with missing data (`NA`) in `recover_data()`

### ISSUE THREAD

**Issue by mattansb** [rvlenth/emmeans#342]
This is an example from `lavaan`:

``` r
library(semTools)
library(lavaan)
library(emmeans)

# Make some missing data
set.seed(30)
data("mtcars")
mtcars <- mice::ampute(mtcars)$amp

model <- "
  mpg ~ hp + drat + hp:drat
"

fit <- sem(model, mtcars, missing = "fiml.x")
```

This works fine:

``` r
emmeans(fit, ~ hp + drat, lavaan.DV = "mpg",
        at = list(hp = c(90, 100),
                  drat = 0))
#>   hp drat emmean   SE  df asymp.LCL asymp.UCL
#>   90    0   4.20 5.22 Inf     -6.04      14.4
#>  100    0   4.15 4.83 Inf     -5.32      13.6
#> 
#> Confidence level used: 0.95
```

However, because there are missing values in recover data,

``` r
recover_data(fit, lavaan.DV = "mpg")
#> Warning in format.data.frame(if (omit) x[seq_len(n0), , drop = FALSE] else x, :
#> corrupt data frame: columns will be truncated or padded with NAs
#>     hp drat
#> 1  110 3.90
#> 2  110 3.90
#> 3   93 3.85
#> 4  110 3.08
#> 5  175 3.15
#> 6  105 2.76
#> 7  245 3.21
#> 8   62 3.69
#> 9   95 3.92
#> 10 123 3.92
#> 11 123 3.92
#> 12 180 3.07
#> 13 180 3.07
#> 14 180 3.07
#> 15 205 2.93
#> 17 215 3.00
#> 18 230 3.23
#> 19  66 4.08
#> 20  52 4.93
#> 21  65 4.22
#> 22  97 3.70
#> 23 150 2.76
#> 27 150 3.15
#> 28 245   NA
#> 29  NA 3.08
#> 30  66   NA
#> 31  91 4.43
```

`cov.reduce` seems to fail:

``` r
ref_grid(fit, lavaan.DV = "mpg")
#> 'emmGrid' object with variables:
#>     hp = NA
#>     drat = NA
```

As does `emtrends()`:

``` r
emtrends(fit, ~ hp, "drat",
         lavaan.DV = "mpg",)
#> Error in if (delta.var == 0) stop("Provide a nonzero value of 'delta.var'"): missing value where TRUE/FALSE needed
```

<sup>Created on 2022-03-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rvlenth** [comment]
It is hard to know what is right here. For example, suppose I fit the same model to the same data using `lm`:
```r
> lmfit = lm(mpg ~ hp + drat + hp:drat, mtcars)
> ref_grid(lmfit)
'emmGrid' object with variables:
    hp = 143.85
    drat = 3.5959
```
So note that `recover_data.lm` does not return a data set with missing values. 

Also, I can do:
```r
> ref_grid(fit, lavaan.DV = "mpg", cov.reduce = function(x) mean(x, na.rm = TRUE))
'emmGrid' object with variables:
    hp = 147
    drat = 3.576
```
So my questions back to you are:

  * *Should* the **emmeans** package architecture be expected to handle a recovered dataset that contains missing values?
  *  The `recover_data` method for this model class is in the **semTools** package, and as I understand it, this package, combined with **lavaan**, provides the machinery needed to deal with those missing values. Shouldn't the `recover_data.lavaan` method handle those missing values in some appropriate way related to those methods, e.g., replace the `NA`s with imputed values or something? Surely we can't expect the **emmeans** package itself to figure out what is best to do with them. (I think that's my answer to the first question.)
 
This really looks like something that is in @simsem's wheelhouse, not mine.

**Comment by mattansb** [comment]
Hi Russell,

I'm actually the one who implemented the `emmeans` methods in `semTools` 😅

I see your point though - I wonder if having imputed data returned by `recover_data` is the right way to go.
Perhaps it would be best to add a warning when missing values are detected in the recovered data, along the lines:

```
Warning message:
Data used on modeling contains missing values.
  Concider setting the `at = ` argument explicitly 
  or pass a function(s) that deals with missing values to
  the `cov.reduce = ` argument. 
```

**Comment by rvlenth** [comment]
This issue has caused me to consider a few issues. In my mind, there are two distinct cases that should be treated differently:

  1. The user provides a `data` argument, thus the `recover_data` method is not really deployed
  2. No `data` argument is provided, thus the `recover_data` method does try to get the original data.

These are distinct situations because if there are `NA`s in case (1), it is the user's doing; while in (2), the user is not responsible; the responsibility for handling `NA`s lies with whoever wrote the `recover_data` method.

After thinking about this, I decided I should trap `NA`s in case (1), but insist that it is the package developer's job to do that in case (2). Interestingly, I found that I had already done this in code I wrote a long time ago:
```r
    else { ### tbl (which is initialized as data) is non-NULL
        tbl = tbl[, vars, drop = FALSE] # consider only the variables actually needed
        tbl = tbl[complete.cases(tbl), , drop=FALSE]
    }
```
(lines 224-227 of `interfacing.R` in **emmeans** version 1.7.3)

For the above reason and others, I actually *disagree* with your choice to issue a warning message if there are `NA`s, because if it can fit the model with those `NA`s present, it is decidedly not the user's problem if it doesn't work. This is especially true because it seems that gracefully handling `NA`s appears to be a central purpose of the model-fitting algorithm. (BTW, if you keep the warning message, please spell "consider" correctly.)

I think I am right in insisting that `recover_data` methods return complete cases, no `NA`s. I can't test your example because I get an error that seems to come from not anticipating handling non-estimable cases (note: I sure hope you created a non-trivial `nbasis` slot). But I believe if your `recover_data` method excludes `NA`s in some way, the errors you observed will not occur. (Try the same call for `rg`, but add `data = d`)

**Comment by mattansb** [comment]
In the posted example, the user is using a FIML method, so I think it would only make sense for the follow-up analysis to also use the full information (and not only the complete observations). 
(Can think of extreme cases where there is only a small percentage of complete cases.)

Can you elaborate more on the `nbasis` slot? I have left it equivalent to `matrix(NA)` (and it multivariate counterpart).
What exactly is expected there if there is missing data but is used by the model fully?

**Comment by rvlenth** [comment]
Well, then I guess you can expect errors to occur in similar cases for future users of your software.

I'll answer on the basis issue separately.

Sent from my iPad

On Apr 1, 2022, at 5:43 AM, Mattan S. Ben-Shachar ***@***.***> wrote:

﻿

In the posted example, the user is using a FIML method, so I think it would only make sense for the follow-up analysis to also use the full information (and not only the complete observations).
(Can think of extreme cases where there is only a small percentage of complete cases.)

Can you elaborate more on the nbasis slot? I have left it equivalent to matrix(NA) (and it multivariate counterpart).
What exactly is expected there if there is missing data but is used by the model fully?

**Comment by rvlenth** [comment]
Looking more closely, I in fact don't see evidence of rank deficiency in your example, so the errors I had were due to something else and are not related to use of `nbasis`.

**Comment by rvlenth** [comment]
More specifically regarding your argument that there could be only a small number of complete cases, please understand that what `ref_grid` needs from `recover_data` is:

  * The levels of factors used in the model
  * Information on how to weight the various factor combinations
  * Information on how to reduce covariates, usually to a single value or to a range of values

So `recover_data` does not need to return a faithful rendition of the original data, it just needs something that is useful for the above purposes. It should consist of complete cases that accomplish the above goals.

**Comment by rvlenth** [comment]
I'm closing this as I think it is resolved.
