### ISSUE TITLE
[Question] Confidence interval with multinom

### ISSUE THREAD

**Issue by Eun-San-Kim** [rvlenth/emmeans#354]
Dear Russ,

I'm using ```emmeans``` with ```multinomial``` regression. With the help from several materials, I managed to use ```emmeans ``` with ```multinom``` function from ```nnet``` package.

However, I faced some problems. The confidence interval overlapped zero, which seems unappropriate with probability. As far as I know, it can be solved in ```glm``` function with ```type = "unlink"```, as confidence interval is calculated with logit form, then transformed. However, the results don't change with any type of type option.

I'm using ```brithwt``` data from ```MASS``` package. Also, 

```
library(MASS)
library(nnet)
example(birthwt)
````
I intentionally used 100 samples of ```bwt``` data, to make sample smaller, and confidence interval wider
```
test_model <- multinom(race ~ smoke, bwt[1:100, ])
```

```
emmeans(test_model, ~ race + smoke)

 race  smoke  prob     SE df lower.CL upper.CL
 white FALSE 0.393 0.0625  4  0.21978    0.567
 black FALSE 0.148 0.0454  4  0.02147    0.274
 other FALSE 0.459 0.0638  4  0.28187    0.636
 white  TRUE 0.718 0.0721  4  0.51789    0.918
 black  TRUE 0.103 0.0486  4 -0.03232    0.237
 other  TRUE 0.179 0.0615  4  0.00887    0.350
```

With unlink and response option, the results stayed the same.
```
emmeans(test_model, ~ race + smoke, type = "unlink")
emmeans(test_model, ~ race + smoke, type = "response")
```

As an alternative, I used ```transform = "logit"``` option, then used ```type = "response"``` type option. The results seem reasonable, but I can't figure out the process clearly. Is this right way to use ```multinom``` with ```nnet```?

```
emmeans(test_model, ~ race + smoke, transform = "logit", type = "response")

 race  smoke response     SE df lower.CL upper.CL
 white FALSE    0.393 0.0625  4   0.2386    0.573
 black FALSE    0.148 0.0454  4   0.0597    0.320
 other FALSE    0.459 0.0638  4   0.2937    0.634
 white  TRUE    0.718 0.0721  4   0.4866    0.872
 black  TRUE    0.103 0.0486  4   0.0257    0.331
 other  TRUE    0.179 0.0615  4   0.0643    0.411
```

**Comment by rvlenth** [comment]
The last thing you did, in smaller steps, is this:
```
EMM <- emmeans(test_model, ~ race + smoke)
logitEMM <- regrid(EMM, transform = "logit")
confint(logitEMM, type = "response")
```
The second step transforms the probabilities to the logit scale, using the delta method to obtain their standard errors (see the documentation for `regrid`). The third step computes the CIs on the logit scale, and then back-transforms them to the original scale. So the CIs are reasonable on the logit scale, and are guaranteed to be in the interval (0,1) when back-transformed. The most important difference is that the resulting CIs will not be symmetric about their estimate (unless the estimate is 0.5 (or 0 on the logit scale). You can see what the intervals are on the logit scale by omitting the `type = "response"` argument.

A note: in the last couple of versions of **emmeans**, I changed the arguments to the `ref_grid()` function (*not* to `regrid()`) and recommend using 
```
emmeans(test_model, ~ race + smoke, regrid = "logit", type = "response")
```
that is, specify `regrid` instead of `transform`. (Using `transform` still works for sake of backward compatibility.) The reason I changed this is because there is also a possibility that a user will specify `tran` (see `update.emmGrid()`) andthat actually has the opposite effect that `transform` does, which was kinda confusing.

**Comment by Eun-San-Kim** [comment]
Thanks a lot!
