### ISSUE TITLE
New bug in 1.8.0: emmeans fails when SE and estimate is NA or NaN

### ISSUE THREAD

**Issue by strengejacke** [rvlenth/emmeans#364]
This example worked fine with emmeans 1.7.4-1

```r
library(emmeans)
data(iris)
fit <- lm(Sepal.Width ~ log(Petal.Width), data = iris)

emmeans(fit,
  specs = "Petal.Width",
  at = list(Petal.Width = c(0, 5, 10))
)
```

It returned `Inf` as predicted value for `Petal.Width=0` due to the `log()` transformation. However, since the recent update, emmeans failed with following error:

```
  Error in `if (rtn < 0) {
      warning("Negative variance estimate obtained!")
      rtn = NaN
  }`: missing value where TRUE/FALSE needed
```

**Comment by rvlenth** [comment]
Well, drat. This is an example of "no good deed goes unpunished." This stems from issue #359 where I thought it would be kind to add a more informative error message.

I guess I will see how often this bug is noticed before I decide whether I need to ask CRAN to accept an emergency update. Thanks for reporting this.

For what it's worth, here is a patch to work around this bug:
```r
assignInNamespace(".qf.non0", function(X, y) {
    ii = (zapsmall(y) != 0)
    rtn = if (any(ii))
        sum(y[ii] * (X[ii, ii, drop = FALSE] %*% y[ii]))
    else 0
    if (!is.na(rtn) && (rtn < 0)) {
        warning("Negative variance estimate obtained!")
        rtn = NaN
    }
    rtn
}, 
"emmeans")
```

**Comment by rvlenth** [comment]
Note -- I changed the title of this issue so other users who experience the same issue are more likely to notice it.

**Comment by rvlenth** [comment]
I think this issue is resolved, so am closing
