### ISSUE TITLE
New bug in 1.8.0 - errors with MGCV

### ISSUE THREAD

**Issue by mattansb** [rvlenth/emmeans#365]
I'm getting the following error with the new version of emmeans.

``` r
d <- tibble::tribble(
  ~ID,  ~DV,     ~X,        ~g,
  "701", 0.23,      1,    "fast",
  "701",    0,      1,    "slow",
  "701", 0.25,      2,    "fast",
  "701", 0.37,      2,    "slow",
  "701", 0.17,      3,    "fast",
  "701", 0.16,      3,    "slow",
  "701", 0.35,      4,    "fast",
  "701", 0.28,      5,    "fast",
  "701", 0.43,      5,    "slow",
  "703", 0.35,      1,    "fast",
  "703", 0.44,      2,    "fast",
  "703", 0.19,      2,    "slow",
  "703", 0.37,      3,    "fast",
  "703", 0.28,      3,    "slow",
  "703", 0.25,      4,    "fast",
  "703", 0.61,      4,    "slow",
  "703", 0.24,      5,    "fast",
  "703", 0.09,      5,    "slow",
  "704", 0.05,      1,    "fast",
  "704", 0.11,      2,    "fast",
  "704", 0.12,      2,    "slow",
  "704", 0.09,      3,    "fast",
  "704",  0.3,      3,    "slow",
  "704", 0.08,      4,    "fast",
  "704", 0.46,      4,    "slow",
  "704", 0.09,      5,    "fast",
  "704", 0.09,      5,    "slow",
  "705", 0.41,      1,    "fast",
  "705", 0.05,      1,    "slow",
  "705", 0.53,      2,    "fast",
  "705", 0.44,      2,    "slow",
  "705", 0.13,      3,    "fast",
  "705", 0.21,      3,    "slow",
  "705", 0.44,      4,    "fast",
  "705", 0.24,      4,    "slow",
  "705", 0.37,      5,    "fast",
  "705", 0.28,      5,    "slow",
  "706",  0.4,      1,    "fast",
  "706", 0.33,      2,    "fast",
  "706", 0.41,      2,    "slow",
  "706", 0.26,      3,    "fast",
  "706", 0.31,      3,    "slow",
  "706", 0.36,      4,    "fast",
  "706", 0.27,      4,    "slow",
  "706", 0.48,      5,    "fast",
  "706", 0.24,      5,    "slow",
  "707", 0.23,      1,    "fast",
  "707", 0.06,      2,    "fast",
  "707", 0.18,      2,    "slow",
  "707", 0.15,      3,    "fast",
  "707",  0.2,      4,    "fast",
  "707", 0.51,      4,    "slow",
  "707", 0.15,      5,    "fast",
  "707", 0.26,      5,    "slow",
  "708", 0.09,      1,    "fast",
  "708",    0,      1,    "slow",
  "708", 0.18,      2,    "fast",
  "708", 0.21,      2,    "slow",
  "708",  0.2,      3,    "fast",
  "708", 0.34,      3,    "slow",
  "708",  0.1,      4,    "fast",
  "708", 0.13,      4,    "slow",
  "708", 0.18,      5,    "fast",
  "708", 0.21,      5,    "slow",
  "709", 0.25,      1,    "fast",
  "709", 0.02,      1,    "slow",
  "709", 0.27,      2,    "fast",
  "709",  0.1,      2,    "slow",
  "709", 0.11,      3,    "fast",
  "709",  0.2,      3,    "slow",
  "709", 0.26,      4,    "fast",
  "709", 0.19,      4,    "slow",
  "709", 0.19,      5,    "fast",
  "709", 0.14,      5,    "slow",
  "710", 0.04,      1,    "slow",
  "710", 0.17,      1,    "fast",
  "710", 0.19,      2,    "fast",
  "710", 0.11,      2,    "slow",
  "710", 0.11,      3,    "fast",
  "710", 0.09,      3,    "slow",
  "710", 0.13,      4,    "fast",
  "710", 0.24,      4,    "slow",
  "710", 0.08,      5,    "fast",
  "711", 0.19,      1,    "fast",
  "711", 0.15,      2,    "fast",
  "711", 0.26,      2,    "slow",
  "711", 0.33,      3,    "fast",
  "711", 0.36,      4,    "fast",
  "711",  0.3,      4,    "slow",
  "711", 0.19,      5,    "fast",
  "711", 0.58,      5,    "slow",
  "712",  0.2,      1,    "fast",
  "712", 0.08,      1,    "slow",
  "712", 0.07,      2,    "fast",
  "712", 0.18,      3,    "fast",
  "712", 0.12,      3,    "slow",
  "712", 0.25,      4,    "fast",
  "712", 0.14,      4,    "slow",
  "712", 0.21,      5,    "fast",
  "712", 0.18,      5,    "slow"
)

d$ID <- factor(d$ID)
d$g <- factor(d$g)

mod <- mgcv::bam(DV ~ g +
                   s(X, by = g, k = 5, bs = "tp") +
                   s(X, ID,
                     bs = "fs", k = 5, xt = list(bs="tp")) + 
                   s(ID, by = g, bs = "re"),
                 data = d)

emmeans::ref_grid(mod)
#> Error in names(dat) <- object$term: 'names' attribute [2] must be the same length as the vector [1]
```

<sup>Created on 2022-08-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rvlenth** [comment]
The first one is due to a typo, I think. You've defined a model named 'm' then ask for 'emmeans::ref_grid(b)'.
Sent from my iPad

On Aug 10, 2022, at 4:58 AM, Mattan S. Ben-Shachar ***@***.***> wrote:

﻿

I'm getting the following two errors with the new version of emmeans.

Error 1

data("mtcars")
mtcars$cyl <- factor(mtcars$cyl)

m <- mgcv::gam(mpg ~ cyl + s(hp, by = cyl),
               data = mtcars)

emmeans::ref_grid(b)
#> Warning in as.vector(x): restarting interrupted promise evaluation
#> Error in as.vector(x) : object 'b' not found
#> Error in emmeans::ref_grid(b): Perhaps a 'data' or 'params' argument is needed

Created on 2022-08-10 by the reprex package<https://reprex.tidyverse.org> (v2.0.1)

Error 2

d <- tibble::tribble(
  ~ID,  ~DV,     ~X,        ~g,
  "701", 0.23,      1,    "fast",
  "701",    0,      1,    "slow",
  "701", 0.25,      2,    "fast",
  "701", 0.37,      2,    "slow",
  "701", 0.17,      3,    "fast",
  "701", 0.16,      3,    "slow",
  "701", 0.35,      4,    "fast",
  "701", 0.28,      5,    "fast",
  "701", 0.43,      5,    "slow",
  "703", 0.35,      1,    "fast",
  "703", 0.44,      2,    "fast",
  "703", 0.19,      2,    "slow",
  "703", 0.37,      3,    "fast",
  "703", 0.28,      3,    "slow",
  "703", 0.25,      4,    "fast",
  "703", 0.61,      4,    "slow",
  "703", 0.24,      5,    "fast",
  "703", 0.09,      5,    "slow",
  "704", 0.05,      1,    "fast",
  "704", 0.11,      2,    "fast",
  "704", 0.12,      2,    "slow",
  "704", 0.09,      3,    "fast",
  "704",  0.3,      3,    "slow",
  "704", 0.08,      4,    "fast",
  "704", 0.46,      4,    "slow",
  "704", 0.09,      5,    "fast",
  "704", 0.09,      5,    "slow",
  "705", 0.41,      1,    "fast",
  "705", 0.05,      1,    "slow",
  "705", 0.53,      2,    "fast",
  "705", 0.44,      2,    "slow",
  "705", 0.13,      3,    "fast",
  "705", 0.21,      3,    "slow",
  "705", 0.44,      4,    "fast",
  "705", 0.24,      4,    "slow",
  "705", 0.37,      5,    "fast",
  "705", 0.28,      5,    "slow",
  "706",  0.4,      1,    "fast",
  "706", 0.33,      2,    "fast",
  "706", 0.41,      2,    "slow",
  "706", 0.26,      3,    "fast",
  "706", 0.31,      3,    "slow",
  "706", 0.36,      4,    "fast",
  "706", 0.27,      4,    "slow",
  "706", 0.48,      5,    "fast",
  "706", 0.24,      5,    "slow",
  "707", 0.23,      1,    "fast",
  "707", 0.06,      2,    "fast",
  "707", 0.18,      2,    "slow",
  "707", 0.15,      3,    "fast",
  "707",  0.2,      4,    "fast",
  "707", 0.51,      4,    "slow",
  "707", 0.15,      5,    "fast",
  "707", 0.26,      5,    "slow",
  "708", 0.09,      1,    "fast",
  "708",    0,      1,    "slow",
  "708", 0.18,      2,    "fast",
  "708", 0.21,      2,    "slow",
  "708",  0.2,      3,    "fast",
  "708", 0.34,      3,    "slow",
  "708",  0.1,      4,    "fast",
  "708", 0.13,      4,    "slow",
  "708", 0.18,      5,    "fast",
  "708", 0.21,      5,    "slow",
  "709", 0.25,      1,    "fast",
  "709", 0.02,      1,    "slow",
  "709", 0.27,      2,    "fast",
  "709",  0.1,      2,    "slow",
  "709", 0.11,      3,    "fast",
  "709",  0.2,      3,    "slow",
  "709", 0.26,      4,    "fast",
  "709", 0.19,      4,    "slow",
  "709", 0.19,      5,    "fast",
  "709", 0.14,      5,    "slow",
  "710", 0.04,      1,    "slow",
  "710", 0.17,      1,    "fast",
  "710", 0.19,      2,    "fast",
  "710", 0.11,      2,    "slow",
  "710", 0.11,      3,    "fast",
  "710", 0.09,      3,    "slow",
  "710", 0.13,      4,    "fast",
  "710", 0.24,      4,    "slow",
  "710", 0.08,      5,    "fast",
  "711", 0.19,      1,    "fast",
  "711", 0.15,      2,    "fast",
  "711", 0.26,      2,    "slow",
  "711", 0.33,      3,    "fast",
  "711", 0.36,      4,    "fast",
  "711",  0.3,      4,    "slow",
  "711", 0.19,      5,    "fast",
  "711", 0.58,      5,    "slow",
  "712",  0.2,      1,    "fast",
  "712", 0.08,      1,    "slow",
  "712", 0.07,      2,    "fast",
  "712", 0.18,      3,    "fast",
  "712", 0.12,      3,    "slow",
  "712", 0.25,      4,    "fast",
  "712", 0.14,      4,    "slow",
  "712", 0.21,      5,    "fast",
  "712", 0.18,      5,    "slow"
)

d$ID <- factor(d$ID)
d$g <- factor(d$g)

mod <- mgcv::bam(DV ~ g +
                   s(X, by = g, k = 5, bs = "tp") +
                   s(X, ID,
                     bs = "fs", k = 5, xt = list(bs="tp")) +
                   s(ID, by = g, bs = "re"),
                 data = d)

emmeans::ref_grid(mod)
#> Error in names(dat) <- object$term: 'names' attribute [2] must be the same length as the vector [1]

Created on 2022-08-10 by the reprex package<https://reprex.tidyverse.org> (v2.0.1)

**Comment by mattansb** [comment]
Oops! Wow, how embarrassing... I've edited the original issue.

**Comment by rvlenth** [comment]
This relates to an update whereby I excluded random effects from the reference grid. I had used some code that identifies the variables involved with non-random terms, but the code I used had an `ifelse()` in it which causes it to overlook a second variable involved in a term. Thus the `ID` variable in this example didn't get in there. I fixed that, I think:
```r
> ref_grid(mod)
'emmGrid' object with variables:
    g = fast, slow
    X = 3.08
    ID = 701, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712
```
Here is a patch that should make this work for you. (I believe it may also work for issue #366)
``` r
assignInNamespace("recover_data.gam", function(object, ...) {
    if (length(object$smooth) > 0) { # get rid of random terms
        fixnm = unlist(lapply(object$smooth, function(s) {
                              if(inherits(s, "random.effect")) NA    else s$term
            }))
        fixnm = union(.all.vars(delete.response(object$pterms)), fixnm[!is.na(fixnm)])
        object$terms = terms(.reformulate(fixnm, env = environment(terms(object))))
    }
    recover_data.lm(object, ...)
},
"emmeans")
```

**Comment by lucasdeschamps** [comment]
Hello!

Thank you very much for your quick response!

Unfortunately, R prompts that `.reformulate` cannot be found.

If I replace `.reformulate` by `reformulate`, R prompts thant `recover_data.lm` cannot be found.

If I replace `recover_data.lm` by `.recover_data`, the process takes a long time and ends prompting 

`Error : C stack usage  15927968 is too close to the limit`

**Comment by mattansb** [comment]
@lucasdeschamps add `emmeans:::` before `.reformulate`, `recover_data.lm` and `.all.vars`.

@rvlenth Can confirm this works. Thanks!

**Comment by mattansb** [comment]
If you're treating random variables differently (excluding them from the grid), you might also want to do so for the second variable in terms like `s(X, ID, bs = "fs")` which is akin to random smooths of X for each level of ID.

**Comment by rvlenth** [comment]
Re terms like `s(X, ID, bs = "fs")` being basically random effects. If you haven't noticed yet, I understand basically *nothing* about `mgcv::gam()`, so I can only do so much. And at this time I'm not really willing to go beyond looking at `lapply(object$smooth, class)` to see which smooth terms inherit from `"random.effect"`. 
``` r
> lapply(mod$smooth, class)
[[1]]
[1] "tprs.smooth" "mgcv.smooth"

[[2]]
[1] "tprs.smooth" "mgcv.smooth"

[[3]]
[1] "fs.interaction" "mgcv.smooth"   

[[4]]
[1] "random.effect" "mgcv.smooth"  

[[5]]
[1] "random.effect" "mgcv.smooth"  
```

Seems to me that if the `gam` code doesn't regard it as a random effect, it probably shouldn't be regarded as such. And if it should, then **mgcv** needs some design improvements IMHO

**Comment by rvlenth** [comment]
Following up after looking a documentation for smoothers -- should I just always regard terms that inherit from `fs.interaction` as random terms? That's the *example* given in the documentation, but do people use it for fixed effects too?

**Comment by rvlenth** [comment]
OK, well, turns out I broke things with 1.8.0-5. So in 1.8.0-6, I fixed that (probably broke something else) and included `fs.interaction` class as another way to have a random effect. Now we have
``` r
> ref_grid(mod)
'emmGrid' object with variables:
    g = fast, slow
    X = 3.08
```
whereas in previous tries, we also had `ID` as a variable in the grid.

**Comment by mattansb** [comment]
Hey @rvlenth ,

In `s(x, z, y, bs = "re", by = m)` (class `random.effect`) all of x, z, and y are random grouping variables, so it is equivalent to in lme4 `(m | x:z:y)` (m itself *should* be included during model fitting as a separate parametric term, a-la `m + s(x, z, y, bs = "re", by = m)` to get a proper "fixed" effect...).

In `s(x, z, y, bs = "fs", by = m)` (class `fs.interaction`) only one of x, z, or y is a random grouping variable (the only one that is a factor - only one can be), and the rest are akin to random slopes nested in the levels of that variable. So if z is a factor, this would be, in lme4 notation `x*y*z + (x*y*m|z)` (that is, it also includes the "fixed" smooth effects, kinda...).

Hope that helps!

**Comment by rvlenth** [comment]
It's still not totally clear that class `fs.interaction` *always* comprises a random factor interacting with fixed factors; but that does seem to be the main intent of it, so I am now deeming random anything inheriting from `random.effect` or `fs.interaction`. 

I have every reason to believe we're not done here yet, but I'm sure hoping there is light at the end of the horizon. There's a huge number of possibilities. Like am I supposed to include `bs = "mrf"` or `bs = "gp"` as well? Others? If so, maybe someone can provide an example to test.

**Comment by mattansb** [comment]
I haven't used mrf or gp, so I can't help there...

You might want to contact / tag [Gavin Simpson](https://github.com/gavinsimpson) (who, from my experience, is always keen to help)...

**Comment by rvlenth** [comment]
@gavinsimpson -- as suggested, do you have any advice on this? Briefly, I'm trying to identify which effects are random in a fitted `gam` object. As of now, I look at the `$smooth` slot and deem a term random if it inherits from `"random.effect"` or `"fs.interaction"`. Are there other classes that signal random effects? Other places to look besides `$smooth`? (I have also emailed Simon Wood with this question.)

**Comment by gavinsimpson** [comment]
The whole what is and isn't a random effect in a GAM makes my head hurt, but...

I think the motivation behind the `fs` basis (smooths with class `"fs.interaction"`) is to have a random smooth counter part to the random intercepts and slopes in GLMMs. I feel this should be considered a random effect and excluded if you are counting the `re` basis a random effect because the `fs` basis contains a random intercept and a random linear term (there is a diagonal penalty matrix for the constants and linear component of the basis) - it would be inconsistent to exclude smooths with class `"random.effect"` and not those with class `"fs.interaction"` when the latter contains the same structure as the former.

I wouldn't include the `"gp"` basis as a random effect; Simon shows in his book that GPs are penalized smooths once you set the length scale of the covariance functions, so if you were being consistent and don't exclude the other `s()` bases (beyond the `"re"` and `"fs"`) you shouldn't exclude `"gp"`.

Same for `"mrf"`; it's used to include population-level-like information into the model.

It is a little more complicated than just looking at the class of the elements of the `$smooth` component of the model fit.

Consider 

```r
mod <- mgcv::bam(DV ~ g + 
                       s(X, by = g, k = 5, bs = "tp") + 
                       t2(X, ID, 
                         bs = c("tp", "re"), k = c(5, NA), full = TRUE) +  
                       s(ID, by = g, bs = "re"), 
                     data = d)
```

which is the same model as the one posted by @mattansb but with the `"fs"` smooth rewritten in the equivalent tensor product form. You would want to identify that the `t2()` is random and thus for tensor products you also need to look at the `$smooth[[x]]$margin` where `x` is indexing the `x`th smooth in the model. For example:

```r
foo <- function(s) {
  cls <- if (is.null(s$margin)) {
    class(s)
  } else {
    unname(unlist(lapply(s$margin, class)))
  }
  cls
}

lapply(mod$smooth, foo)
```

yielding

```r
r$> lapply(mod$smooth, foo)
[[1]]
[1] "tprs.smooth" "mgcv.smooth"

[[2]]
[1] "tprs.smooth" "mgcv.smooth"

[[3]]
[1] "tprs.smooth"   "random.effect"

[[4]]
[1] "random.effect" "mgcv.smooth"

[[5]]
[1] "random.effect" "mgcv.smooth"
```

such that you'd want to remove the 3rd, 4th, and 5th smooths even though just looking at the class of the smooth elements would suggest removing only the 4th and 5th smooths:

```r
r$> lapply(mod$smooth, class)
[[1]]
[1] "tprs.smooth" "mgcv.smooth"

[[2]]
[1] "tprs.smooth" "mgcv.smooth"

[[3]]
[1] "t2.smooth"   "mgcv.smooth"

[[4]]
[1] "random.effect" "mgcv.smooth"

[[5]]
[1] "random.effect" "mgcv.smooth"
```

**Comment by rvlenth** [comment]
@gavinsimpson Thanks so much -- this is really helpful!

**Comment by rvlenth** [comment]
My streamlined version of this, FWIW. (Illustrated with Gavin's model)
```r
> cls <- lapply(mod$smooth, \(s) c(class(s), unname(unlist(lapply(s$margin, class)))))

> sapply(cls, \(c) any(c("random.effect", "fs.interaction") %in% c))
[1] FALSE FALSE  TRUE  TRUE  TRUE
```

**Comment by rvlenth** [comment]
I think this is finally resolved with the latest **emmeans** CRAN update, so am closing.
