### ISSUE TITLE
Effect sizes for computed contrasts

### ISSUE THREAD

**Issue by mattansb** [rvlenth/emmeans#37]
(Not so much an issue as it is a request)
Are there any plans to add effect sized to contrasts (either partial eta square, or r-square-alerting)?
This would be very useful, as some journals require an effects size to accompany each p-value (and doing this "by hand" is quite tedious).

**Comment by rvlenth** [comment]
Similar requests have been made before. 

I am reluctant, partly because I think it is beyond the purpose of **emmeans**, and partly because I definitely lack the subject-matter expertise. While I know some about effect sizes and the way they are used in social sciences, and it is straightforward to compute them for a one-way anova with homogeneous variances, it is unclear what defines an effect size when it comes to an unbalanced multi-factor mixed model with random slopes and a correlation structure. Perhaps that's an extreme example, but I think the ambiguities start coming in for far simpler situations.

There is also the fact that I have written papers arguing against using standardized effect sizes as a target for sample-size determination. But that is truly beside the point, as I don't claim that they are not useful for other purposes. 

It'd be fine if someone else develops a separate package for effect sizes that uses (or does not use) **emmeans** for some of the computations. Somebody cleverer than I am (and there are many, many such people) can take this on and run with it. But it is not in view as a future feature of this package.

**Comment by rvlenth** [comment]
I am closing this as I think it is inactive.
