### ISSUE TITLE
adjust='none' is ignored by contrast

### ISSUE THREAD

**Issue by malcook** [rvlenth/emmeans#40]
arguably adjust='none' should squelch and p.value adjustments, but does not, as evidenced:

 stopifnot(! identical(coefficients(contrast(warp.emm, "eff", by = NULL)),coefficients(contrast(warp.emm, "eff", by = NULL))))
Error: !identical(coefficients(contrast(warp.emm, "eff", by = NULL)),  .... is not TRUE

THANKS FOR EMMEANS!

**Comment by rvlenth** [comment]
I don't see how this has anything to do with `adjust`, as your snippet does not even contain that keyword.

Moreover, it is not totally obvious what is the starting point for this example. I suppose that `warp.emm` is the object created in the help page for `contrast`, but am not sure. 

As a human, I would rather see an example that shows the actual results thought to be incorrect, rather than computer code that tests it. If I look at part of what is being tested here, I get this:
```
> coefficients(contrast(warp.emm, "eff", by = NULL))
    tension wool        c.1        c.2        c.3        c.4        c.5        c.6
L,A       L    A  0.8333333 -0.1666667 -0.1666667 -0.1666667 -0.1666667 -0.1666667
M,A       M    A -0.1666667  0.8333333 -0.1666667 -0.1666667 -0.1666667 -0.1666667
H,A       H    A -0.1666667 -0.1666667  0.8333333 -0.1666667 -0.1666667 -0.1666667
L,B       L    B -0.1666667 -0.1666667 -0.1666667  0.8333333 -0.1666667 -0.1666667
M,B       M    B -0.1666667 -0.1666667 -0.1666667 -0.1666667  0.8333333 -0.1666667
H,B       H    B -0.1666667 -0.1666667 -0.1666667 -0.1666667 -0.1666667  0.8333333
```
Please note that these are the contrast coefficients for the `"eff"` contrasts. Once again, this has nothing to do with multiplicity adjustments of tests. 

And I think there is a logic error in your `stopifnot(! ...)` construct:
```
> stopifnot(!(2 + 2 == 4))
Error: !(2 + 2 == 4) is not TRUE
```

So please edit your question so I can see (in humanly readable form) what you feel is the undesired behavior of `contrast()` and `adjust`

**Comment by malcook** [comment]
Prof Lenth - 

Thanks for your critical response.  

Mea culpa - from reading documentation I now see that adjust is only taken into account when combine=TRUE.  So, I retract my issue, but will definitely heed your advice into consideration regarding posing issues in general in the future.

**Comment by rvlenth** [comment]
OK. I still am confused about what you had tried but didn't work. I want to make sure you understand that `combine` only affects contrasts when the `simple` specification is used, and that `adjust` is *not* ignored when `combine = FALSE`. 

I am guessing that the issue has something to do with the fact that `adjust` applies separately to each `by` group when there are `by` variable(s) present. When you want to compute contrasts for `by` groups and then view the results as a single family with a common multiplicity adjustment, you have to wrap it in `summary()` with `by = NULL`. For example:
```
> contrast(warp.emm, "consec", by = "tension", adjust = "bonf")
tension = L:
 contrast   estimate       SE df t.ratio p.value
 B - A    -16.333333 5.157299 48  -3.167  0.0027

tension = M:
 contrast   estimate       SE df t.ratio p.value
 B - A      4.777778 5.157299 48   0.926  0.3589

tension = H:
 contrast   estimate       SE df t.ratio p.value
 B - A     -5.777778 5.157299 48  -1.120  0.2682
```
`adjust` was ignored because each family has just one test, so no multiplicity adjustment is needed.  

However, consider:
```
> summary(contrast(warp.emm, "consec", by = "tension"), 
+     by = NULL, adjust = "bonf")
 contrast tension   estimate       SE df t.ratio p.value
 B - A    L       -16.333333 5.157299 48  -3.167  0.0080
 B - A    M         4.777778 5.157299 48   0.926  1.0000
 B - A    H        -5.777778 5.157299 48  -1.120  0.8045

P value adjustment: bonferroni method for 3 tests 
```
The same three comparisons are now combined into one family and the Bonferroni adjustment is applied to that family.

Some additional examples in [the "contrasts" vignette](https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html) may be useful to you.

**Comment by malcook** [comment]
Prof Lenth - I much appreciate your examples and believe I see the point of them but could not have fathomed all these particulars from the documentation - I am emailing you directly to see if you might be interested in providing my some guidance in the particulars of a specific application.  Thanks again - Malcolm
