### ISSUE TITLE
Calculate chi-square instead of F for glm joint tests

### ISSUE THREAD

**Issue by mattansb** [rvlenth/emmeans#400]
Currently, when estimated values have `df = Inf`, the test statistic is labeled `z.ratio`:

```R
library(emmeans)

m <- glm(am ~ factor(cyl), family = binomial("logit"), data = mtcars)

em_cyl <- emmeans(m, ~ cyl)

contrast(em_cyl, method = "pairwise")
#>  contrast    estimate   SE  df z.ratio p.value
#>  cyl4 - cyl6     1.27 1.02 Inf   1.243  0.4279
#>  cyl4 - cyl8     2.77 1.02 Inf   2.717  0.0181
#>  cyl6 - cyl8     1.50 1.08 Inf   1.393  0.3448
#> 
#> Results are given on the log odds ratio (not the response) scale. 
#> P value adjustment: tukey method for comparing a family of 3 estimates
```

But for joint tests, it is labeled `F.ratio`:

```R
(jt_cyl <- joint_tests(em_cyl)) # Gives an F.ratio
#>  model term df1 df2 F.ratio p.value
#>  cyl          2 Inf   3.691  0.0249
#>  
```

whereas a `Chisq = F.ratio * df1` would be (I think) more appropriate:

```R
# Proposed change - for tests with `df2 = Inf`:
as.data.frame(jt_cyl) |> 
  transform(
    Chisq = F.ratio * df1,
    df = df1
  ) |> 
  subset(select = c(`model.term`, df, Chisq, p.value))
#>   model.term df Chisq    p.value
#> 1        cyl  2 7.382 0.02493989
```

Would it be possible to have this changed in `joint_test`?

**Comment by rvlenth** [comment]
This is *not* a bug! Infinite denominator d.f. is supported by R, and there is nothing invalid about using it.

I was resistant to doing this because F with infinite `df2` *is* supported in R and the statistic is always computed *as* an *F* statistic. However, it's easy enough to do, so not worth much of a fight. If we ever have a situation where some `df2`s are infinite and others are finite, we have an error condition lying in wait though. I don't *think* that will ever happen, but who knows?

I opted to *keep* `F.ratio` in the output, always, and add `Chisq` when it is appropriate. Again, the statistic is computed as an F ratio, and its P value is computed using `pf()`, not `pchisq()`
```
> warp.lm = lm(breaks ~ wool * tension, data = warpbreaks)
> joint_tests(warp.lm)
 model term   df1 df2 F.ratio p.value
 wool           1  48   3.765  0.0582
 tension        2  48   8.498  0.0007
 wool:tension   2  48   4.189  0.0210

> neuralgia.glm <- glm(Pain ~ Treatment * Sex + Age, family = binomial(), data = neuralgia) 
> joint_tests(neuralgia.glm)
 model term    df1 df2 F.ratio  Chisq p.value
 Treatment       2 Inf   6.067 12.133  0.0023
 Sex             1 Inf   5.324  5.324  0.0210
 Age             1 Inf   7.601  7.601  0.0058
 Treatment:Sex   2 Inf   0.074  0.148  0.9286
```

**Comment by mattansb** [comment]
Thanks Russell!

I didn't mean to imply this was a bug - just seemed inconsistent with the t/z labeling (`pt(df=Inf)` also works!).

Personally, I always report these cases as Wald Chisq tests, so thanks for indulging me!

**Comment by mattansb** [comment]
Oh, I see this was automatically labelled as a bug when I posted - sorry about that!

**Comment by rvlenth** [comment]
I think we've got this one resolved, so am closing the issue
