### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mateusz1981** [rvlenth/emmeans#41]
I got this error while analysing data with 2 groups, for three groups work fine

NOTE: 'cld()' groupings are determined separately for each list member.
Error in `[[<-.data.frame`(`*tmp*`, nm, value = c(-1, 1)) : 
  replacement has 2 rows, data has 1

**Comment by rvlenth** [comment]
I'm guessing that you did something like
```
emm <- emmeans(model, pairwise ~ ...)
cld(emm)
```
The issue here is that `emm` contains a *list* of two `emmGrid` objects. The first has the EMMs, and the second has the pairwise comparisons. When you called `cld(emm)`, it tried to get the cld for the first one (which you wanted), but also for the second one (which would be comparisons of the comparisons). If there are only two groups, there is only one comparison, and when you try to compare that one comparison with itself, that created an error.

You can avoid the error by doing either
```
cld(emm[[1]])

# or #

cld(emm, which = 1)
```

I had thought I had fixed things so comparing one mean with itself gets handled more gracefully, but I missed a detail. I fixed that detail, and I also changed the method for `cld` so that it refuses to run `cld` on more than one member of a list. Those changes will be in the next push to Github, and in the next CRAN update.

**Comment by rvlenth** [comment]
PS -- Another alternative is to use `cld` in place of `pairwise` in the formula. For example,
```
warp.lm = lm(breaks ~ wool*tension, data = warpbreaks)
emmeans(warp.lm, cld ~ wool | tension)
```

**Comment by rvlenth** [comment]
I believe this has been resolved now, so closing
