### ISSUE TITLE
adjustment method for contrast(combine = TRUE)

### ISSUE THREAD

**Issue by gevro** [rvlenth/emmeans#467]
Is it possible to specify the adjust method in contrast(combine=TRUE) for the combination across the emmeans list? The documentation says that rbind is used to execute combine = TRUE, but the adjust parameter of contrast appears to be ignored and even though I set it to "tukey" the result says it used "sidak". The cross.adjust parameter doesn't work either.

Strangely, when I set adjust = "mvt", the final result says that "mvt" was used. But I would like to use "tukey" both for the standard p-value adjustment, and for the combine=TRUE combination step.

Thanks

**Comment by rvlenth** [comment]
You have to use these functions the way they are documented. In this case,

  * When you combine objects into one group, there are no longer any groups to cross-adjust. Hence anything you put in `cross.adjust` is immaterial.
  * The Tukey adjustment is not allowed except for pairwise comparisons of *one* set of means. That's because for other families of tests, the statistical assumptions are incorrect. So if you ask for `tukey`, it gets changed to something that is allowed, namely `sidak`. This is documented in the [`FAQs` vignette](https://cran.r-project.org/web/packages/emmeans/vignettes/FAQs.html#notukey) and elsewhere.
