### ISSUE TITLE
On Coxph or survival model

### ISSUE THREAD

**Issue by elong0527** [rvlenth/emmeans#47]
I have difficulty to understand the `emmeans` results for `coxph` model. 

Is the default setting of  `emmeans` calculate the linear combination of log hazards? 

Would it possible to have `emmeans` to report the estimated survival curve? 

For example, in the code below, would it be possible to create the estimated survival probability based on a user-defined time (e.g. time = 1)? 

```
library(survival)
library(emmeans)
# Create the simplest test data set 
test1 <- list(time=c(4,3,1,1,2,2,3), 
              status=c(1,1,1,0,1,1,0), 
              x=c(0,2,1,1,1,0,0), 
              sex=c(0,0,0,0,1,1,1)) 
# Fit a stratified model 
fit <- coxph(Surv(time, status) ~ x + factor(sex), test1) 
emmeans(fit, specs = "sex")
```  

```
 sex     emmean        SE df asymp.LCL asymp.UCL
   0 -0.4001928 0.6034757 NA -1.582983 0.7825979
   1  0.5335904 0.8046343 NA -1.043464 2.1106447

Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
```

**Comment by rvlenth** [comment]
At this time, at least, it is not possible to estimate the hazard function -- or the survival function -- itself with the existing **emmeans** support. For instance, the `time` variable isn't even represented in the reference grid; for your example:
```
> ref_grid(fit)
'emmGrid' object with variables:
    x = 0.71429
    sex = 0, 1
Transformation: “log” 
```
I am not sure even how to approach it. I am no expert on survival analysis, and I may well be missing something here; but it appears that the Cox model parameters can be estimated without directly estimating the hazard function; and that the estimated hazard function does not appear to be a part of a `coxph` object. I will check with some colleagues who are a lot more conversant with these topics than I am, but right now I don't even see a way to do this.

**Comment by rvlenth** [comment]
Looking at this further, I think you may use the `survfit` function to estimate the survival curve using one of the methods it provides for. The documentation recommends providing a `newdata` argument, and for that you may use the `"grid"` slot of an `emmGrid` object. For example:
```
# Two survival curves, one for each sex, at x = .71429:
survfit(fit, newdata =ref_grid(fit)@grid)

# 6 survival curves for each combination of sex and x = .25, .5, .75:
sf = survfit(fit, newdata = ref_grid(fit, at=list(x=c(.25,.5,.75)))@grid)
summary(sf)
plot(sf)
plot(sf[1], conf = TRUE)
```
As I understand it, you use the `type` argument in `survfit` to determine what method is used to estimate the survival curve.

I was going to say that you could use `emmeans()` in more complex Cox models to average over some factors and obtain marginal survival curves; but now I realize that won't work because the levels of those factors averaged over will not be included in `newdata` and so `survfit` won't work. So, in principle, it'd be a useful addition to be able to add support for fitting survival curves and hazard curves to **emmeans**; however, I remain quite unsure about how to go about it. Seems though that the right approach, if it's doable, might be to provide **emmeans** support for the `survfit` object rather than the `coxph` one.

**Comment by rvlenth** [comment]
Closing, as I don't think there is much I can do to facilitate this in **emmeans**
