### ISSUE TITLE
Bump minimum needed R version to 4.3

### ISSUE THREAD

**Issue by IndrajeetPatil** [rvlenth/emmeans#489]
`{estimability}` is a runtime or hard dependency of `{emmeans}`, which needs `R 4.3`. 

<img width="689" alt="Screenshot 2024-05-11 at 21 42 11" src="https://github.com/rvlenth/emmeans/assets/11330453/e7571495-1aa7-49ed-914c-0bad0a4ac4cb">

---

This means that anyone on `R < 4.3` system can't actually install `{emmeans}`. But this is not reflected in the minimum needed R version specified in `DESCRIPTION`:

https://github.com/rvlenth/emmeans/blob/420328de19d9916135ed84b64b7ee5252e2a50ec/DESCRIPTION#L17

**Comment by rvlenth** [comment]
You're right, of course. The dependency bump in **estimability** is because in R version 4.3, responsibile estimability checking was FINALLY  added the `predict.lm`. That kind of obviates the need for `estimability::epredict()`. 

I hadn't thought carefully about the effect of this on **emmeans**, and I'd be inclined -- if possible -- to try to put through an update of **estimability** that does not require as high an R version. I have to look carefully to ensure that **estimability** will actually work with lower R versions, rather than bumping up the requirements for **emmeans**. I'll let you know soon.

**Comment by IndrajeetPatil** [comment]
Softening the required R version to 4.1, if possible, would be an even better solution!

Thanks a lot.

**Comment by rvlenth** [comment]
The updated estimability 5.1 was just submitted to CRAN. Or you can install it from GitHub.

**Comment by IndrajeetPatil** [comment]
Thanks for quickly resolving this!

**Comment by rvlenth** [comment]
Thanks for calling it to my attention. This put some srious constraints on any other package depending on **estimability**.
