### ISSUE TITLE
Adding the following function for pooling ready emmeans objects to the emmeans package

### ISSUE THREAD

**Issue by Generalized** [rvlenth/emmeans#502]
With regard to my other issue, where I described the case with multiply imputed data, I took the code from your package and changed it a little to allow for pooling emmeans rather than analysis objects.

This is especially helpful when we need to do a pooled analysis using some special features of the used modelling package, not handled out of the box by emmeans.

The function - adaptation of your `emmeans:::emm_basis.mira` code:
```
pool_emmeans <- function(emmeans_list) {
  bas = emmeans_list[[1]]
  k = length(emmeans_list)
  V = 1/k * bas@V
  allb = cbind(bas@bhat, matrix(0, nrow = length(bas@bhat), ncol = k - 1))
  
  for (i in 1 + seq_len(k - 1)) {
    basi = emmeans_list[[i]]
    V = V + 1/k * basi@V
    allb[, i] = basi@bhat
  }
  bas@bhat = apply(allb, 1, mean)
  notna = which(!is.na(bas@bhat))
  bas@dfargs$m = k
  bas@dfargs$df1 = bas@dffun
  bas@dfargs$B = cov(t(allb[notna, , drop = FALSE]))
  bas@V = bas@dfargs$T = V + (k + 1)/k * bas@dfargs$B
  bas@dffun = function(a, dfargs) {
    dfcom = dfargs$df1(a, dfargs)
    with(dfargs, {
      b = sum(a * (B %*% a))
      t = sum(a * (T %*% a))
      lambda = (1 + 1/m) * b/t
      dfold = (m - 1)/lambda^2
      dfobs = (dfcom + 1)/(dfcom + 3) * dfcom * (1 - lambda)
      ifelse(is.infinite(dfcom), dfold, dfold * dfobs/(dfold + dfobs))
    })
  }
   return(bas)
}
```

An exemplary use:
```
> d <- structure(list(ID = structure(c(1L, 1L, 1L, 2L, 2L, 2L, 3L, 3L, 
3L, 4L, 4L, 4L, 5L, 5L, 5L, 6L, 6L, 6L, 7L, 7L, 7L, 8L, 8L, 8L, 
9L, 9L, 9L, 10L, 10L, 10L, 11L, 11L, 11L, 12L, 12L, 12L, 13L, 
13L, 13L, 14L, 14L, 14L), levels = c("1", "2", "3", "4", "5", 
"6", "7", "8", "9", "10", "11", "12", "13", "14"), class = "factor"), 
Arm = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L), levels = c("A", "B"), class = "factor"), Visit = structure(c(1L, 
2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 
2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 
2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L), levels = c("V1", 
"V2", "V3"), class = c("ordered", "factor")), Visit_non_ord = structure(c(1L, 
2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 
2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 
2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L), levels = c("V1", 
"V2", "V3"), class = "factor"), Painscore = c(1L, 2L, 4L, 
5L, 6L, NA, 4L, 2L, 3L, 4L, 3L, 4L, 5L, NA, 5L, 6L, 7L, 6L, 
4L, 3L, 5L, 1L, NA, 4L, 5L, 4L, 5L, 4L, 6L, NA, 0L, 4L, 3L, 
4L, NA, 4L, 3L, 4L, NA, 6L, 7L, 8L)), row.names = c(NA, -42L
), class = "data.frame")

> library(mice)
> library(glmtoolbox)

> imp <- mice(d, m=5)
> imp$predictorMatrix[1:4, 1:5] <- 0
> imp$predictorMatrix[5, 1] <- 0
> imp <- mice(d, m=5, predictorMatrix = imp$predictorMatrix)
> imp_list <- complete(imp, "all")

> trend_emms <- lapply(imp_list, 
                    function(dat) {
                        m <- glmgee(Painscore ~ Visit * Arm, 
                                    family = gaussian(link = "identity"), 
                                    id = ID,  
                                    data=dat, 
                                    corstr = "unstructured")
                        
                        emmeans(m, 
                                specs = ~ Visit | Arm,
                                adjust="none", 
                                vcov =  vcov(m, type = "bias-corrected"))   # this is not accessible from within emmeans
                      })

> pooled_ems <- pool_emmeans(trend_emms)
> contrast(pooled_ems, "poly", max.degree=2, by = "Arm")

Arm = A:
 contrast  estimate    SE    df t.ratio p.value
 linear        0.40 0.753 16.10   0.531  0.6026
 quadratic     1.03 1.168 17.48   0.881  0.3903

Arm = B:
 contrast  estimate    SE    df t.ratio p.value
 linear        1.40 0.752 13.01   1.861  0.0855
 quadratic    -1.74 1.864  7.54  -0.935  0.3787
```

Would you consider adding this little "helper" to your package?

**Comment by rvlenth** [comment]
How about if you post this on Cross Validated. and I will consider including a link to that posting in the "models" vignette.

**Comment by adrianolszewski** [comment]
@rvlenth Dear Professor,
Would this format be appropriate to be linked in the vignette?
It will be easier to update if something changes in future.

https://github.com/adrianolszewski/Useful-R-codes/blob/main/Pooling%20emmeans%20objects.md

**Comment by rvlenth** [comment]
Thanks. I am adding this link to the `models` vignette. In doing so, I found I had done something like this before related to issue #446. I think these are not all that related, but I could be wrong, and in any case you may be interested.

**Comment by adrianolszewski** [comment]
Thank you so much!

And also I updated the example:
- simplified the dataset, 
- provided a more useful example with 2 approaches (the default one vs. lapply + pool_emmeans), 
- polished the descriptions and explained things step-by-step to show better **when** this approach may be useful.

**Comment by adrianolszewski** [comment]
Dear Professor,

I apologize for bringing this topic up again and asking for something that, I understand, may not be to your liking...

...but would you be willing to consider adding this above-mentioned pooling function to emmeans?

I know (and I'm so grateful!) that you have already added a relevant reference to my examples (https://github.com/adrianolszewski/Useful-R-codes/blob/main/Pooling%20emmeans%20objects.md) in the emmeans manual. 

But let me explain myself. Recently, while working on clinical trials, I've been collaborating with several R programmers. Some of them are advanced statisticians coming from the SAS world. To them - emmeans is just like a "revelation". **They love it.** Now, from time to time they ask me about models or fitting procedures that are implemented in R but not directly supported by the `emmeans`. Moreove, they need it under multiple imputation (mostly done via `mice`).

It's a simple task if the requested models are supported directly by the mice & emmeans tandem, so everything happens "auto-magically".

However, for some models they need to go through qdrg() --> emmeans() --> pooling(). It would be super helpful to have even this simple function above-mentioned ready to use already in the package...

**Comment by adrianolszewski** [comment]
Ouch, you asked right questions and I must admit - my idea wasn't good...

**Regarding question 1**
Alas, I cannot give any reasonable, unbiased estimates other than rough guesses...

The popularity of R in the pharmaceutical industry increases yearly (from almost 0 job advertisements in 2015 to many such offers just weekly), so I guess there will be more interest in methods involving multiple imputation and many kinds of models used there for more advanced hypothesis testing. So, for example, ordinal responses (so common in clinical trials), through a variety of GEE-estimated models (GEE principle is a workhorse in pharma, applied to many kinds of omodels, and there exists over R 25 packages for that, many of which able to do something specific, that no other packages do), exact and Firth-penalised models for rare-event studies, frailty survival models, even recently GEE marginal quantile regression, etc...

/ A recent post from the LinkedIn, where a SAS-raised Author, senior biostatistician, explores the possibilities of R and does first steps, learning emmeans and other packages. There are dozens such posts monthly, gaining interest and involving discussions, and in some (say 2-3 per quarter) people ask about the integration of something with emmeans.

<img width="990" height="1388" alt="Image" src="https://github.com/user-attachments/assets/9fbc4ddd-4b3d-4a50-a396-5446a2cb5a04" />

<img width="259" height="42" alt="Image" src="https://github.com/user-attachments/assets/852e1b22-0723-460a-a0b3-e1bc03538f7b" />

/

Some packages are well-known and supported by emmeans.

But the R ecosystem is **very dynamic**. Some packages are getting replaced fully or partially by others (like geeplack replaced slowly by the glmtoolbox; which -by the way- got a great support, including emmeans, marginaleffects, broom, etc.). Many new packages appear, e.g. for Firth-penalised logistic regression, for robust and rank-based regression models (such as the `Rfit` package). Some are outdated and getting replaced. Those new implementations appear quickly and soon are noticed and considered by biostatisticians for experimentation to prove or disprove their usefulness in clinical trials.

Authors of such packages often do not understand the need for clean and proper structuring the returned outcomes and the big importance of being compliant with packages like emmeans (and marginaleffects) in clinical trials.

I believe you faced it many times, when many people, including me, asked you for supporting some kind of model. One author names it "result$robust_vcov", another "result$vcov", "result@vcov", "vcov(result)" and there are just endless ways of doing the same thing. Some return the coefficients via result$coefficients, result@betas, result$zeta (for intercepts in ordinal models), result$B, result$coef, and so on... The `broom` and related packages was made to help there (`mice` uses it extensively), but still "creativity prevails"...

And because it's not the emmeans's goal to fit to every new model structure appearing suddenly and massively, and also the authors of these packages either don't understand or don't care, the `qdrg()` is an extremely important part of your package, at least for this field.

But honestly I cannot "promise" this will be used on daily basis by many users, so maybe indeed this work if futile.

**Regarding question 2**
Your questions opened my eyes.

Indeed - I cannot find any reasonable way to prevent from using specific contrasts first and then pool it, other than the classic D1...D4 methods of pooling entire "products", like chi2 statistics (so the certain contrast serves as the input Wald's statistic to pool), or ignoring the DF and proceed under infinite degrees of freedom (which may work at least for GEE under Wald's asymptotic inference).

I cannot even guarantee that the way that is proposed to pool ready emmeans is entirely valid. I read the code of the pooling function, based on the `emm_basis.mira` and it seems it just uses emmeans just a "proxy object" to a model, used only to retrieve the underlying coefficients, DFs, and covariances. So for the basic use where the `specs` parameter matches the formula model (e.g. `response ~ A * B` and then `specs = ~ A*B`) this should work.

But if the user specifies the `specs` in any different way, this may diverge.

I apologize for taking your time with this, **but your response opened my eyes.** and I thank you for this opportunity!
Now I understand better why this should probably remain outside emmeans and be used only in a set of scenarios limited to simple `specs`.
