### ISSUE TITLE
Question re: emmeans estimates vs. gamlss estimates

### ISSUE THREAD

**Issue by averill-murray** [rvlenth/emmeans#61]
I am using 'emmeans' with a gamlss object with a model containing a single factor with 6 levels applied to both mu and nu. I am interested in the contrasts between factor levels for nu. The emmeans function returns the same values for the intercept and SE for nu as given by the summary of the gamlss object. However, none of the other factor levels are the same (emmeans produces more negative estimates with smaller SEs). Am I missing something simple?

**Comment by rvlenth** [comment]
If I understand your question right, the summary of the `gamlss` object would be for the regression coefficients. When the predictor is a factor with 6 levels, most software creates a set of 5 dummy variables to represent it. There are many ways to do this, but the default in R is based on the `contr.treatment()` function, which consists of variables `x2, x3, ..., x6` where `xj` is 1 for the jth level of the factor, and 0 otherwise. Note that there is no `x1`, and that means that for the first treatment, the only nonzero predictor is the intercept. It follows that the estimated intercept is the EMM for the first treatment (call this quantity EMM1). Now look at the second treatment, where the nonzero predictors are the intercept and `x2`, so that the prediction for that case is `b0 + b2*x2`, which reduces to EMM1 + b2 (since `x2 = 1`). This prediction should be equal to EMM2; that is, EMM1 + b2 = EMM2, or b2 = EMM2 - EMM1. Similarly, b3 = EMM3 - EMM1, etc.

I think if you look at the results you have you will find this to be true: that the intercept is the first EMM, and the subsequent coefficients are differences between the remaining EMMs and the first one. Or equivalently, if you do `pairs(emm, reverse = TRUE)` where `emm = emmeans(model, "treatment")`, then the pairwise differences involving the first treatment level are equal to the regression coefficients in the `gamlss` summary. Check it out and see if that's the case. I'll bet it is.

**Comment by averill-murray** [comment]
Exactly. Thank you for the clear explanation!
