### ISSUE TITLE
Problems with glm confidence intervals

### ISSUE THREAD

**Issue by mcfanda** [rvlenth/emmeans#7]
Hi,
I'm estimating confidence intervals with emmeans on a glm model and found discrepancies with `confint()` function. 
An example can be done using data from  SAS user guide which I saved [here](https://github.com/mcfanda/gamlj_docs/blob/master/data/neuralgia.csv).

The dep var (Pain) is binary and the factor is 3-level (Treatment). I code Treatment with `contr.treatment` so the intercept of the model will be the expected logit for Treatment=A

`contrasts(dat$Treatment)<-contr.treatment(3,base=1)`
`model<-glm(Pain~Treatment,data=dat,family = binomial())`
`summary(model)`

The summary indicates that the intercept is -1.0986, with SE=0.51639. Asking for CI I get
`confint(model)`
`(Intercept) -2.2218727 -0.1504401`

If now I run the `emmeans()` function I get (ci bounds are the last two numbers)
`emmeans(model,~Treatment)`
`A         -1.098612 0.5163973 NA -2.11073247 -0.08649211`

The estimate is the same, the SE is the same, but the confidence interval is different. Is this ok?
I found this behavior to be general, as it applies to many different examples.
Thanks a lot for the great material
marcello

**Comment by rvlenth** [comment]
For what it's worth, this dataset is available in the package as `neuralgia`, and is used as an example in one of the package vignettes. I fitted the model using that dataset:

```
> model <- glm(Pain ~ Treatment, data=neuralgia, family = binomial())
> df = summary(emmeans(model, "Treatment"))
> df
 Treatment    emmean        SE  df   asymp.LCL   asymp.UCL
 A         -1.098612 0.5163973 Inf -2.11073247 -0.08649211
 B         -1.098612 0.5163973 Inf -2.11073247 -0.08649211
 P          1.098612 0.5163973 Inf  0.08649211  2.11073247

Results are given on the logit (not the response) scale. 
Confidence level used: 0.95 
```

... which are the same results you report. Having saved the results as a data frame, I'll compare the half-width of the CIs with the hand-computed widths:

```
> (df[[6]] - df[[5]])/2
[1] 1.01212 1.01212 1.01212

> df[[3]] * 1.96
[1] 1.012139 1.012139 1.012139
```

This confirms that **emmeans** is indeed using plus or minus `1.96 * SE` to obtain them.

Now, if I use `confint()` on the model:

```
> confint(model)
Waiting for profiling to be done...
                 2.5 %     97.5 %
(Intercept) -2.2218727 -0.1504401
TreatmentB  -1.4589319  1.4589319
TreatmentP   0.8357014  3.7317441
```

I believe that the key to your question is in the message *"Waiting for profiling to be done"*. If I do `? confint.glm`, I find that it is done by the **MASS** package, and included in the material is:

>These confint methods call the appropriate profile method, then find the confidence intervals by interpolation in the profile traces. If the profile object is already available it should be used as the main argument rather than the fitted model object itself.

Thus, the intervals are *not* being computed using the estimates and standard errors. You can get closer to the same results via

```
> confint.lm(model)
                 2.5 %      97.5 %
(Intercept) -2.1326801 -0.06454446
TreatmentB  -1.4623927  1.46239274
TreatmentP   0.7348318  3.65961732
```

These differ only slightly from the **emmeans** results -- because `confint.lm()` uses a *t* with 57 d.f. instead of the *z* cutoffs.

**Comment by mcfanda** [comment]
Thank you, that clarifies my doubts (I should have come to that by reading MASS material :-) )
mc
