### ISSUE TITLE
Can't use `at` argument on existing `emmGrid`

### ISSUE THREAD

**Issue by mattansb** [rvlenth/emmeans#82]
The `at` argument does not work as expected when working on an existing `emmGrid`. For example:
``` r
library(emmeans)

fit <- lm(yield ~ nitro + Block + Variety, nlme::Oats)

my_grid <- emmeans(fit,~Block + Variety)

# doesn't work as expected:
emmeans(my_grid,~Block, at = list(Block = 'V'))
#>  Block emmean   SE df lower.CL upper.CL
#>  VI      96.2 4.42 63     87.4    105.1
#>  V       90.9 4.42 63     82.1     99.8
#>  III     95.9 4.42 63     87.1    104.8
#>  IV      98.2 4.42 63     89.3    107.0
#>  II     107.2 4.42 63     98.4    116.1
#>  I      135.3 4.42 63    126.5    144.2
#> 
#> Results are averaged over the levels of: Variety 
#> Confidence level used: 0.95
```

Although might not make much sense in the above scenario, it would be very useful when combined with `add_grouping` to examine only certain levels of the new grouping variables (the example bellow also doesn't make much sense):

``` r
my_nested <- add_grouping(my_grid,'halves','Block',
                          c('4-5','4-5','1-3','4-5','1-3','1-3'))

emmeans(my_nested,~halves, at = list(halves = '1-3'))
#>  halves emmean   SE df lower.CL upper.CL
#>  1-3     112.8 2.55 63      108      118
#>  4-5      95.1 2.55 63       90      100
#> 
#> Results are averaged over the levels of: Block, Variety 
#> Confidence level used: 0.95
```

**Comment by rvlenth** [comment]
It has never been possible to use `at` on an existing reference grid, because `at` is an argument for *constructing* the grid from a model. 

Also, I don't see what you're trying to accomplish with `emmeans(my_grid,~Block, at = list(Block = 'V'))`; if `at` worked, wouldn't that just be `my_grid[2]`?

To restrict to a smaller number of cases, you can use the `[]` operator (the `@grid` slot may be helpful in identifying which rows you want to subset). Or you can use use `contrast()` with `include` or `exclude`, or you can start over with the model and use `at`

**Comment by rvlenth** [comment]
I think this is resolved, so am closing.
