### ISSUE TITLE
Vignette guidance results in Warning message

### ISSUE THREAD

**Issue by rpmady** [rvlenth/emmeans#89]
If emmeans() doesn't work as expected, this [vignette](https://cran.r-project.org/web/packages/emmeans/vignettes/FAQs.html#numeric) advises to use factor(trtmt). I did that, but then I received a warning when I tried emmeans() 

`Warning message:
In model.frame.default(trms, grid, na.action = na.pass, xlev = xlev) :
  variable 'trtmt' is not a factor`

**Comment by rvlenth** [comment]
The vignette says that, but read it carefully. You need to do that when *fitting the model*. See `?pigs` for an example. 

In addition, of course, `trtmt` must be the name of a predictor that is used in the model.

### Note
If you have more questions, please re-open one of these existing issues and post it there, rather than creating a new issue.

**Comment by rpmady** [comment]
Sorry I didn't make that clear that I did factor(trtmt) when I fit the model, and yes trtmt is the name of the categorical predictor in the model. My thought is that it might be because of the function I am using to fit the model, glmm.TMB, already takes care of that? Or the fact that trtmt is already recognized as a factor in the dataframe.

**Comment by rvlenth** [comment]
Show me the results of `summary()` for your model, and how you called `emmeans()` that produced the message you show.

**Comment by rpmady** [comment]
Here is the model and summary results:
`zip_tut <- glmmTMB(sum.50 ~ factor(trtmt) + min_aft_sunrise2 + mintemp2 + factor(snow_cover) + (1|site), data = data_tuti, ziformula=~1, family = poisson)
`
`summary(zip_tut)`
```
 Family: poisson  ( log )
Formula:          sum.50 ~ factor(trtmt) + min_aft_sunrise2 + mintemp2 + factor(snow_cover) +      (1 | site)
Zero inflation:          ~1
Data: data_tuti

     AIC      BIC   logLik deviance df.resid 
   140.7    160.1    -61.3    122.7       55 

Random effects:

Conditional model:
 Groups Name        Variance  Std.Dev. 
 site   (Intercept) 2.869e-15 5.357e-08
Number of obs: 64, groups:  site, 9

Conditional model:
                             Estimate Std. Error z value Pr(>|z|)    
(Intercept)                -2.299e+00  7.534e-01  -3.051 0.002278 ** 
factor(trtmt)hotspot        3.212e+00  7.297e-01   4.401 1.08e-05 ***
factor(trtmt)pulsed_food    2.584e+00  7.635e-01   3.384 0.000714 ***
factor(trtmt)pulsed_nofood -1.890e+01  1.297e+04  -0.001 0.998837    
min_aft_sunrise2           -3.038e-02  1.249e-01  -0.243 0.807805    
mintemp2                   -1.898e-01  1.218e-01  -1.558 0.119169    
factor(snow_cover)Y         1.080e-01  3.112e-01   0.347 0.728527    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Zero-inflation model:
            Estimate Std. Error z value Pr(>|z|)  
(Intercept)  -2.0979     0.8917  -2.353   0.0186 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```
`emm.t.s <- emmeans(zip_tut, "trtmt")`

Gives me the following warning: 
```
Warning messages:
1: In model.frame.default(trms, grid, na.action = na.pass, xlev = xlev) :
  variable 'trtmt' is not a factor
2: In model.frame.default(trms, grid, na.action = na.pass, xlev = xlev) :
  variable 'snow_cover' is not a factor
```

**Comment by rvlenth** [comment]
It appears to me that for some reason, `emmeans()` isn't able to reconstruct the data. Perhaps it will work correctly if you explicitly specify the data:
```
emm.t.s <- emmeans(zip_tut, "trtmt", data = data_tuti)
```
Another possibility (unlikely but possible) is that the data frame `data_tuti` has been corrupted or deleted since the model was fitted. That'd cause this error too.

But it is also clear to me that the model should work just fine *without* the `factor()` calls. You need those only when you want to use a numeric variable as a factor, and here I can tell that `trtmt` has character levels like `hotspot` and `pulsed_food`, while `snow_cover` has character levels `Y` (and `N` is my guess).

**Comment by rpmady** [comment]
Thanks for the suggestions. I tried specifying the data, but still received warnings. I also reloaded data_tuti to see if corruption or deletion was a problem. The only way I got emmeans() to run was by taking out factor() from the model. Like you said, the model should work fine without the factor() calls. And now the results from emmeans() seem more reasonable. Maybe I just needed to reload R or some other weird quirk of the program.
